### ISSUE TITLE
Switch to View mode crashes

### ISSUE THREAD

**Issue by adriaaah** [stefan-niedermann/nextcloud-notes#1038]
**Describe the bug**
Notes can't be viewed in "View mode" (eye icon option) because the app crashes. However they can be accessed and edited from the Edit view.

**To Reproduce**
1. Click on any note (no matter if you've just created it or it's an existing one)
2. Click on the Eye icon in order to switch to "Read-only" view.
3. The app crashes, displaying a stack trace (please see below)

**Expected behavior**
Jump between Edit and View modes at any time.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.19.0
 - F-Droid or Play Store: fdroid
 - Android-Version: 6.0.1
 - Device: A0001
 - OS Version: 3.4.110-cyanogenmod-ge6be560(3c3f0aca9b)
 - OS API Level: 23
 - Manufacturer: OnePlus
 - Model (and Product): A0001 (bacon)

**Server**
 - Nextcloud version: 20.0.4
 - Nextcloud Notes version (server app): 4.0.2
 - Files App Version Code: 30140190

**Stacktrace**
```
android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer
	at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
	at it.niedermann.owncloud.notes.databinding.FragmentNotePreviewBinding.inflate(FragmentNotePreviewBinding.java:65)
	at it.niedermann.owncloud.notes.edit.NotePreviewFragment.onCreateView(NotePreviewFragment.java:77)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer
	at android.view.LayoutInflater.createView(LayoutInflater.java:645)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
	... 22 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at android.view.LayoutInflater.createView(LayoutInflater.java:619)
	... 31 more
Caused by: java.lang.NoClassDefFoundError: it.niedermann.android.markdown.markwon.-$$Lambda$MarkwonMarkdownViewer$qsmyUNStj9yyyg1WAXI7aCfaAjw
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:49)
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:44)
	... 33 more
```

**Comment by stefan-niedermann** [comment]
Thanks for the report. Should be fixed in `v3.0.1` - If it still occurs in this version or higher, just reopen the issue or create a new one.
