### ISSUE TITLE
app crash when using the view mode

### ISSUE THREAD

**Issue by hugodu69** [stefan-niedermann/nextcloud-notes#1057]
**Android version:** 3.10.49

**Device**: Lenovo A6020a46

**System language**: french

**App version:** v3.1.1

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. click on a note
  3. click on the eye to switch to view mode
  4. app crash (since the previous update of the app)

this is the crash report :

```
App Version: 3.1.1
App Version Code: 3001001
App Flavor: fdroid

Files App Version Code: 30130090

---

OS Version: 3.10.49-perf-g4714f7e(A6020a46_S056_161019_ROW)
OS API Level: 22
Device: A6020a46
Manufacturer: LENOVO
Model (and Product): Lenovo A6020a46 (A6020a46)

---

android.view.InflateException: Binary XML file line #23: Error inflating class it.niedermann.android.markdown.MarkdownViewerImpl
	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
	at it.niedermann.owncloud.notes.databinding.FragmentNotePreviewBinding.inflate(FragmentNotePreviewBinding.java:65)
	at it.niedermann.owncloud.notes.edit.NotePreviewFragment.onCreateView(NotePreviewFragment.java:77)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
	at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
	at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
	at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
	at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5268)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
	... 28 more
Caused by: java.lang.NoClassDefFoundError: it.niedermann.android.markdown.markwon.-$$Lambda$MarkwonMarkdownViewer$N0nQp3p98292jlHz07UHK8yKrAg
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.createMarkwonBuilder(MarkwonMarkdownViewer.java:89)
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:68)
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.<init>(MarkwonMarkdownViewer.java:63)
	at it.niedermann.android.markdown.MarkdownViewerImpl.<init>(MarkdownViewerImpl.java:18)
	... 31 more

```

**Comment by stefan-niedermann** [comment]
https://github.com/stefan-niedermann/nextcloud-notes/issues/1056#issuecomment-771830500

**Comment by hugodu69** [comment]
sorry, i searched for existing issue, but i was on my phone, small screen, i missed it somehow
