### ISSUE TITLE
Synchronization failed

### ISSUE THREAD

**Issue by bushrang3r** [stefan-niedermann/nextcloud-notes#1064]
App fails to synchronize.

**To Reproduce**
1. Start the app.
2. It begins its initial sync
3. Message appears at the bottom 'Synchronization failed'

**Expected behavior**
Synchronization succeeds

**What I've tried**
I have force closed both the Notes and Nextcloud apps and cleared the caches of both.

**Smartphone**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Redmi note 8 pro

**Server**
 - Nextcloud version: 19.0.4
 - Nextcloud Notes version (server app): 3.6.4

**Stacktrace**

````
App Version: 3.1.2
App Version Code: 3001002
App Flavor: fdroid

Files App Version Code: 30150090

---

OS Version: 4.14.215-QuantumKiller-N(eng.bricko.20210114.113350)
OS API Level: 30
Device: begonia
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8 pro (begonia)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.putNote(NotesClientV1.java:41)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.editNote(NotesClientV1.java:49)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:373)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)


com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.getNotes(NotesClientV1.java:31)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

````

**Comment by stefan-niedermann** [comment]
Please try the steps mentioned in our [FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error) and tell us whether they were successful or not.

**Comment by bushrang3r** [comment]
Thanks for the tip.
I cleared the storage of the Notes app only, and set it up again (connected it to the Nextcloud app).
This solved the problem.
