### ISSUE TITLE
Already existing Notes don't show up after first sync

### ISSUE THREAD

**Issue by boinappi** [stefan-niedermann/nextcloud-notes#1067]
Hi!
Bought your app today and i'm a bit disappointed.

Already existing notes (approx 1500 Notes, 400MB with media) don't show up after adding a new account and granting access. The sync fails with the error below.

When adding a new Note it shows up - the new Note is also synced and appears in the Note folder in cloud.

```
App Version: 3.1.2
App Version Code: 3001002
App Flavor: play

Files App Version Code: 30130190
OS Version: 4.4.192-perf+(00WW_4_16E)
OS API Level: 29
Device: B2N_sprout
Manufacturer: HMD Global
Model (and Product): Nokia 7 plus (Onyx_00WW)
com.nextcloud.android.sso.exceptions.UnknownErrorException: Read timed out
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
at it.niedermann.owncloud.notes.persistence.NotesClientV02.getNotes(NotesClientV02.java:31)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
at android.os.AsyncTask$3.call(AsyncTask.java:378)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
Apperently there is a read time out because the size of all notes is too large for a single synchronization roundtrip.

Can you try to move all your notes to a different folder and then back in chuncks step by step?

Please let me know whether the synchronization works that way.

**Comment by stefan-niedermann** [comment]
ping @boinappi

**Comment by boinappi** [comment]
> Can you try to move all your notes to a different folder and then back in chuncks step by step?

I just tried a "häppchenweise" sync - and this seems to work.

Feel free to move this suggestions to an enhancement labeled ticket:

- Don't abort the sync when syncing works, but will take a long time
- Start a sync in smaller chunks instead
- Inform the user about whats going on

**Comment by boinappi** [comment]
May be related, as i'm using also QOwnNotes: https://github.com/stefan-niedermann/nextcloud-notes/issues/761

**Comment by stefan-niedermann** [comment]
Thanks for the update! Glad to hear that it is working now. I agree that this is an issue and will have a talk to the maintainer of the server app since your proposal requires changes in the API.

Could you please contact me via E-Mail at info@niedermann.it (i speak german)?
