### ISSUE TITLE
Update to 3.3.0 on Android Breaks 

### ISSUE THREAD

**Issue by edrohler** [stefan-niedermann/nextcloud-notes#1128]
**Description**
After upgrading to v3.3.0 thru F-Droid, I was asked to select the account and synchronization errored out.

I cleared the cache, cleared the storage, forced closed the app which resulted in the same error.

I uninstalled and installed which resulted in the same error.

**To Reproduce**
1. Update App through F-Droid
2. Edit a note
3. Synchronize changes
5. Receive error

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.0
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11 (GrapheneOS)
 - Device: Pixel 3a XL

**Server**
 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**
Not sure how useful this is:

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.9.237-ga7832a5c4268(2021.04.05.20)
OS API Level: 30
Device: bonito
Manufacturer: Google
Model (and Product): Pixel 3a XL (aosp_bonito)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by unilock** [comment]
I'm experiencing ths same issue.

**Smartphone:**
- Nextcloud Notes-Version (android app): 3.3.0
- F-Droid or Play Store: F-Droid
- Android version: 11 (Stock)
- Device: Pixel 4a (non-5G)

**Server:**
- Nextcloud version: 21.0.1 (also occurred on 20.0.8)
- Nextcloud Notes version (server app): 4.0.4

**Stacktrace**
```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.199-g0f6cf0610a1f-ab7132618(7181113)
OS API Level: 30
Device: sunfish
Manufacturer: Google
Model (and Product): Pixel 4a (sunfish)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by notarobot63** [comment]
Hello

Same here with Android 11 one Oneplus 7t
````
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.190-perf+(2103161153)
OS API Level: 30
Device: OnePlus7T
Manufacturer: OnePlus
Model (and Product): HD1903 (OnePlus7T_EEA)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
	at it.niedermann.owncloud.notes.persistence.n.e(Unknown Source:24)
	at it.niedermann.owncloud.notes.persistence.k$c.g(Unknown Source:64)
	at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:24)
	at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

````

**Comment by stefan-niedermann** [comment]
Is alreasy fixed and released in `3.3.1`.

I can't do anything more than wait for F-Droid unfortunstely. Use an older version as workaroundy sorry.

**Comment by notarobot63** [comment]
Perfect thanks for the quick fix !

**Comment by mkriegl** [comment]
Thanks I also have the issue and wait for f-droid to update. Yesterday I managed to make it run one time again, but today I am stuck again
