### ISSUE TITLE
Sync Fails after updating to 3.3.0

### ISSUE THREAD

**Issue by felix-berlin** [stefan-niedermann/nextcloud-notes#1129]
**Describe the bug**
The sync fails after updating the app and selecting the one of my accounts.

**To Reproduce**
1. Update to the newest Version
2. Start the app
3. Those Account (i have two)
4. Sync fails

**Expected behavior**
Normal sync.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.0
 - F-Droid or Play Store: f-droid
 - Android-Version: 11
 - Device: Pixel 4a

**Server**
 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.199-g1823ff3e1553-ab7079318(7119741)
OS API Level: 30
Device: sunfish
Manufacturer: Google
Model (and Product): Pixel 4a (sunfish)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment]
https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
