### ISSUE TITLE
Synchronization crashes

### ISSUE THREAD

**Issue by CrAme007** [stefan-niedermann/nextcloud-notes#1130]
**To Reproduce**
1. Upgrade to version 3.3.0
2. Synchronize

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - App Version: 3.3.0
 - App Version Code: 3003000
 - App Flavor: fdroid
 - Files App Version Code: 30150190
---
 - OS Version: 3.10.84-perf-g83e017e(2275028769)
 - OS API Level: 25
 - Device: F5321
 - Manufacturer: Sony
 - Model (and Product): F5321 (F5321)

**Server**
 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app):  4.0.4
 - Nextcloud server: Linux 4.19.0-13-amd64 x86_64, Intel(R) Pentium(R) CPU G4560 @ 3.50GHz (4 cores)

**Stacktrace**
b.b.a.a.e.n: b.b.a.a.c.c
 at b.b.a.a.d.c.i()
 at b.b.a.a.d.e.c()
 at it.niedermann.owncloud.notes.persistence.p.e()
 at it.niedermann.owncloud.notes.persistence.i.a()
 at it.niedermann.owncloud.notes.main.MainActivity.C0()
 at it.niedermann.owncloud.notes.main.MainActivity.D0()
 at it.niedermann.owncloud.notes.main.l.run()
 at java.lang.Thread.run(Thread.java:761)

**Comment by CrAme007** [comment]
Downgrade to 3.2.5 is working

**Comment by stefan-niedermann** [comment]
https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
