### ISSUE TITLE
Bug: error can't sync after upgrade to 3.3.0

### ISSUE THREAD

**Issue by wijourdil** [stefan-niedermann/nextcloud-notes#1131]
Since I have upgraded the app to the latest version, I have the following issue when I start the app, and my notes are no longer synced
```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.9.227-gfd7b2c5(13e6898eb2)
OS API Level: 29
Device: OnePlus6
Manufacturer: OnePlus
Model (and Product): ONEPLUS A6003 (OnePlus6)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
	at it.niedermann.owncloud.notes.persistence.n.h(Unknown Source:73)
	at it.niedermann.owncloud.notes.persistence.n.c(Unknown Source:23)
	at it.niedermann.owncloud.notes.persistence.k$c.h(Unknown Source:214)
	at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:14)
	at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)


b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
	at it.niedermann.owncloud.notes.persistence.n.e(Unknown Source:24)
	at it.niedermann.owncloud.notes.persistence.k$c.g(Unknown Source:64)
	at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:24)
	at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by wijourdil** [comment]
Oops I did not see the issue was already reported, sorry !
