### ISSUE TITLE
Notes is not synchronizing anymore with NC server after last update

### ISSUE THREAD

**Issue by wael-t** [stefan-niedermann/nextcloud-notes#1135]
Since the last update, Notes is unable to sync with my NC server. I  am getting this report: 
```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.199-00008-g4772302565(2021.04.07.18)
OS API Level: 30
Device: sunfish
Manufacturer: Google
Model (and Product): Pixel 4a (calyx_sunfish)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment]
https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
