### ISSUE TITLE
Synchronization failed: b.b.a.a.c.c after update to 3.3.0

### ISSUE THREAD

**Issue by calvinrw** [stefan-niedermann/nextcloud-notes#1137]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

After updating to app version 3.3.0 via F-Droid, synchronization with the server fails with the error message "Synchronization failed: b.b.a.a.c.c".

**To Reproduce**
Steps to reproduce the behavior (after clearing Notes' cache and storage):
1. Open the app
2. Select the Nextcloud account to use with Notes
3. Allow Notes to use the Nextcloud account
2. See error

**Expected behavior**

When opening the app while connected to the Internet, initial note synchronization succeeds and my notes are available to view and edit.

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.0
 - F-Droid or Play Store: F-Droid 1.11
 - Android-Version: 10 (LineageOS 17.1 official build)
 - Device: Moto Z3 Play (beckham)

**Server**
 - Nextcloud version: 20.0.8
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.4.249-lineageos-gfb8eba734eb8(4f7841c381)
OS API Level: 29
Device: beckham
Manufacturer: Motorola
Model (and Product): Moto Z3 Play (beckham)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by calvinrw** [comment]
Never mind, I see now this has been thoroughly reported, and that F-Droid is holding up distribution of the fix.
