### ISSUE TITLE
Synchronization failed App Version: 3.3.0

### ISSUE THREAD

**Issue by cidetraq** [stefan-niedermann/nextcloud-notes#1140]
**Describe the bug**
Synchronization with my nextcloud account has recently started to fail after a new app update. I can still edit, create, delete just fine on the web browser portal to my nextcloud, just the Nextcloud Notes app fails. I don't know enough about the app to explain why it's not working. 

**To Reproduce**
Attempt to sync notes.

**Expected behavior**
Notes should sync.

**Screenshots**
None, see the bug log generated by Nextcloud Notes

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.0
 - F-Droid or Play Store: F-droid
 - Android-Version: 2021.04.07.18
 - Device: Taimen (Google pixel 2 XL)

**Server**
 - Nextcloud version: UNAVAILABLE (I am on a free plan for this nexctloud setup, which does not show the admin settings which has the nextcloud version)
 - Nextcloud Notes version (server app): Also Unavailable
 - (It is Cloudamo Free plan)

**Stacktrace**
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190OS Version: 4.4.223-gd5675d2b78-00003-gd245ac834e(2021.04.07.18)
OS API Level: 30
Device: taimen
Manufacturer: Google
Model (and Product): Pixel 2 XL (calyx_taimen)b.b.a.a.e.n: b.b.a.a.c.c
at b.b.a.a.d.c.i(Unknown Source:33)
at b.b.a.a.d.e.c(Unknown Source:6)
at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
at it.niedermann.owncloud.notes.persistence.n.h(Unknown Source:73)
at it.niedermann.owncloud.notes.persistence.n.c(Unknown Source:23)
at it.niedermann.owncloud.notes.persistence.k$c.h(Unknown Source:214)
at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:14)
at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)

b.b.a.a.e.n: b.b.a.a.c.c
at b.b.a.a.d.c.i(Unknown Source:33)
at b.b.a.a.d.e.c(Unknown Source:6)
at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
at it.niedermann.owncloud.notes.persistence.n.e(Unknown Source:24)
at it.niedermann.owncloud.notes.persistence.k$c.g(Unknown Source:64)
at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:24)
at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)

**Comment by stefan-niedermann** [comment]
See https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
