### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by brimwats** [stefan-niedermann/nextcloud-notes#1143]
**Describe the bug**

cannot access notes

**To Reproduce**
1. Go to app
2. Click on anything

**Expected behavior**

ability to open my notes

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.3.0
 - F-Droid or Play Store: fdroid
 - Android-Version: latest
 - Device: galaxy s10

**Server**

(can't get to this on mobile rn, will update later) 
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.14.190-21058543-abG973USQU5GUBH(G973USQU5GUBH)
OS API Level: 30
Device: beyond1q
Manufacturer: samsung
Model (and Product): SM-G973U (beyond1qltesq)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment]
See https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
