### ISSUE TITLE
Sync Error on Startup

### ISSUE THREAD

**Issue by Ged296123** [stefan-niedermann/nextcloud-notes#1144]
Sync problem on startup.
Error log as below appearing when starting app.

Tried uninstall and reinstall with no success.

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.9.218(eng.root.20210125.180650)
OS API Level: 29
Device: crownlte
Manufacturer: samsung
Model (and Product): SM-N960F (crownltexx)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

```

**Comment by stefan-niedermann** [comment]
See https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
