### ISSUE TITLE
Sync fails repeatedly

### ISSUE THREAD

**Issue by matthias1707** [stefan-niedermann/nextcloud-notes#1145]
... even after update today.

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.4.147+(vMA170107)
OS API Level: 28
Device: A140
Manufacturer: ACEPAD
Model (and Product): A140 (A140)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
	at it.niedermann.owncloud.notes.persistence.n.h(Unknown Source:73)
	at it.niedermann.owncloud.notes.persistence.n.c(Unknown Source:23)
	at it.niedermann.owncloud.notes.persistence.k$c.h(Unknown Source:214)
	at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:14)
	at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
	at it.niedermann.owncloud.notes.persistence.n.h(Unknown Source:73)
	at it.niedermann.owncloud.notes.persistence.n.a(Unknown Source:4)
	at it.niedermann.owncloud.notes.persistence.k$c.h(Unknown Source:262)
	at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:14)
	at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)


b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.l.g(Unknown Source:165)
	at it.niedermann.owncloud.notes.persistence.n.e(Unknown Source:24)
	at it.niedermann.owncloud.notes.persistence.k$c.g(Unknown Source:64)
	at it.niedermann.owncloud.notes.persistence.k$c.c(Unknown Source:24)
	at it.niedermann.owncloud.notes.persistence.k$c.doInBackground(Unknown Source:2)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by stefan-niedermann** [comment]
https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
