### ISSUE TITLE
Problema al añadir usuario

### ISSUE THREAD

**Issue by Gabiginer** [stefan-niedermann/nextcloud-notes#1146]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To Reproduce**
1. Simply add an user login

**Expected behavior**
User aded and sincrhonized.

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: F-Droid
 - Android-Version: 8
 - Device: Galaxy S7

**Server**
 - Nextcloud version: 22.0.0
 - Nextcloud Notes version (server app): 3.3.0

**Stacktrace**
```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 3.18.91-19497840-QB34227861(G930FXXU8ETI2)
OS API Level: 26
Device: herolte
Manufacturer: samsung
Model (and Product): SM-G930F (heroltexx)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by stefan-niedermann** [comment]
https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516

Please write in english in the future, i don't speak every language on the planet :wink:
