### ISSUE TITLE
Cant connect to nextcloud on oneplus 8 pro

### ISSUE THREAD

**Issue by golfben** [stefan-niedermann/nextcloud-notes#1147]
**Android version:** 11

**Device**: oneplus 8 pro

**System language**: German

**App version:** 3.3.0

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. select nextcloud account (which was already set up in nextcloud App)
  3. allow App to connect with account 
 4. App crashes

Crashlog:

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.19.110-perf+(2103221755)
OS API Level: 30
Device: OnePlus8Pro
Manufacturer: OnePlus
Model (and Product): IN2023 (OnePlus8Pro_EEA)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment]
See https://github.com/stefan-niedermann/nextcloud-notes/issues/1128#issuecomment-817526516
