### ISSUE TITLE
Issue on OnePlusNord

### ISSUE THREAD

**Issue by mariomare22** [stefan-niedermann/nextcloud-notes#1155]
**Describe the bug**
cannot login into the app on android

**To Reproduce**
1. open the app
2. add my account

```
b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

```

**Expected behavior**
clean login

```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.19.113-perf+(2103130237)
OS API Level: 30
Device: Nord
Manufacturer: OnePlus
Model (and Product): AC2003 (Nord_EEA)

---
```

**Server**
 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app): 404

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Update to 3.3.1

**Comment by mariomare22** [comment]
Thank you
Fdroid did not update the repo.
