### ISSUE TITLE
Exception when trying to synchronize

### ISSUE THREAD

**Issue by mphilipp** [stefan-niedermann/nextcloud-notes#1157]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Synchronization fails with exception

**To Reproduce**
1. Pull down to synchronize
2. See exception message below

**Expected behavior**

Notes should be synchronized

**Screenshots**

**Smartphone (please complete the following information):**
```
App Version: 3.3.0
App Version Code: 3003000
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 4.4.223-g52750b8f2138-ab6846512(6934943)
OS API Level: 30
Device: walleye
Manufacturer: Google
Model (and Product): Pixel 2 (walleye)

---

b.b.a.a.e.n: b.b.a.a.c.c
	at b.b.a.a.d.c.i(Unknown Source:33)
	at b.b.a.a.d.e.c(Unknown Source:6)
	at it.niedermann.owncloud.notes.persistence.p.e(Unknown Source:8)
	at it.niedermann.owncloud.notes.persistence.i.a(Unknown Source:124)
	at it.niedermann.owncloud.notes.main.MainActivity.C0(Unknown Source:71)
	at it.niedermann.owncloud.notes.main.MainActivity.D0(Unknown Source:0)
	at it.niedermann.owncloud.notes.main.l.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)

```
**Server**
 - Nextcloud version: 20.0.4
 - Nextcloud Notes version (server app): Unknown

**Stacktrace**
See above

**Comment by stefan-niedermann** [comment]
Update to 3.3.1

**Comment by mphilipp** [comment]
The new version works. Thank you very much!
