### ISSUE TITLE
No account in nextcloud app found

### ISSUE THREAD

**Issue by JR0815** [stefan-niedermann/nextcloud-notes#1206]
```
App Version: 3.4.1
App Version Code: 3004001
App Flavor: fdroid

Files App Version Code: 30160090

---

OS Version: 3.10.84-perf-g51b663cc723-04742-g5bcfaca9e61(1631208121)
OS API Level: 26
Device: F5321
Manufacturer: Sony
Model (and Product): F5321 (F5321)

---

com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.AccountImporter.getSingleSignOnAccount(AccountImporter.java:192)
	at com.nextcloud.android.sso.helper.SingleAccountHelper.getCurrentSingleSignOnAccount(SingleAccountHelper.java:53)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$2$MainActivity(MainActivity.java:167)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$ZhWE-Elp2gTqL_Z3Kyw5s_28StU.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)

```

**Expected behavior**
Works without problem in version 3.4.0

**Comment by stefan-niedermann** [comment]
Have you tried to remove and readd your account from the Notes Android app?

**Comment by stefan-niedermann** [comment]
Feel free to open a new issue [filling the complete issue template](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed) if the error persists after performing [the steps mentioned in the FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error).
