### ISSUE TITLE
UnknownErrorException: Read timed out 	

### ISSUE THREAD

**Issue by WST1811** [stefan-niedermann/nextcloud-notes#1207]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Every start the app i get the error. After this each sync is running without an error.

**To Reproduce**
1. Start the App 
2. See error Log:

```
App Version: 3.4.1
App Version Code: 3004001
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 3.4.113-lineageos-g4a34f0e(b463797747)
OS API Level: 30
Device: klte
Manufacturer: samsung
Model (and Product): SM-G900F (klte)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: Read timed out
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:178)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.getNotes(NotesClientV1.java:32)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:176)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Expected behavior**

I only start the app, each sync after this error is running.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.15.1
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Samsung S5 klte

**Server**
 - Nextcloud version: 21.0.1
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Please try to move your notes to another folder ony your Nextcloud instance and put them back step by step. After putting back a few notes, synchronize.

Technical background: The Notes Android app currently tries to synchronize all notes at once, what will cause a read timeout on slow connections or many big notes.

This issue affects only the very first sync - after all notes have successfully been synchronized to the Android app, all following syncs will only synchronize actual changed notes.

**Comment by WST1811** [comment]
Thanks @stefan-niedermann that works. :)

**Comment by WST1811** [comment]
After 3 times Sync without a problem, a new one is coming each start of the app:

```
App Version: 3.4.1
App Version Code: 3004001
App Flavor: fdroid

Files App Version Code: 30150190

---

OS Version: 3.4.113-lineageos-g4a34f0e(c20a8a3919)
OS API Level: 30
Device: klte
Manufacturer: samsung
Model (and Product): SM-G900F (klte)

---

com.nextcloud.android.sso.exceptions.UnknownErrorException: Connection reset
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:178)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.getNotes(NotesClientV1.java:32)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:176)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:74)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment]
This seems to be unrelated to the above mentioned architectural flaw of the Android app and caused by an unreliable network connection / by the server. Sorry, but i can't help you with that one as i have no idea what can cause a connection reset on the clients side 🤷‍♂️

**Comment by WST1811** [comment]
Now i hab uninstall both apps, notes and nextcloud, install nextcloud first again, configure my Server and account, after this install notes again. After a couple of Appstarts and 1 restart of the phone, it works without any errors. crossing fingers. Thanks for help again. ;)

**Comment by stefan-niedermann** [comment]
Thanks for the update and 🤞 🙂
