### ISSUE TITLE
Crash while login on start after update

### ISSUE THREAD

**Issue by mcpride** [stefan-niedermann/nextcloud-notes#1241]
The new version is unable to login into my nextcloud account

```
App Version: 3.4.4
App Version Code: 3004004
App Flavor: fdroid

Files App Version Code: 30160090

---

OS Version: 4.14.116(10.1.0.163C00)
OS API Level: 29
Device: HWLYA
Manufacturer: HUAWEI
Model (and Product): LYA-AL10 (LYA-AL10)

---

com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Konto in der Nextcloud App nicht gefunden
	at com.nextcloud.android.sso.AccountImporter.getSingleSignOnAccount(AccountImporter.java:192)
	at com.nextcloud.android.sso.helper.SingleAccountHelper.getCurrentSingleSignOnAccount(SingleAccountHelper.java:53)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$2$MainActivity(MainActivity.java:168)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$ZhWE-Elp2gTqL_Z3Kyw5s_28StU.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:929)

```

**Comment by stefan-niedermann** [comment]
Try to clear the storage of both, the Notes Android and the Nextcloud Android app as [described here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error). If this doesn't help, feel free to open a new issue [filling the complete issue template](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed).
