### ISSUE TITLE
Reopen Crash on rotate

### ISSUE THREAD

**Issue by IngoBelka** [stefan-niedermann/nextcloud-notes#1258]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To Reproduce**
1. open a note
2. rotate the tablet from portrait to landscape
3. crash

**Expected behavior**

should not crash

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.8
 - F-Droid or Play Store: F-Droid
 - Android-Version: 9
 - Device: Huawei MediaPad 5

**Server**
 - Nextcloud version: 20
 - Nextcloud Notes version (server app): 4.0.4

**Stacktrace**
Hello,
on my Huawei MediaPad 5 with Android 9 the rotation bug is still present.

```
App Version: 3.4.8
App Version Code: 3004008
App Flavor: fdroid

Files App Version Code: 30160190

---

OS Version: 4.9.148(9.1.0.335C432)
OS API Level: 28
Device: HWSHT
Manufacturer: HUAWEI
Model (and Product): SHT-W09 (SHT-W09)

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{it.niedermann.owncloud.notes/it.niedermann.owncloud.notes.edit.EditNoteActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeAllViews()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3430)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3614)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5527)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5418)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.ViewGroup.removeAllViews()' on a null object reference
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:689)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:201)
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.onCreate(EditNoteActivity.java:77)
	at android.app.Activity.performCreate(Activity.java:7458)
	at android.app.Activity.performCreate(Activity.java:7448)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
	... 13 more

```

**Comment by IngoBelka** [comment]
waitimh for version 3.4.9
