### ISSUE TITLE
Crash  when there a long press and swipe over a note 

### ISSUE THREAD

**Issue by debnone** [stefan-niedermann/nextcloud-notes#1308]
### bug Describing

the app crash when there are a Long press and swipe to the  outside of the  note border.
it happens in the Grid view and also in the default view.

### To Reproduce

1. Long press over any note.
2. Swipe to the outside border of the note.
3. Boom CRASH 💥

---

### More Info

```
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30160190

---

OS Version: 4.14.213-LineageOS-gd263581e554a-ab545c332bc8(545c332bc8)
OS API Level: 29
Device: davinci
Manufacturer: Xiaomi
Model (and Product): Mi 9T (davinci)

---

java.lang.ArrayIndexOutOfBoundsException: length=72; index=-1
 at java.util.ArrayList.get(ArrayList.java:439)
 at it.niedermann.owncloud.notes.main.items.ItemAdapter.getItem(ItemAdapter.java:170)
 at it.niedermann.owncloud.notes.main.items.selection.ItemSelectionTracker$1.canSetStateAtPosition(ItemSelectionTracker.java:34)
 at androidx.recyclerview.selection.GestureSelectionHelper.handleMoveEvent(GestureSelectionHelper.java:192)
 at androidx.recyclerview.selection.GestureSelectionHelper.onTouchEvent(GestureSelectionHelper.java:141)
 at androidx.recyclerview.selection.EventRouter.onTouchEvent(EventRouter.java:68)
 at androidx.recyclerview.widget.RecyclerView.dispatchToOnItemTouchListeners(RecyclerView.java:3259)
 at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3421)
 at android.view.View.dispatchTouchEvent(View.java:13953)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
 at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
 at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1849)
 at android.app.Activity.dispatchTouchEvent(Activity.java:4011)
 at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
 at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
 at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
 at android.view.View.dispatchPointerEvent(View.java:14212)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5649)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5452)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4955)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5008)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4974)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5114)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4982)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5171)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4955)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5008)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4974)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4982)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4955)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7672)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7641)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7602)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7797)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
 at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
 at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
 at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7748)
 at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7821)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
 at android.view.Choreographer.doCallbacks(Choreographer.java:791)
 at android.view.Choreographer.doFrame(Choreographer.java:719)
 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:214)
 at android.app.ActivityThread.main(ActivityThread.java:7356)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```

**Comment by stefan-niedermann** [comment]
Thank you for the bug report. This issue will be fixed in `3.4.13` :slightly_smiling_face:
