### ISSUE TITLE
Syncing notes doesn't work, exception

### ISSUE THREAD

**Issue by unalignedcoder** [stefan-niedermann/nextcloud-notes#1321]
Notes won't sync. Those created on the smartphone are not uploaded and I cannot create new ones on the web interface. 

**To Reproduce**
1. On the web interface, click on new note
2. see error: "creating new note has failed. Http 500 (ocp\files\not permitted exception)" 
3. Try to sync on the phone notes created there
4. See error "synchronization failed". Clicking on "more" gives this error:

```
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30170051

---

OS Version: 4.9.190+(root.20200605.114948)
OS API Level: 29
Device: Armor_9
Manufacturer: Ulefone
Model (and Product): Armor 9 (Armor_9_EEA)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 401
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
	at it.niedermann.owncloud.notes.main.MainViewModel.lambda$synchronizeCapabilities$13$MainViewModel(MainViewModel.java:406)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainViewModel$Kr1O01KODRuj8fCWyoVh0ZkuW9I.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: <?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>997</statuscode>
  <message>Unauthorised</message>
 </meta>
 <data/>
</ocs>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```

**Server**
 - Nextcloud version: 22.1.0
 - Nextcloud Notes version (server app): 4.11

**Comment by stefan-niedermann** [comment]
If the Notes server app does not work, the Android client is of course also not able to create notes. The exception message of the Android app is a symptom rather than the cause of your problem.

Please first solve your issues with the Notes server app therefore and *then* check out the Android client. You can ask for help with the Notes server app here: https://github.com/nextcloud/notes/issues/new/choose

The error messages hint on a permission issue, the Notes server app is not allowed to write files into your `/Notes` folder, you should check the file system permissions of this folder.

Good luck!

**Comment by unalignedcoder** [comment]
I manually created the "Notes" folder, there was none! Now I can create notes without any problems on the web, but the app still won't sync.
