### ISSUE TITLE
Crash when using link in checkbox list

### ISSUE THREAD

**Issue by pbek** [stefan-niedermann/nextcloud-notes#1326]
First, thank you very much @stefan-niedermann, for this awesome app! 😁  It's a great companion to https://github.com/pbek/QOwnNotes/. 😀 

**Describe the bug**

I get a crash when using a link in a checkbox list.

Example note:

```markdown
Test Crash
==========

- [ ] Just text with link <https://github.com>
```

**To Reproduce**

1. Create a note file externally (example above)
2. Open the note on mobile app
3. App crashes

**Expected behavior**

- App doesn't crash :)

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.11
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Samsung A52

**Server**
 - Nextcloud version: 22.1.0
 - Nextcloud Notes version (server app): 4.1.1

**Stacktrace**

```
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 4.14.190-perf-21945581-abA525FXXU3AUG4(A525FXXU3AUG4)
OS API Level: 30
Device: a52q
Manufacturer: samsung
Model (and Product): SM-A525F (a52qnseea)

---

java.lang.IllegalArgumentException: lower must be less than or equal to upper
	at android.util.Range.<init>(Range.java:59)
	at it.niedermann.android.markdown.markwon.plugins.ToggleableTaskListPlugin.findFreeRanges(ToggleableTaskListPlugin.java:159)
	at it.niedermann.android.markdown.markwon.plugins.ToggleableTaskListPlugin.afterRender(ToggleableTaskListPlugin.java:123)
	at io.noties.markwon.MarkwonImpl.render(MarkwonImpl.java:80)
	at io.noties.markwon.MarkwonImpl.toMarkdown(MarkwonImpl.java:97)
	at io.noties.markwon.MarkwonImpl.setMarkdown(MarkwonImpl.java:113)
	at it.niedermann.android.markdown.markwon.MarkwonMarkdownViewer.lambda$null$1$MarkwonMarkdownViewer(MarkwonMarkdownViewer.java:148)
	at it.niedermann.android.markdown.markwon.-$$Lambda$MarkwonMarkdownViewer$hUNo5njTVF09ptnIgeBU4cmkPBQ.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8587)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by pbek** [comment]
Any chance getting this into a release, @stefan-niedermann? I still need to open my notes again on my phone. 😅

**Comment by pbek** [comment]
@stefan-niedermann, Fdroid shows me Version 3.4.11 as most current version (from 3 month ago) but with my fix in the changelog. But I still get the exact same crash. Was there a release (with the same version number as the last) or is this a different issue?
