### ISSUE TITLE
Note won't synch back to the NC server

### ISSUE THREAD

**Issue by sciurius** [stefan-niedermann/nextcloud-notes#1344]
**Describe the bug**

A note created on Android won't synch back to the NC server.

**To Reproduce**
1. Create a note
2. Go to the note list. It shows the sync-symbol next to the favourites symbol
3. Click on the sync symbol

````
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 5.4.86-qgki-22338221-abT733XXU1AUI1(T733XXU1AUI1)
OS API Level: 30
Device: gts7fewifi
Manufacturer: samsung
Model (and Product): SM-T733 (gts7fewifieea)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Provided authentication token does not match or package name is not permitted to perform this action
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
````

Software was migrated from another tablet using Samsung Switch.

**Expected behavior**

Synch.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.11
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: Samsung Galaxy Tab S7 FE

**Server**
 - Nextcloud version: 21.0.3
 - Nextcloud Notes version (server app): 4.1.1

**Stacktrace**
See above.

**Comment by stefan-niedermann** [comment]
Please proceed as [described in the FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#tokenmismatchexception-and-all-others). The app won't survive a transfer via Samsung Switch as the authentication token does bo longer match. Maybe removing and readding the account from the Notes Android app is already enough.
