### ISSUE TITLE
Synchronize Failed 

### ISSUE THREAD

**Issue by HvdK-zOS** [stefan-niedermann/nextcloud-notes#1345]
**Synchronize Failed after Note updates**

**Describe the bug**
After update a new Note the android app are not able to synchronize the not on the NC server.
Android Smartphone restarted
NC Server restarted
NC Note removed and installed again via F-Droid.

NC Note via WEB-Browser available and no synchronize errors

**To Reproduce**
Change a point in one Note on smartphone

**Expected behavior**
Synchronize the update on the NC server too

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app):  3.4.11
 - F-Droid or Play Store:  fdroid
 - Android-Version: 10
 - Device: Gigaset GS4

**Server**
 - Nextcloud version: 22.1.1.snap1
 - Nextcloud Notes version (server app): 4.1.1

**Stacktrace**

```
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 4.14.141(1628061231)
OS API Level: 29
Device: Gigaset_GS4
Manufacturer: Gigaset
Model (and Product): E940-2795-00 (Gigaset_GS4_EEA)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Die API der Nextcloud-Dateien-App reagiert nicht. Bitte melden Sie diesen Fehler.
at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Die API der Nextcloud-Dateien-App reagiert nicht. Bitte melden Sie diesen Fehler.
at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
at io.reactivex.Observable.blockingSingle(Observable.java:5381)
at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Die API der Nextcloud-Dateien-App reagiert nicht. Bitte melden Sie diesen Fehler.
at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
at com.nextcloud.android.sso.api.-$$Lambda$NextcloudAPI$8WS9mapJbOYsPgbhBi25vBNYZqI.subscribe(Unknown Source:6)
at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
... 8 more

```

--

**Comment by stefan-niedermann** [comment]
Please proceed as [described in our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#nextcloudapinotrespondingexception).
