### ISSUE TITLE
Can no longer sync after latest update on samsung TabS2

### ISSUE THREAD

**Issue by rainer042** [stefan-niedermann/nextcloud-notes#1353]
**Describe the bug**
When I try to sync on my Samsung Tab S2notes with my nextcloud since recently I only see the error shown by the app, see below. On my mobile Samsung S8, using the same app in its latest  available version frompay store and the same nextcloud server it just works fine. 

```
App Version: 3.2.5
App Version Code: 3002005
App Flavor: play

Files App Version Code: 30170090

---

OS Version: 3.10.84-14953299(T819XXS2BTI1)
OS API Level: 24
Device: gts210velte
Manufacturer: samsung
Model (and Product): SM-T819 (gts210veltexx)

---

com.nextcloud.android.sso.exceptions.TokenMismatchException: Der Authentifizierungs-Token stimmt nicht überein oder dem Paketnamen fehlt die Berechtigung für diese Aktion
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.getNotes(NotesClientV1.java:31)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:762)

```

**To Reproduce**
Start the app and try to sync

**Expected behavior**
Start of the sync action

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.2.5
 - F-Droid or Play Store: playstore
 - Android-Version: 7.0
 - Device: Model (and Product): SM-T819 (gts210veltexx)

**Server**
 - Nextcloud version: 20.2.12 stabke
 - Nextcloud Notes version (server app): current

**Comment by stefan-niedermann** [comment]
Have you already tried to remove and reimport your account in the Notes Android app (of course after backing up unsynchronized changes elsewhere)?

**Comment by rainer042** [comment]
Hello Stefan,
thank you very much for writing. The trick you described worked. After 
removing and reading my account everything is working again.

Have a nice say
Rainer


Am 26. September 2021 15:01:19 schrieb Niedermann IT-Dienstleistungen 
***@***.***>:

**Comment by stefan-niedermann** [comment]
Thanks for the feedback! Stay well, Stefan.
