### ISSUE TITLE
Sync error

### ISSUE THREAD

**Issue by vikhou** [stefan-niedermann/nextcloud-notes#1355]
```
App Version: 3.4.11
App Version Code: 3004011
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 4.14.116(10.1.0.298AUSC636)
OS API Level: 29
Device: HWHMA
Manufacturer: HUAWEI
Model (and Product): HMA-L29 (HMA-L29)

---

java.lang.Exception: {"errorType":"OCP\\Files\\NotPermittedException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)

```

Thank you.

**Comment by stefan-niedermann** [comment]
Server says, you are not permitted to write something. I can't see anything that a client should do if it is not allowed to 🤷‍♂️ 

I recommend you to open an issue [in the Notes server app repository](https://github.com/nextcloud/notes/issues/new/choose) and filling out the complete issue template instead of ignoring it. It is there [for a reason](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed).

**Comment by vikhou** [comment]
Thank you, Stefan.
