### ISSUE TITLE
Notes - synchro failure

### ISSUE THREAD

**Issue by saperlottegit** [stefan-niedermann/nextcloud-notes#1376]
Hi,

Could you help me with this synch error message?
Thx

Regards
---------

```
App Version: 3.4.13
App Version Code: 3004013
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 3.18.131-lineageos-g22175f5b2cee(14980dfdcc)
OS API Level: 27
Device: santoni
Manufacturer: Xiaomi
Model (and Product): Redmi 4X (lineage_santoni)

---

java.lang.Exception: 
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)


java.lang.Exception: 
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)


java.lang.Exception: 
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)


java.lang.Exception: 
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: La requête HTTP a échoué avec le statut HTTP :302
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: La requête HTTP a échoué avec le statut HTTP :302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransact(Binder.java:697)

```

**Comment by stefan-niedermann** [comment]
Then please be more verbose about your environment.

- Is your cloud located in a subdirectory or directly in the root folder of your domain?
 - Did you recently change *anything* on your server configuration?
 - Do you have configured any redirects on your server (for example via `.htaccess` in case if an Apache)? 
 - Does the Nextcloud (not Notes) app work without any issues on your device?

**Comment by saperlottegit** [comment]
Hi,
Sorry for my late response.
My comments below (in blue).
Regards

Fyi, last error report below
```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30180090

---

OS Version: 3.18.131-lineageos-g22175f5b2cee(f7a13383dc)
OS API Level: 27
Device: santoni
Manufacturer: Xiaomi
Model (and Product): Redmi 4X (lineage_santoni)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: La requête HTTP a échoué avec le statut HTTP :302
at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
at io.reactivex.Observable.blockingSingle(Observable.java:5381)
at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: La requête HTTP a échoué avec le statut HTTP :302
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:110)
at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
... 8 more
Caused by: java.lang.IllegalStateException:
at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
at android.os.Binder.execTransact(Binder.java:697)

```

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by stefan-niedermann** [comment]
See my [questions above](https://github.com/stefan-niedermann/nextcloud-notes/issues/1376#issuecomment-944139212), just repeating the error message does not add any additional information.

**Comment by stefan-niedermann** [comment]
Ah, i just noticed the responses were hidden, sorry.

Which Notes server app version do you have installed?

**Comment by saperlottegit** [comment]
No problem.
I have just downloaded the app on my phone : Version 3.4.16
Rgds

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by stefan-niedermann** [comment]
The Notes **server** app version. It's linked in the description of the Notes Android app as a requirement 😉

**Comment by saperlottegit** [comment]
Hi,
As you can see, i am not experienced at all. I have just installed eelo on my personal cell phone, the Nextcloud app and the Nextcloud note app.
I have not installed the Notes server app, I do not use it.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by stefan-niedermann** [comment]
In this case you won't be able to use the Notes Android app, as the Notes server app is required for it.

**Comment by saperlottegit** [comment]
Thank you for this answer.
I have been using notes for more than a year and at the beginning I didn't need the server app for notes to work.
Something has changed?
Rgds

-------- Message d'origine --------

**Comment by stefan-niedermann** [comment]
No, nothing changed. It is impossible to use the Notes Android app without the Notes server app (and it has been impossible since the very first version released years ago).
You maybe used another app or had a weird not-synchronized setup, but it definitely has never been possible to use the Notes Android app without the server counterpart.
