### ISSUE TITLE
First configuration

### ISSUE THREAD

**Issue by sercasbh** [stefan-niedermann/nextcloud-notes#1392]
When I try to configure the first time, after choosing nextcloud file profile I give this error.:

```
App Version: 3.4.13
App Version Code: 3004013
App Flavor: fdroid

Files App Version Code: 30180051

---

OS Version: 4.9.188-perf+(eng.root.20211027.084848)
OS API Level: 29
Device: tissot
Manufacturer: Xiaomi
Model (and Product): Mi A1 (lineage_tissot)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: L'applicazione File di Nextcloud non risponde. Segnala questo problema.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
	at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity.lambda$onActivityResult$5$ImportAccountActivity(ImportAccountActivity.java:97)
	at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity$$ExternalSyntheticLambda6.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

 - Nextcloud version: 22.2.0
 - Nextcloud Notes version (server app): 4.1.1

**Comment by stefan-niedermann** [comment]
Please see "Current state of this issue" in https://github.com/nextcloud/android/issues/9156
