### ISSUE TITLE
The notes that have been created when sharing a tweet are not synchronized.

### ISSUE THREAD

**Issue by isaacmuro** [stefan-niedermann/nextcloud-notes#1396]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

On twitter, when you share a tweet and create a note, the note is created in the app, but it is not synced with the nextcloud server.
By marking the note shared by twitter in the app as a favorite, it is then synchronized with the nextcloud server.
If you create a new note in the app, it does sync with the nextcloud server. 
I have given the example of a note created with twitter, but it happens to me with any other app that I share to the Notes app. 

**To Reproduce**
1. Go to Twitter App. 
2. Click on Share Button in one tweet.
3. Share the tweet creating a new note. 
4. The note is created in the Notes app, but it does not sync with the nextcloud server. 
5. Marking the note as Favourite, the note is sync with the nextcloud server. 

**Expected behavior**

When the note is shared, it will sync directly to the nextcloud server. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.13
 - F-Droid or Play Store: F-Droid
 - Android-Version: 10-05
 - Device: Alcatel 5002H_EEA (in other device I notice the same behaviour)

**Server**
 - Nextcloud version: 21.0.5
 - Nextcloud Notes version (server app): 4.1.1

**Stacktrace**
(It gave me some different errors. Sometimes, it give no error)
App Version: 3.4.13
App Version Code: 3004013
App Flavor: fdroid

Files App Version Code: 30170090

---

OS Version: 4.9.226-perf(v3CEF-0)
OS API Level: 29
Device: Seoul
Manufacturer: TCL
Model (and Product): 5002H_EEA (5002H_EEA)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

In the server side, I didn't see errors. The access log shows this: 

Creating new note in the app: 
[08/Nov/2021:19:31:22 +0000] "POST /nextcloud/index.php/apps/notes/api/v1/notes? HTTP/1.1" 200 2225 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.17.0"
[08/Nov/2021:19:31:23 +0000] "GET /nextcloud/index.php/apps/notes/api/v1/notes?pruneBefore=1636389990 HTTP/1.1" 200 2764 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.17.0"

Refresh notes: 
[08/Nov/2021:19:32:53 +0000] "GET /nextcloud/ocs/v2.php/cloud/capabilities?format=json HTTP/1.1" 304 558 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.17.0"
[08/Nov/2021:19:32:54 +0000] "GET /nextcloud/index.php/apps/notes/api/v1/notes?pruneBefore=1636399935 HTTP/1.1" 304 1151 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.17.0"

Sharing a note from twitter: 
[08/Nov/2021:19:35:20 +0000] "GET /nextcloud/index.php/apps/notes/api/v1/notes?pruneBefore=1636399935 HTTP/1.1" 304 1471 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.17.0"

**Comment by stefan-niedermann** [comment]
Update to the current version of the Notes app (`3.4.16`), this bug has already been fixed.

**Comment by isaacmuro** [comment]
Thank you!
