### ISSUE TITLE
Facing this issue since so many months

### ISSUE THREAD

**Issue by goswamiji321** [stefan-niedermann/nextcloud-notes#1397]
```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30140090

---

OS Version: 4.9.268-shiva-NoName-672764-g81a3f9555c2b-dirty(840)
OS API Level: 30
Device: beryllium
Manufacturer: Xiaomi
Model (and Product): POCOPHONE F1 (beryllium)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to cloud.spryservers.net/209.160.96.107 (port 443) from /192.168.1.41 (port 39037) after 60000ms: isConnected failed: ETIMEDOUT (Connection timed out)
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.nextcloud.android.sso.exceptions.UnknownErrorException: failed to connect to cloud.spryservers.net/209.160.96.107 (port 443) from /192.168.1.41 (port 39037) after 60000ms: isConnected failed: ETIMEDOUT (Connection timed out)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment]
Ignored *and* deleted the issue template, provided literally no information about your environment (looks like an instance which is only accessible from a LAN? obviously related preferences like `Sync only on Wi-Fi`), no information about the used Notes server version, how often and under which circumstances this happens (wifi? mobile data? when switching?), reachability via browser in the same situations, ... not even a single full sentence.

I happily try to provide support, for every user, but honestly, not this way. [→ Try it again.](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed)
