### ISSUE TITLE
Synchronization Failed

### ISSUE THREAD

**Issue by maria-mcdorman** [stefan-niedermann/nextcloud-notes#1408]
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30170190

---

OS Version: 4.9.237-lineageos-g31cab26(b563e068ea)
OS API Level: 30
Device: blueline
Manufacturer: Google
Model (and Product): Pixel 3 (blueline)

---

java.lang.Exception: {"errorType":"OCP\\Lock\\LockedException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by maria-mcdorman** [comment]
Very sorry. First time opening incident. Was opening incident on the actual phone and screen was super small.  Will try again on the correct repository. Again, my apologies.
