### ISSUE TITLE
indexOutOfBoundsEx on new note with emtpy checkbox

### ISSUE THREAD

**Issue by darkenedcolossal** [stefan-niedermann/nextcloud-notes#1411]
reproduction:
1. create new note
2. type "- [ ]" ENTER
3. stacktrace

```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30170190

---

OS Version: 4.9.227-perf+(2109171635)
OS API Level: 30
Device: OnePlus6
Manufacturer: OnePlus
Model (and Product): ONEPLUS A6003 (OnePlus6)

---

java.lang.IndexOutOfBoundsException: replace (0 ... 7) ends beyond length 6
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:513)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.deleteCustomText(AutoContinuationTextWatcher.java:78)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.afterTextChanged(AutoContinuationTextWatcher.java:60)
	at it.niedermann.android.markdown.markwon.textwatcher.LowerIndentionTextWatcher.afterTextChanged(LowerIndentionTextWatcher.java:49)
	at it.niedermann.android.markdown.markwon.textwatcher.SearchHighlightTextWatcher.afterTextChanged(SearchHighlightTextWatcher.java:61)
	at it.niedermann.android.markdown.markwon.textwatcher.CombinedTextWatcher.afterTextChanged(CombinedTextWatcher.java:47)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:10626)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13630)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1277)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:507)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:37)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:866)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:202)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:177)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:353)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:94)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8068)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```

**Comment by darkenedcolossal** [comment]
https://github.com/stefan-niedermann/nextcloud-commons/commit/452974ff79345d178d3ff510695f087db5bd4f8b

ok, looks like it's already gonna be fixed in the next release. although the line number is off by two. but I guess that is how computer stuff is. not the most precise domain.
