### ISSUE TITLE
`NextcloudFilesAppAccountNotFoundException`

### ISSUE THREAD

**Issue by barthohomeautomation** [stefan-niedermann/nextcloud-notes#1417]
Installed app on Android device and sync is failing with the following error. Send to not be able to find nextcloud app. However, the nextcloud app is installed.

```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30180090

---

OS Version: 4.14.190-perf+(2110121803)
OS API Level: 30
Device: OnePlus7TProNR
Manufacturer: OnePlus
Model (and Product): HD1925 (OnePlus7TProNR)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Account not found in nextcloud files app
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Account not found in nextcloud files app
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment]
Hi, which version of the Nextcloud app are you running? From which source did you install the Nextcloud app? Are you using any other 3rd party apps like Deck?

**Comment by barthohomeautomation** [comment]
I am running version 3.18.0. I have tried both the PlayStore and fdroid flavors of the app. I have uninstalled and reinstalled both. No other 3rd party apps were installed.

I was able to resolve the issue. I cleared the cache and storage of the Notes app on the device. After selecting the account on setup, all seems to be good now. I can no longer replicate the error.

**Comment by stefan-niedermann** [comment]
Strange things are happening - well okay, let's close this one then, glad to hear that everything is working now in your environment :)
