### ISSUE TITLE
Crash when pressing enter twice at list item 

### ISSUE THREAD

**Issue by charno** [stefan-niedermann/nextcloud-notes#1421]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

**To Reproduce**

- create new note
- enter `- a` in the note
- press enter twice 

**Expected behavior**

- leave list editing mode

**Smartphone (please complete the following information):**

```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: play

Files App Version Code: 30180090

---

OS Version: 4.14.113-22340597(G973FXXSEFUJ2)
OS API Level: 30
Device: beyond1
Manufacturer: samsung
Model (and Product): SM-G973F (beyond1ltexx)

---

java.lang.IndexOutOfBoundsException: replace (4 ... 7) ends beyond length 6
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1335)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:523)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:517)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.deleteCustomText(AutoContinuationTextWatcher.java:78)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.afterTextChanged(AutoContinuationTextWatcher.java:60)
	at it.niedermann.android.markdown.markwon.textwatcher.LowerIndentionTextWatcher.afterTextChanged(LowerIndentionTextWatcher.java:49)
	at it.niedermann.android.markdown.markwon.textwatcher.SearchHighlightTextWatcher.afterTextChanged(SearchHighlightTextWatcher.java:61)
	at it.niedermann.android.markdown.markwon.textwatcher.CombinedTextWatcher.afterTextChanged(CombinedTextWatcher.java:47)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:11816)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:15266)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1287)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:587)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:517)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
	at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:228)
	at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
	at android.widget.TextView.doKeyDown(TextView.java:9479)
	at android.widget.TextView.onKeyDown(TextView.java:9244)
	at android.view.KeyEvent.dispatch(KeyEvent.java:3624)
	at android.view.View.dispatchKeyEvent(View.java:15050)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:740)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1986)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:901)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1947)
	at android.app.Activity.dispatchKeyEvent(Activity.java:4142)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3068)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:756)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:7365)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:7191)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6595)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6786)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6843)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6652)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6618)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6626)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6599)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9880)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9718)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9671)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:6206)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

```

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app):
(not accessible at the moment, can be provided at request)

**Comment by stefan-niedermann** [comment]
Thanks for reporting this issue and sorry for the inconveniences.

We already are aware of it and fixed it in `3.4.17` (which should be released soon).

If i remember correctly, it is depending on the speed which you are pressing <kbd>Enter</kbd>, so as a workaround until the new version gets rolled out, you shouldn't hit <kbd>Enter</kbd> too fast many times but with a second break.

**Comment by charno** [comment]
Hi @stefan-niedermann 

Thanks for your work. Do you know about when the release will happen? I'm a "list guy", so this breaks my workflow quite seriously.

Ich wünsche schöne Feiertage!

Charno

**Comment by stefan-niedermann** [comment]
Jep, january, sorry for the late reply, quite busy those days.... Guten Rutsch 🙂
