### ISSUE TITLE
Can not login to server on start of application

### ISSUE THREAD

**Issue by jsiegert** [stefan-niedermann/nextcloud-notes#1423]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

After installation, during first login to server the app responds with below error 

**To Reproduce**
1. Go to "Start app"
2. Click on "KIES ACCOUNT"
3. Click on "known account" click on OK, give permission to account

**Expected behavior**

Logon to server, and open notes application

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.16
 - F-Droid or Play Store: Play Store
 - Android-Version: 10
 - Device: Nokia 6.2

**Server**
 - Nextcloud version: 23.0.0
 - Nextcloud Notes version (server app): 4.2.0

**Stacktrace**
```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: play

Files App Version Code: 30180090

---

OS Version: 4.4.194-perf+(00WW_2_400_SP07)
OS API Level: 29
Device: SLD_sprout
Manufacturer: HMD Global
Model (and Product): Nokia 6.2 (Starlord_00EEA)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP aanvraag mislukt met HTTP status-code: 301
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:110)
at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
at io.reactivex.Observable.blockingSingle(Observable.java:5381)
at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity.lambda$onActivityResult$5$it-niedermann-owncloud-notes-importaccount-ImportAccountActivity(ImportAccountActivity.java:97)
at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity$$ExternalSyntheticLambda6.run(Unknown Source:4)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: <html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>

at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
at android.os.Binder.execTransactInternal(Binder.java:1021)
at android.os.Binder.execTransact(Binder.java:994)

```

**Comment by stefan-niedermann** [comment]
Hi @jsiegert 

- did you already try to clear the storage of both apps [as described in our FAQs](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#tokenmismatchexception-and-all-others)?
- did you recently move your Nextcloud instance to another domain or path?
- are you using any reverse proxies or similar technologies?

**Comment by jsiegert** [comment]
Deleted cache, and storage.
Nextcloud is not moved to other domain, or changed to an other path.
Server is directly accessible from the internet or local network.

**Comment by jsiegert** [comment]
Accidentely closed report, and reopened

**Comment by stefan-niedermann** [comment]
Thanks for contacting me via E-Mail -> Let's close this issue and discuss the rest directly :slightly_smiling_face:
