### ISSUE TITLE
Synchronization failed after I enabled Two-Factor TOTP Provider

### ISSUE THREAD

**Issue by mehdiMj-ir** [stefan-niedermann/nextcloud-notes#1432]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Synchronization failed after I enabled Two-Factor TOTP Provider

**To Reproduce**
1. Go to nextcloud->apps and install Two-Factor TOTP Provider.
2. Click on security and enable TOTP.
3. Go to notes app on android.
4. See the error.

**Expected behavior**

To works fine but
![Screenshot_20211224_135858](https://user-images.githubusercontent.com/20270329/147345022-1bda082c-7678-413e-a53a-99fb0b544197.jpg)
![Screenshot_20211224_135710_it niedermann owncloud notes](https://user-images.githubusercontent.com/20270329/147345026-587bbb54-d3d7-464f-9902-d8032bacfa2e.jpg)

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
3.4.16
 - F-Droid or Play Store: 
on F-Droid
 - Android-Version: 
10
 - Device: 
huawei nova 7i

**Server**
 - Nextcloud version: 
![Screenshot_20211224_140235_org mozilla firefox](https://user-images.githubusercontent.com/20270329/147345291-ef963cb1-5022-410e-a7ea-271184ab0960.jpg)

 - Nextcloud Notes version (server app): 
 
![Screenshot_20211224_141226](https://user-images.githubusercontent.com/20270329/147345963-76db3147-de48-4f61-b439-250b7383a2c8.jpg)

![Screenshot_20211224_140039_it niedermann owncloud notes](https://user-images.githubusercontent.com/20270329/147345309-a3d6655c-7997-4e56-8749-ff34138e229b.jpg)

**Stacktrace**
```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 20211217 (Beta)

---

OS Version: 4.14.116(10.1.0.375C185)
OS API Level: 29
Device: HWJNY
Manufacturer: HUAWEI
Model (and Product): JNY-LX1 (JNY-LX1)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:171)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:110)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment]
Hi, did you already try to remove your account from the Notes app and readd it again?

**Comment by mehdiMj-ir** [comment]
Yes I already done that. It will synchronize but will fail after I close and reopen the app.

**Comment by stefan-niedermann** [comment]
And did you also try to remove the account from *both* apps? Nextcloud *and* Notes as suggested [in our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#tokenmismatchexception-and-all-others)? Since we use the SingleSignOn mechanism, they are both coupled with each other and if activating 2fa affects the Nextcloud account in an unexpected way (which it shouldn't), it might cause Notes to stop work properly - it's worth a try 🙂

**Comment by mehdiMj-ir** [comment]
Yes I did really did try it before and even changed my NextCloud password + tried Nginx as web-server. backed with Apache now. the strange thing is I have problem with my NextCloud Dev (Synchronization Client) but my NextCloud Passwords and Bookmarks works just fine.

**Comment by stefan-niedermann** [comment]
> I have problem with my NextCloud Dev (Synchronization Client)

Well, since the Notes app uses SSO as explained above, it *can not* work properly until your Nextcloud Dev app works properly, too. SSO means, that Notes does not perform any network request itself but asks the Nextcloud app to do them, that's why it is necessary, that Nextcloud works properly in the first place.

> NextCloud Passwords and Bookmarks works just fine.

Passwords and Bookmarks both don't use SSO but connect directly to your server, so it is not surprising that they behave differently.

So, sorry but i can't help you much on my end at this stage - Please feel free to reopen the issue (or create a new one) in case Notes does still not work after your Nextcloud Dev app works again 😕.

Another hint: Please disable any kind of battery "optimizations" for your Nextcloud apps, especially Nextcloud itself, Notes, Deck and News to avoid further trouble.

Have some nice days! 🎄

**Comment by mehdiMj-ir** [comment]
Thanks, at least we found out whats going on, know I will try to check and found out whats going on with my Nextcloud Dev. 
Thanks again for your quick answers and response. 
We as an Iranian have [Nowruz](https://en.wikipedia.org/wiki/Nowruz), have a nice days to you as well :)
