### ISSUE TITLE
App crash with bullet points 

### ISSUE THREAD

**Issue by simazar** [stefan-niedermann/nextcloud-notes#1433]
**Describe the bug**
App crash when hitting "enter" twice after a bullet point. 

**To Reproduce**
1. Go to the app
2. Click on any note
3. Add bullet points "-" 
4. Hit "enter" twice (the fist enter will add a bullet point, the second will crash the app) 

**Expected behavior**
No crash, a new line without bullet point. 

**Screenshots**
![Screenshot_20211228-164630](https://user-images.githubusercontent.com/28871869/147583279-55138910-a973-41ff-8777-510ede6290e8.jpg)
![Screenshot_20211228-164647](https://user-images.githubusercontent.com/28871869/147583304-34596be3-ae08-402f-9f6c-7c9834aa049c.jpg)

**Stacktrace**
```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30180090

---

OS Version: 4.4.205-perf+(2010292059)
OS API Level: 29
Device: OnePlus5
Manufacturer: OnePlus
Model (and Product): ONEPLUS A5000 (OnePlus5)

---

java.lang.IndexOutOfBoundsException: replace (116 ... 119) ends beyond length 118
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1340)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:528)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:522)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:42)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.deleteCustomText(AutoContinuationTextWatcher.java:78)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.afterTextChanged(AutoContinuationTextWatcher.java:60)
	at it.niedermann.android.markdown.markwon.textwatcher.LowerIndentionTextWatcher.afterTextChanged(LowerIndentionTextWatcher.java:49)
	at it.niedermann.android.markdown.markwon.textwatcher.SearchHighlightTextWatcher.afterTextChanged(SearchHighlightTextWatcher.java:61)
	at it.niedermann.android.markdown.markwon.textwatcher.CombinedTextWatcher.afterTextChanged(CombinedTextWatcher.java:47)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:10626)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13467)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1292)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:592)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:522)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:42)
	at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:228)
	at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
	at android.widget.TextView.doKeyDown(TextView.java:8497)
	at android.widget.TextView.onKeyDown(TextView.java:8254)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2801)
	at android.view.View.dispatchKeyEvent(View.java:13435)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1937)
	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:491)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1937)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1937)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1937)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1937)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1937)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1937)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1937)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1937)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:460)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1874)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3966)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:599)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3068)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:374)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5796)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5664)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5146)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5199)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5165)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5305)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5173)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5362)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5146)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5199)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5165)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5173)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5146)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7955)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7924)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7864)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4887)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by stefan-niedermann** [comment]
Already fixed in `3.4.17`, will be released in january.

Thanks for the detailled report, though!
