### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Herbertholzkopf** [stefan-niedermann/nextcloud-notes#1434]
If I tr, to make a checkbox with - [ ] and don't leave a space behind the second bracket and I press return I get this error from the app:
(This doesn't happen if I leave a space behind the second bracket)

```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 30180190

---

OS Version: 5.4.86-qgki-04198-ge2e2ee5ed9b9(R.202112140115)
OS API Level: 31
Device: OnePlus9
Manufacturer: OnePlus
Model (and Product): LE2111 (OnePlus9_IND)

---

java.lang.IndexOutOfBoundsException: replace (42 ... 49) ends beyond length 48
	at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1326)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:514)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.deleteCustomText(AutoContinuationTextWatcher.java:78)
	at it.niedermann.android.markdown.markwon.textwatcher.AutoContinuationTextWatcher.afterTextChanged(AutoContinuationTextWatcher.java:60)
	at it.niedermann.android.markdown.markwon.textwatcher.LowerIndentionTextWatcher.afterTextChanged(LowerIndentionTextWatcher.java:49)
	at it.niedermann.android.markdown.markwon.textwatcher.SearchHighlightTextWatcher.afterTextChanged(SearchHighlightTextWatcher.java:61)
	at it.niedermann.android.markdown.markwon.textwatcher.CombinedTextWatcher.afterTextChanged(CombinedTextWatcher.java:47)
	at android.widget.TextView.sendAfterTextChanged(TextView.java:10925)
	at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:13956)
	at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:1278)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:578)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:508)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:38)
	at android.view.inputmethod.BaseInputConnection.replaceText(BaseInputConnection.java:947)
	at android.view.inputmethod.BaseInputConnection.commitText(BaseInputConnection.java:219)
	at com.android.internal.widget.EditableInputConnection.commitText(EditableInputConnection.java:204)
	at com.android.internal.view.IInputConnectionWrapper.executeMessage(IInputConnectionWrapper.java:549)
	at com.android.internal.view.IInputConnectionWrapper$MyHandler.handleMessage(IInputConnectionWrapper.java:111)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8182)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

**Comment by stefan-niedermann** [comment]
Hey there, please see https://github.com/stefan-niedermann/nextcloud-notes/issues/1433#issuecomment-1002182465
