### ISSUE TITLE
Cannot start app

### ISSUE THREAD

**Issue by kopecnydavid5** [stefan-niedermann/nextcloud-notes#1439]
After touch icon open window and imediately close. 
I tried install older version but only show: "Installation failed"

Anyone know what to do? Thank you.
D.

```
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 20211221 (Beta)

---

OS Version: 4.14.116(10.0.0.275C431)
OS API Level: 29
Device: HWMAR
Manufacturer: HUAWEI
Model (and Product): MAR-LX1A (MAR-LX1AEEA)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'long it.niedermann.owncloud.notes.persistence.entity.Note.getId()' on a null object reference
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.onCloseNote(BaseNoteFragment.java:286)
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.close(EditNoteActivity.java:273)
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.onOptionsItemSelected(EditNoteActivity.java:246)
	at android.app.Activity.onMenuItemSelected(Activity.java:4291)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
	at android.view.View.performClick(View.java:7192)
	at android.view.View.performClickInternal(View.java:7166)
	at android.view.View.access$3500(View.java:824)
	at android.view.View$PerformClick.run(View.java:27592)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

```

**Comment by stefan-niedermann** [comment]
> After touch icon open window and imediately close.

Quite weird, especially since this exception is happening in the edit area and according your report, it happens directly after launching the app (list view). Have you tried to <kbd>Force Stop</kbd> the app and start it again (instead of messing around with different versions)?

The best solution to get a clean state is to clear the storage of the app as [described in our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#tokenmismatchexception-and-all-others) (beware that not yet synchronized changes will be lost of course). So please do so and in case the issues persists, feel free to reopen this or create a new issue.

> I tried install older version but only show: "Installation failed"

This hints for cross installations of various different signed sources (like F-Droid, Play Store, Self-Build, etc.). Also note, that non-destructive downgrades are not supported as in the most apps, so you probably will need to clear the storage of the app anyway.


Unfortunately a bit hard to guess any other issues with your environment since you decided to [not only ignore but instead completely delete the issue template](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed).

**Comment by kopecnydavid5** [comment]
Hi Stefan,
Thanks for your quick response. I'm sorry, we're not a programmer and I'm doing this for the first time. I want to help because I like the application very much and it helped me a lot.

I read how to fill in the template and I send the completed one below:

**Describe the bug**
After touch on icon on home screen aplication not launch.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to home screen/ touch home btn
2. Click on icon Nextcloud notes
3. --not launch-- only short open window and imediately close window, no info about error

I tried force stop:
1. Go to Settings/applictions/Nextcloud Notes 
2. Force stop
3. Touch home button
4. Touch icon Nextcloud notes to launch app (view list of notes)
5.  --not launch-- only short open window and imediately close window, no info about error

I got an error message after these steps:
1. Press home button to go on home screen.
2. Long touch on icon Nextcloud notes
3. Tap on "New notes"
4. Application is opened - I show Editor and pointer and i can write something.
5. Above is written "Edit" and arrow "Back".
6. Click on arrow "Back"
7. You got error message"

I tried remove aplication data -> the same result like force stop or noral launch app
I tried install older version in F-droid -> instalation failed
I tried install older version but only show: "Installation failed"

I am using only mobile app without server and without logging 1-2 years.
The problem has occurred after actualisation maybe 12/2021.
How to manualy export Notes from my phone into *.txt or *.rtf, etc.?

**Expected behavior**
After touch on ico I expect launch the app and show list of my notes.


**Screenshots**
![image](https://user-images.githubusercontent.com/48021445/147887940-8d7625d9-ac4a-4079-a1d1-7d6260cb5404.png)

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.16
 - F-Droid or Play Store:  F-Droid
 - Android-Version: 10 (EMUI 10.0.0), last update
 - Device: Huawei P30 lite MAR-LX1A. CPU Kirin 710, 4GB RAM, 


**Server**
 - Nextcloud version:  not using server
 - Nextcloud Notes version (server app): not using server

**Stacktrace**
App Version: 3.4.16
App Version Code: 3004016
App Flavor: fdroid

Files App Version Code: 20211221 (Beta)

---

OS Version: 4.14.116(10.0.0.275C431)
OS API Level: 29
Device: HWMAR
Manufacturer: HUAWEI
Model (and Product): MAR-LX1A (MAR-LX1AEEA)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'long it.niedermann.owncloud.notes.persistence.entity.Note.getId()' on a null object reference
	at it.niedermann.owncloud.notes.edit.BaseNoteFragment.onCloseNote(BaseNoteFragment.java:286)
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.close(EditNoteActivity.java:273)
	at it.niedermann.owncloud.notes.edit.EditNoteActivity.onOptionsItemSelected(EditNoteActivity.java:246)
	at android.app.Activity.onMenuItemSelected(Activity.java:4291)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.widget.ToolbarWidgetWrapper$1.onClick(ToolbarWidgetWrapper.java:188)
	at android.view.View.performClick(View.java:7192)
	at android.view.View.performClickInternal(View.java:7166)
	at android.view.View.access$3500(View.java:824)
	at android.view.View$PerformClick.run(View.java:27592)
	at android.os.Handler.handleCallback(Handler.java:888)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Comment by stefan-niedermann** [comment]
> Nextcloud Notes version (server app): not using server

As mentioned in the description of the app, having installed the [Notes server app](https://apps.nextcloud.com/apps/notes) is mandatory for using the Notes Android app.
