### ISSUE TITLE
Cannot synchronize notes

### ISSUE THREAD

**Issue by domotic-29** [stefan-niedermann/nextcloud-notes#1442]
Hello

Not sure if this is the same as #1437 so I prefer creating a new one.
Since this version, I can't synchronize up or down.

`App Version: 3.4.18
App Version Code: 3004018
App Flavor: fdroid

Files App Version Code: 30170190

---

OS Version: 3.14.27-986474(G361FXXU1APB1)
OS API Level: 22
Device: coreprimevelte
Manufacturer: samsung
Model (and Product): SM-G361F (coreprimeveltexx)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.UnknownErrorException: com.nextcloud.android.sso.QueryParam
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: com.nextcloud.android.sso.exceptions.UnknownErrorException: com.nextcloud.android.sso.QueryParam
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more
`

I get the error message as soon as I open the application, and when I pull down to synchronize.
Sorry, I have not been able to find the version of the server.

**Comment by stefan-niedermann** [comment]
Hi, the issue is different.

You are using a very outdated version of the [Nextcloud Android app](https://play.google.com/store/apps/details?id=com.nextcloud.client) - Please update it, since the Notes Android app requires at least `3.18.x`.
