### ISSUE TITLE
Unable to connect to Nextcloud 22

### ISSUE THREAD

**Issue by mohicanb** [stefan-niedermann/nextcloud-notes#1453]
**Describe the bug**
When trying to create a new note, an error message is displayed

IMPORTANT : the "Nextcloud" App does connect and can show the notes (they can be downloaded).
Only the Notes App does not work.

**To Reproduce**
Open Notes
Click on the "+" button
Error message appears

**Expected behavior**
A new note is edited

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.18
 - F-Droid or Play Store: F-Droid
 - Android-Version:  5.1 (or later ?)
 - Device: Dive_70

**Server**
 - Nextcloud version: 22.2.3
 - Nextcloud Notes version (server app): ?

**Error message**
```
App Version: 3.4.18
App Version Code: 3004018
App Flavor: fdroid

Files App Version Code: 30060090OS Version: 3.10.49-ga3f536d(C109B172)
OS API Level: 22
Device: Dive_70
Manufacturer: Orange
Model (and Product): SCL-L01 (Dive_70)

java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileDescriptor android.os.ParcelFileDescriptor.getFileDescriptor()' on a null object reference
at android.os.ParcelFileDescriptor$AutoCloseInputStream.<init>(ParcelFileDescriptor.java:803)
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:181)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source)
at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
at io.reactivex.Observable.blockingSingle(Observable.java:5381)
at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity.lambda$onActivityResult$5$it-niedermann-owncloud-notes-importaccount-ImportAccountActivity(ImportAccountActivity.java:97)
at it.niedermann.owncloud.notes.importaccount.ImportAccountActivity$$ExternalSyntheticLambda6.run(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:833)
```

**Comment by stefan-niedermann** [comment]
Notes Android requires the Nextcloud app to be at least 3.18.x - i missed the check in the currently released version, but it was part of the release notes.

Since you are running Android 5.1 and the Nextclouf 3.18.x versions require Android 6, you will need tp stick to an older version or upgrade to a newer Android version, for example with a custom ROM.
