### ISSUE TITLE
Failure on synchronisation

### ISSUE THREAD

**Issue by bruzzz** [stefan-niedermann/nextcloud-notes#1465]
**Describe the bug**
The App always reports a failure on synchronisation. 

**To Reproduce**
1. Start the App
2. Sync is started automatically and failes
3. Retry to sync al2ays failes with the same isuue

**Expected behavior**
The synchronisation shall work without error. 

**Screenshots**

**Smartphone (please complete the following information):**

 - Nextcloud Notes-Version (android app): 3.4.18
 - App Version Code: 3004018
 - App Flavor: fdroid
 - Files App Version Code: 30190090
 - Android-Version: 11
 - Device:
OS Version: 4.19.113-22378117(G780GXXU3AUJ2)
OS API Level: 30
Device: r8q
Manufacturer: samsung
Model (and Product): SM-G780G (r8qeea)

**Server**
 - Nextcloud version: 21.0.3
 - Nextcloud Notes version (server app): 4.3.0

**Stacktrace**
```
java.lang.Exception: {"errorType":"Doctrine\\DBAL\\Exception\\InvalidFieldNameException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:174)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by stefan-niedermann** [comment]
Hey 👋 

this error message is not caused by the Notes Android app but by your Notes Server app. Please check whether you are able to view and edit your Notes via web browser and check your server logs.

In case the issue persists and you can't find the cause in the logs, please open an issue in [the Notes sever app repository](https://github.com/nextcloud/notes/issues/new?assignees=&labels=bug%2C+need+to+reproduce&template=bug_report.md&title=InvalidFieldNameException).
