### ISSUE TITLE
Login and synchronizing fails because of 401 from the server

### ISSUE THREAD

**Issue by PureTryOut** [stefan-niedermann/nextcloud-notes#1481]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

Logging in and synchronizing fails with 401 response from the server. Weird because to login I just selected the account it prompted me for (I'm assuming that it got that from the Nextcloud app which is configuree and logged in correctly) but it just failed. After some fiddling I somehow got it to continue but then synchronizing any note fails, again because of the 401 error from the server.

**To Reproduce**
1. Log out of the app
2. Log in again

**Expected behavior**

The app to login and successfully synchronize notes

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.18
 - F-Droid or Play Store: F-Droid
 - Android-Version: 11
 - Device: OnePlus One

**Server**
 - Nextcloud version: 22.2.5
 - Nextcloud Notes version (server app): 4.3.1

**Stacktrace**
```
App Version: 3.4.18
App Version Code: 3004018
App Flavor: fdroid

Files App Version Code: 30190090

---

OS Version: 3.4.113-lineageos-gefdf6294e73(10040338)
OS API Level: 30
Device: bacon
Manufacturer: OnePlus
Model (and Product): A0001 (bacon)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 401
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 401
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more
Caused by: java.lang.IllegalStateException: {"message":"CORS requires basic auth"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

```

**Comment by stefan-niedermann** [comment]
Hello @PureTryOut 👋 

looks like the Single Sign On mechanism of the Nextcloud Android app is in an outdated or inconsisten state. This may happen in some scenarios like domain changes.

Could you please try clearing the data of the Notes Android app, **remove your account from the Nextcloud Android app** and readd it then like [described in our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#workarounds) to retain a clean state?

Since the authentication part doesn't happen in the Notes Android app but in the Nextcloud Android app, it's important to also reimport the account from there.

Kind regards,
Stefan

**Comment by PureTryOut** [comment]
> remove your account from the Nextcloud Android app

Yeah sorry I figured that out in the meantime. The NextCloud Android app was in some weird limbo state and I just had to relog there to fix it. Thanks for your answer, I'll close this!
