### ISSUE TITLE
Notes app does login, but gets Api errors for Nextcloud All-in-one v0.7.0(nc 23.0.2)

### ISSUE THREAD

**Issue by r-hmn** [stefan-niedermann/nextcloud-notes#1484]
**To Reproduce**
1. Installed Deck app from Fdroid. Logged in. So, an account was already known on my device.
2. Download Notes app from Fdroid
3. Start the Notes app
4. Select the existing nextcloud account
5. App showed the "waiting circle" indefinitely.
6. Closed the app and reopened
7. App shows correct profile logo.
8. It fails to sync with the following error

```
App Version: 3.4.18
App Version Code: 3004018
App Flavor: fdroid

Files App Version Code: 20220223 (Beta)

---

OS Version: 4.9.218+(eng.root.20220228.083402)
OS API Level: 29
Device: FP3
Manufacturer: Fairphone
Model (and Product): FP3 (FP3)

---

java.lang.Exception: 
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP aanvraag mislukt met HTTP status-code: 302
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP aanvraag mislukt met HTTP status-code: 302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1021)
	at android.os.Binder.execTransact(Binder.java:994)

```

**Expected behavior**
After opening the app, for syncing to work.

**Server**
 - Nextcloud version: AIO container 0.7.0 beta(nc 23.0.2)
 - Nextcloud Notes version (server app): 
   AHA.. THE NOTES SERVER-SIDE APP WASNT INSTALLED 🙈

Then expected app behaviour(for silly like me) could be to suggest the Server side app should be installed. 

Thanks

**Comment by stefan-niedermann** [comment]
> AHA.. THE NOTES SERVER-SIDE APP WASNT INSTALLED 

So, you already solved it 😆 

> Then expected app behaviour(for silly like me) could be to suggest the Server side app should be installed.

Check out the very first issue on the top of the quite short issue list 😉:

https://github.com/stefan-niedermann/nextcloud-notes/issues/1475

**Comment by r-hmn** [comment]
Hi. yes, sorry. i did check the list, but no title rang a bell for me. As it looked like it did log in. At some point in one of the stacktraces it looked like an API version issue. Not realizing it requires a server-side counterpart.
Thanks for your work
