### ISSUE TITLE
`UnknownErrorException: Read timed out`

### ISSUE THREAD

**Issue by timunrau** [stefan-niedermann/nextcloud-notes#1488]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

- the nextcloud notes app on my phone doesn't sync with my server. 

**To Reproduce**
1. Open the app
2. Change a note 
3. Go back to the notes list. 
4. It will try to sync a while and then show the erro I've pasted below. 

**Expected behavior**

- it should just sync seamlessly. :) 

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: F-Droid 3.4.18
 - Android-Version: 12
 - Device: Samsung S10

**Server**
 - Nextcloud version: 23.0.2
 - Nextcloud Notes version (server app): 4.3.1

**Stacktrace**

```
App Version: 3.4.18
App Version Code: 3004018
App Flavor: fdroid

Files App Version Code: 30190190

---

OS Version: 4.14.190-23230211-abG973WVLS6HVA1(G973WVLS6HVA1)
OS API Level: 31
Device: beyond1q
Manufacturer: samsung
Model (and Product): SM-G973W (beyond1qltecs)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.UnknownErrorException: Read timed out
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: com.nextcloud.android.sso.exceptions.UnknownErrorException: Read timed out
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment]
Please see https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#unknownerrorexception-read-timed-out

1. Is your Nextcloud running on weak hardware and / or busy? Post information about the used hardware.
2. Are you able to seamlessly access your notes within an acceptable loading speed via web interface?
3. How large is the biggest note you have, how many notes do you have at all, how big are your notes in average?
4. Did you try removing and re-adding your account [as described in the FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#workarounds)?
5. If the issue persists, please provide a test account and send the credentials to info@niedermann.it - so I can have a closer look

**Comment by timunrau** [comment]
Thanks for the reply. I looked into it and it seemed to be related to performance. The web interface for Notes was also slow. After solving the performance issues on the server the app works great now. 

Thanks for pointing me in the right direction! I should have figured this out on my own. My apologies for the inconvenience. 

Also, thanks for taking the time to create and maintain this app. It's greatly appreciated!
