### ISSUE TITLE
TokenMismatchException

### ISSUE THREAD

**Issue by stemid** [stefan-niedermann/nextcloud-notes#1490]
**Describe the bug**
Suddenly my Notes app won't sync, it shows the TokenMismatchException, same as many other issues reported here but they're all closed and none of the solutions have worked for me.

I have tried the following steps, in this order;
1. Force stop Notes app
2. Clear cache of Notes app
3. Clear storage of Notes app
4. Uninstall Notes app
5. Repeat steps 1-4 for Nextcloud app
6. Restart phone
7. Reinstall Nextcloud and Notes app
8. Login to Nextcloud through Nextcloud app with qr code

What is also very strange here;
1. Follow steps 1-5 and remove all Nextcloud apps from my phone
2. ensure I have no nextcloud accounts under Accounts in Settings.
3. Install only Nextcloud Notes from play store
4. As soon as I start Nextcloud Notes it shows all my old notes and immediately starts a sync attempt with my old account.

This account is supposed to be cleared no? Maybe that is part of the problem.

I do have DavX installed too, but it has its own account setup under Account Settings. So I'm not sure how many apps I need to uninstall to fix this issue. Already I lost all my auto-sync settings by uninstalling Nextcloud.

**To Reproduce**
1. Install Notes app
2. Start Notes app, immediate sync error

**Expected behavior**
Sync of notes.

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.4.18 from google play store
 - F-Droid or Play Store: google play store
 - Android-Version: 12
 - Device: Pixel 3XL

**Server**
 - Nextcloud version: 21.0.9
 - Nextcloud Notes version (server app): 4.3.1

**Stacktrace**

```
App Version: 3.4.18
App Version Code: 3004018
App Flavor: play

Files App Version Code: 30190190

---

OS Version: 4.9.270-g862f51bac900-ab7613625(8029091)
OS API Level: 31
Device: crosshatch
Manufacturer: Google
Model (and Product): Pixel 3 XL (crosshatch)

---

java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Provided authentication token does not match or package name is not permitted to perform this action
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:145)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.TokenMismatchException: Provided authentication token does not match or package name is not permitted to perform this action
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: com.nextcloud.android.sso.exceptions.TokenMismatchException: Provided authentication token does not match or package name is not permitted to perform this action
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**Comment by stefan-niedermann** [comment]
Hello @stemid 👋 

given that this issue is not (only) caused by the Notes Android app, but by a combination of Notes Android, the Nextclouf Single-Sign-On and the Nextcloud Android app, could you please try not only clear the storage of the Notes Android app, but also remove and readd your account from your Nextcloud Android app as [described in our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#tokenmismatchexception)?

**Comment by stemid** [comment]
Thanks, reinstalling both apps, removing the account from NC app, also had to remove the account from the Notes app but it threw an exception so maybe I could have restarted it or something.

Well now it works.

**Comment by stefan-niedermann** [comment]
Just out of curiosity: Did you change something
- with your authentication like
  - change your password
  - en- / disable two factor authentication
- on your mobile device like
  - Android updates
  - App updates
  - Backup and restore apps, parts of your data or your whole device?

**Comment by stemid** [comment]
> * with your authentication like
>   
>   * change your password
>   * en- / disable two factor authentication
> 
> * on your mobile device like
>   
>   * Android updates
>   * App updates
>   * Backup and restore apps, parts of your data or your whole device?

I think the change closest in time to when I noticed the Notes app error was me moving the nc server from one managed k8s cluster to a new k8s cluster at a different provider.

That involved backing up all NC files to S3, then reading the backup from S3 on the new k8s cluster to a new volume. And exporting/importing the DB.

But no password changes and my old OTP still works.

**Comment by tapocol** [comment]
YMMV. I worked around this issue by clicking my avatar in the top right of the Notes app, clicking "Add account", selecting the same Nextcloud account and clicking "OK". After a minute, the app synced all the previous notes that were not synced. I went to the browser app to confirm and saw all those notes on my Nextcloud account.
