### ISSUE TITLE
all nextcloud accounts are gone

### ISSUE THREAD

**Issue by BuZZ-dEE** [stefan-niedermann/nextcloud-notes#1550]
```
App Version: 3.5.00
App Version Code: 3005000
App Flavor: fdroid

Files App Version Code: 30200390

---

OS Version: 4.14.190-perf+(2205261815)
OS API Level: 30
Device: OnePlus7Pro
Manufacturer: OnePlus
Model (and Product): GM1913 (OnePlus7Pro_EEA)

---

com.nextcloud.android.sso.exceptions.NoCurrentAccountSelectedException: Kein Konto ausgewählt
	at com.nextcloud.android.sso.helper.SingleAccountHelper.getCurrentAccountName(SingleAccountHelper.java:47)
	at com.nextcloud.android.sso.helper.SingleAccountHelper.getCurrentSingleSignOnAccount(SingleAccountHelper.java:54)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$onCreate$7$it-niedermann-owncloud-notes-main-MainActivity(MainActivity.java:171)
	at it.niedermann.owncloud.notes.main.MainActivity$$ExternalSyntheticLambda24.run(Unknown Source:2)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

```

**Comment by BuZZ-dEE** [comment]
Got this error after deleting all app data and reimporting the accounts.

```
App Version: 3.5.00
App Version Code: 3005000
App Flavor: fdroid

Files App Version Code: 30200390

---

OS Version: 4.14.190-perf+(2205261815)
OS API Level: 30
Device: OnePlus7Pro
Manufacturer: OnePlus
Model (and Product): GM1913 (OnePlus7Pro_EEA)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask.lambda$importNotes$1$it-niedermann-owncloud-notes-persistence-NotesImportTask(NotesImportTask.java:57)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:455)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:128)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:111)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1165)
	at android.os.Binder.execTransact(Binder.java:1134)

```

**Comment by stefan-niedermann** [comment]
Check out the [FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#http-status-code-302). You don't have installed the (correct) Notes app on your server or it is disabled.

**Comment by BuZZ-dEE** [comment]
@stefan-niedermann yes, that could be the case (Nextcloud from company). But I think, it should not lead to be all accounts removed. Also maybe the user should get a message that understandable after trying to import an account that does not have the Nextcloud Notes app installed.

Is that possible?

**Comment by stefan-niedermann** [comment]
I do not know your exact environment, but a disabled Notes app on your server alone is not able to cause such a thing like "removing all accounts".

We detect a disabled Notes server app and show [a proper hint](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/app/src/main/res/values/strings.xml#L200) right now. If it is not the case for you, it seems like you have a quite edgy server configuration or some other special environment issue. Please feel free to open a Pull Request to also detect your specific constellation.

As a hint for the future: Please use the issue template instead of ignoring and deleting it, it [is there for a reason](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed). Just throwing in an error message like garbage in a trash bin is not helpful and I have no time to play 10 questions like "Are the accounts removed from your Nextcloud Android app or the Notes Android app?" and a myriad other questions about what you experienced and how to reproduce this error message.
