### ISSUE TITLE
sync failed: Account not found in Nextcloud Files app

### ISSUE THREAD

**Issue by boizoe** [stefan-niedermann/nextcloud-notes#1593]
It worked before

```
App Version: 3.6.0
App Version Code: 3006000
App Flavor: play

Files App Version Code: 30220090

---

OS Version: 4.9.327-gdc5f460d7106(4f6176228e)
OS API Level: 32
Device: sargo
Manufacturer: Google
Model (and Product): Pixel 3a (sargo)

---

com.nextcloud.android.sso.exceptions.NextcloudFilesAppAccountNotFoundException: Account not found in Nextcloud Files app
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:32)
	at it.niedermann.owncloud.notes.main.MainViewModel.lambda$synchronizeCapabilities$13$it-niedermann-owncloud-notes-main-MainViewModel(MainViewModel.java:411)
	at it.niedermann.owncloud.notes.main.MainViewModel$$ExternalSyntheticLambda16.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

```

**Comment by boizoe** [comment]
My mistake
