### ISSUE TITLE
Error while synchronization after folder changing

### ISSUE THREAD

**Issue by bvn13** [stefan-niedermann/nextcloud-notes#1599]
I have changed the default folder to another one and started to get an exception.

```
App Version: 3.4.18
App Version Code: 3004018
App Flavor: fdroid

Files App Version Code: 30220290

---

OS Version: 4.14.116(10.1.0.245C10)
OS API Level: 29
Device: HWYAL
Manufacturer: HUAWEI
Model (and Product): YAL-L41 (YAL-L41RU)

---

android.database.sqlite.SQLiteBlobTooBigException: Row too big to fit into CursorWindow requiredPos=0, totalRows=1
	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:986)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:858)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:153)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:140)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:232)
	at android.database.AbstractCursor.moveToFirst(AbstractCursor.java:271)
	at it.niedermann.owncloud.notes.persistence.dao.NoteDao_Impl.getNoteById(NoteDao_Impl.java:691)
	at it.niedermann.owncloud.notes.persistence.NotesRepository.addNote(NotesRepository.java:428)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:239)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
```

**Comment by stefan-niedermann** [comment]
Did you already try to remove your account (after exporting unsynchronized notes) and reimporting it again?

**Comment by stefan-niedermann** [comment]
Closing due to missing feedback. Let me know in case this still happens after you removed and reimported your account.

**Comment by bvn13** [comment]
@stefan-niedermann 
Unable to reproduce it on last 3.6.0 version from FDroid.
Thank you.
