### ISSUE TITLE
receive timeouts

### ISSUE THREAD

**Issue by markushub** [stefan-niedermann/nextcloud-notes#1617]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

at Synchronization often receive timeouts . 
A 2nd or 3th try works

```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: fdroid

Files App Version Code: 30220390

---

OS Version: 4.19.125-perf+(9ab668)
OS API Level: 30
Device: nairo
Manufacturer: motorola
Model (and Product): moto g 5G plus (nairo_retaile)

---

java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.UnknownErrorException: Read timed out
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: com.nextcloud.android.sso.exceptions.UnknownErrorException: Read timed out
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	... 8 more

```

**To Reproduce**
1. Open notes app
2. Swipe down
4. See sync error and more button...

**Expected behavior**

Skip 1th timeout message and auto try again without notify. Or increase timeout.

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.7.1
 - F-Droid or Play Store: Fdroid
 - Android-Version: 11
 - Device: moto g 5G plus (nairo_retaile)

**Server**
 - Nextcloud version: 25.0.1
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
I think I can't say more than already stated [in the corresponding section of our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#unknownerrorexception-read-timed-out) 🤷‍♂️ 

What are the hardware specs of your server? How many users are using it?

Are you able to reproduce the timeouts when directly calling the REST API via `wget` or `curl`?

**Comment by markushub** [comment]
Thank you for your fast answer. I did some tests. 
Nextcloud is running on Nas. There are less users, but I'm the only one with timeout issue. Notes app for the other users works fine. It's a account specified (size) problem.

I think, I'm the only "Notes" power user. 
I have nearly 500 notes and yes some notes (maybe 10)  are larger than 10k. (20k is the largest file)
Delete notes is no solution for me.

Checks inside local network area:

```
curl https://server/nextcloud/apps/notes/api/v1/notes    # works  
curl ... --connect-timeout 0.070                                              # not working - timeout
curl ... --connect-timeout 0.090                                              # works
```

Is there a place to configure the timeout setting for notes app?

**Comment by stefan-niedermann** [comment]
Thanka for the investigatons.

There is no option tp specify the timeout because the actual network requests are done by the Nextcloud Android app (not the Notes Android app).

So you stated that the timeouts are also happening using the REST API directly via `curl`? The thing is, I believe this is more of a server issue and not "caused" by the Notes Android app, so in my opinion this issue might fit better to the [Notes server app repository](https://github.com/nextcloud/notes/issues/)?

**Comment by markushub** [comment]
Thank you. Timeout with curl default value happens.
Increase timeout to 90ms returns notes data.

You are right,
I will look to Notes server timeout setting.
