### ISSUE TITLE
Sync issue (JsonSyntaxException)

### ISSUE THREAD

**Issue by koug44** [stefan-niedermann/nextcloud-notes#1618]
App can’t sync w/ my Nextcloud instance. I’ve tried to empty cache and data and resync, I’ve the same error

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app):  3.7.0
 - F-Droid or Play Store: F-Droid
 - Android-Version: 12
 - Device: Samsung S20 FE

**Server**
 - Nextcloud version: 25.0.1
 - Note version (nextcloud): 4.6.0

**Stacktrace**
```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: fdroid

Files App Version Code: 30220390

---

OS Version: 4.19.113-24784831(G781WVLS7FVI4)
OS API Level: 31
Device: r8q
Manufacturer: samsung
Model (and Product): SM-G781W (r8qcsx)

---

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 5 path $[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:395)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:1214)
	at com.google.gson.Gson.fromJson(Gson.java:1124)
	at com.google.gson.Gson.fromJson(Gson.java:1094)
	at com.nextcloud.android.sso.api.NextcloudAPI.convertStreamToTargetEntity(NextcloudAPI.java:159)
	at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:130)
	at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
	at io.reactivex.Observable.blockingSingle(Observable.java:5381)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask.lambda$importNotes$1$it-niedermann-owncloud-notes-persistence-NotesImportTask(NotesImportTask.java:57)
	at it.niedermann.owncloud.notes.persistence.NotesImportTask$$ExternalSyntheticLambda1.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 5 path $[0]
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:393)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:384)
	... 24 more
```

Please, tell me if more information is needed (probably)

**Comment by stefan-niedermann** [comment]
Please see https://help.nextcloud.com/t/all-3rd-party-android-apps-stopped-working/150892

This is a general issue which does not only affect Notes and therefore can't be fixed here unfortunately.

**Comment by stefan-niedermann** [comment]
Maybe you can post more information regarding your instance:
- Which web server do you run?
- Did the error appear after upgrading Nextcloud itself?
- Since which Nextcloud version does the error appear?
Ideally directly post it at the linked forum thread to have a single source for all affected people.

**Comment by stefan-niedermann** [comment]
Ultimately helpful would be (in case you are technically experienced):

- What does the server return when fetching the Notes via `wget` or `curl`?
- Are you able to make this reproducible, for example via Docker image or a test account on a public instance?

**Comment by koug44** [comment]
I didn’t answer yesterday because the Nextcloud forums were down and I was unable to see the post forum. Indeed, it’s the same issue and sync w/ Cookbook is also broken.

So I don’t know if you want to go further - I’m technical so I can try some CURL requests if it helps
(and also provide more info if insightful)

**Comment by stefan-niedermann** [comment]
@koug44 did you apply changes to your .htaccess file? An user with the same issue [was able to solve the problem](https://github.com/stefan-niedermann/nextcloud-deck/issues/1387#issuecomment-1338462735).

**Comment by koug44** [comment]
The .htaccess thing is not working for me - would this help ?

I've grepped some lines on my access.log and found this one that seem relevant. I've tried it with httpie (no auth)

``` 
[dalexandre@dalexandre ~]$ http "https://my.domain/owncloud/apps/notes/api/v1/notes?exclude=etag%2Creadonly%2Ccontent%2Ctitle%2Ccategory%2Cfavorite%2Cmodified"
HTTP/1.1 200 OK
{Lot of headers here}

[105] Missing version directory
```

Looking back at my Notes app trace
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 5 path $[0]
``` 

Does this help ?

**Comment by koug44** [comment]
And looking on a search engine with the error message «Missing version directory», I’ve found this thread:
https://help.nextcloud.com/t/solved-errors-blank-page-after-udate-to-2022-11-20/149328/22?u=koug44

Disabling Rainloop fix all sync issues for me: Notes, Recipes, News…
