### ISSUE TITLE
Sync error when returning from viewing/editing note.

### ISSUE THREAD

**Issue by hugalafutro** [stefan-niedermann/nextcloud-notes#1622]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

When I press back to go to the list of all notes, a synchronization error pops up claiming it can't reach my server. This is untrue, the address is reachable and dns-resolvable from the phone 100% of the time. The synchronization actually happens If I pull down in the main menu however I'm never sure if I have to do that or if it happens anyway and I can ignore the error.

**To Reproduce**
1. Go to any note
2. Click on back
3. ???

**Expected behavior**
no error should be popping up or it should say the real reason (the server it claims unreachable is reacha ble)

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.7.1
 - F-Droid or Play Store: play store
 - Android-Version: 13
 - Device: OnePlus 10T 5G (EU version)

**Server**
 - Nextcloud version: 25.0.2
 - Nextcloud Notes version (server app): 4.6.0

**Stacktrace**
I don't know what stacktrace is, here is the error from phone:
```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: play

Files App Version Code: 30230090

---

OS Version: 5.10.101-android12-9-00018-g39cc9b2386ef-ab9041667(S.c3ccc3-5-6)
OS API Level: 33
Device: OP5552L1
Manufacturer: OnePlus
Model (and Product): CPH2415 (CPH2415EEA)

---
'''
java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.UnknownErrorException: Unable to resolve host "[turbomrak.o5.ddns.net](http://turbomrak.o5.ddns.net/)": No address associated with hostname
at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
at io.reactivex.Observable.blockingSingle(Observable.java:5381)
at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Caused by: com.nextcloud.android.sso.exceptions.UnknownErrorException: Unable to resolve host "[turbomrak.o5.ddns.net](http://turbomrak.o5.ddns.net/)": No address associated with hostname
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda0.subscribe(Unknown Source:6)
at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
at io.reactivex.Observable.subscribe(Observable.java:12284)
at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
at io.reactivex.Maybe.subscribe(Maybe.java:4290)
at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
... 8 more
```

**Comment by stefan-niedermann** [comment]
Can you please tell me a bit more about your environment:

- Do you have enabled the `Sync only on Wi-Fi` option in the settings?
- Is the error message reproducible on all three states
  - Wi-Fi
  - Mobile data
  - Airplane mode / Completely offline
- Are you using a VPN?
- Is your Nextcloud instance hosted publicly or on a LAN? Your domain looks like a DynDNS provider which of course can add additional complexity and fail points to the stack.

**Comment by hugalafutro** [comment]
Hi, I was going through the list of your questions, I am indeed using a "vpn" of sorts - Adguard to remove adds which runs as local vpn or some such, and your question about it led me to mark it as not route through adguard which had resolved the issue after it reloaded and I force stopped Notes app and opened it again - no more error. Adguard also uses local cert CA to filter https traffic and I suspect that could've been the main culprit.

I should've thought about that in the first place, my apologies for wasting your time.

The server runs behind reverse-proxy on lan via dyndns address indeed, but the service is remarkably stable in last week the only times it was unreachcable was when I was restarting the docker container or host itself Monitored with uptime-kuma.

**Comment by stefan-niedermann** [comment]
Thanks for the update 🙂. Please note that the Notes Android app itself does not perform any network requests on its own but "asks" the Nextcloud Android app to do them. Might be relevant for your setup.

**Comment by js-d-coder** [comment]
I am facing this issue on Android 11 and Android 14 while using TrackerControl VPN for many months. I always keep my app update to date with latest version.
