### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by moritztw** [stefan-niedermann/nextcloud-notes#1626]
**Describe the bug**
After activation serverside encryption an error occures while syncing notes.

**To Reproduce**
1. Create or edit note.
2. Close note.
3. See error

**Expected behavior**
Sync notes.

**Screenshots**
Error warning: 

```
App Version: 3.7.1
App Version Code: 3007001
App Flavor: play

Files App Version Code: 30230191

---

OS Version: 5.10.107-android13-4-00038-ga6f610f1f1e6-ab9083768(9244662)
OS API Level: 33
Device: bluejay
Manufacturer: Google
Model (and Product): Pixel 6a (bluejay)

---

java.lang.Exception: {"errorType":"OCA\\Encryption\\Exceptions\\MultiKeyEncryptException"}

	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
	at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)

```

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 3.7.1
 - F-Droid or Play Store: PlayStore
 - Android-Version: 13
 - Device: Google Pixel 6a

**Server**
 - Nextcloud version: 25.0.2
 - Nextcloud Notes version (server app): 4.6.0

**Comment by moritztw** [comment]
The Error is not on the side of the Android App but on my server. Sorry.
