### ISSUE TITLE
Notes app crashing when mark some notes to delete

### ISSUE THREAD

**Issue by Happyfeet01** [stefan-niedermann/nextcloud-notes#205]
Hello,

I get an update from F-droid from this App. Since this update the app crashing when I mark some notes to delete these.

My system:

Android 7.1.1
LG Nexus 5x
Rooted with Magisk

Notes 0.10.0
```
04-12 20:28:56.200 W/PackageParser(25534): Unknown element under <manifest>: meta-data at /data/user/0/org.fdroid.fdroid/cache/apks/f-droid.org--1/it.niedermann.owncloud.notes_15.apk Binary XML file line #15
04-12 21:13:58.685 E/AndroidRuntime(17684): Process: it.niedermann.owncloud.notes, PID: 17684
04-12 21:13:58.685 E/AndroidRuntime(17684): 	at it.niedermann.owncloud.notes.persistence.NoteSQLiteOpenHelper.getNotesCustom(NoteSQLiteOpenHelper.java:229)
04-12 21:13:58.685 E/AndroidRuntime(17684): 	at it.niedermann.owncloud.notes.persistence.NoteSQLiteOpenHelper.getLocalModifiedNotes(NoteSQLiteOpenHelper.java:304)
04-12 21:13:58.685 E/AndroidRuntime(17684): 	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:213)
04-12 21:13:58.685 E/AndroidRuntime(17684): 	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:199)
04-12 21:13:58.685 E/AndroidRuntime(17684): 	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:170)
04-13 06:26:54.880 I/ActivityManager(1955): Start proc 6565:com.dvtonder.chronus/u0a228 for service com.dvtonder.chronus/com.evernote.android.job.v21.PlatformJobService
04-13 06:29:11.964 I/ActivityManager(1955): START u0 {flg=0x24000000 cmp=it.niedermann.owncloud.notes/.android.activity.CreateNoteActivity} from uid 10307 on display 0
04-13 06:29:11.987 W/ActivityManager(1955): startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x24000000 cmp=it.niedermann.owncloud.notes/.android.activity.CreateNoteActivity }
04-13 06:29:12.032 I/ActivityManager(1955): Start proc 8310:it.niedermann.owncloud.notes/u0a307 for activity it.niedermann.owncloud.notes/.android.activity.CreateNoteActivity
04-13 06:29:12.096 W/System  (8310): ClassLoader referenced unknown path: /data/app/it.niedermann.owncloud.notes-1/lib/arm64
04-13 06:29:12.615 I/ActivityManager(1955): Displayed it.niedermann.owncloud.notes/.android.activity.CreateNoteActivity: +603ms
04-13 06:29:29.949 I/ActivityManager(1955): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=it.niedermann.owncloud.notes/.android.activity.NotesListViewActivity bnds=[24,1450][230,1728] (has extras)} from uid 10030 on display 0
04-13 06:29:30.219 D/ZenLog  (1955): intercepted: 0|it.niedermann.owncloud.notes|10|null|10307,alarmsOnly
04-13 06:29:30.222 V/NotificationService(1955): pkg=it.niedermann.owncloud.notes canInterrupt=false intercept=true
04-13 06:29:30.234 V/NotificationService(1955): pkg=it.niedermann.owncloud.notes canInterrupt=false intercept=true
04-13 06:29:30.237 D/NoteServerSyncHelper(8310): Network connection established.
04-13 06:29:30.237 D/NoteServerSyncHelper(8310): Sync requested (full; network connected, sync NOT active) ...
04-13 06:29:30.238 D/NoteServerSyncHelper(8310): ... starting now
04-13 06:29:30.283 D/BaseStreamManager(6016): Promised set @ r#1213 for (it.niedermann.owncloud.notes,tag=null,id=10,notifKey=0|it.niedermann.owncloud.notes|10|null|10307)
04-13 06:29:30.284 D/DynamicBucketRankerImpl(6016): StreamItemId{notifKey=0|it.niedermann.owncloud.notes|10|null|10307, packageName=it.niedermann.owncloud.notes, id=10, revision=1213, originalRevision=977} in bucket #3 (Ongoing)
04-13 06:29:30.284 D/WatchStreamDB(6016): StreamItem[StreamItemId{notifKey=0|it.niedermann.owncloud.notes|10|null|10307, packageName=it.niedermann.owncloud.notes, id=10, revision=1213, originalRevision=977},StreamItemDataImpl[title=10 chars creatorNode=null, originalPackageName=it.niedermann.owncloud.notes, localPackageName=it.niedermann.owncloud.notes, appName=Notizen, postTime=1492057770215, lastInterruptTime=0, user=UserHandle{0}, onlyAlertOnce=false, vibration pattern=null, interruptive=false, summary=false, hasCustomContentView=false, dismissalId=null, bridgeTag=null]] ranked at index 0
04-13 06:29:30.285 D/DatabaseEventLogger(6016):     StreamItemId{notifKey=0|it.niedermann.owncloud.notes|10|null|10307, packageName=it.niedermann.owncloud.notes, id=10, revision=1213, originalRevision=977}
04-13 06:29:30.285 D/DatabaseEventLogger(6016):         StreamItemId{notifKey=0|it.niedermann.owncloud.notes|10|null|10307, packageName=it.niedermann.owncloud.notes, id=10, revision=1213, originalRevision=977}
04-13 06:29:30.286 D/BaseStreamManager(6016): Promised set @ r#1214 for (it.niedermann.owncloud.notes,tag=null,id=10,notifKey=0|it.niedermann.owncloud.notes|10|null|10307)
04-13 06:29:30.289 D/DynamicBucketRankerImpl(6016): StreamItemId{notifKey=0|it.niedermann.owncloud.notes|10|null|10307, packageName=it.niedermann.owncloud.notes, id=10, revision=1214, originalRevision=977} in bucket #3 (Ongoing)
04-13 06:29:30.290 D/WatchStreamDB(6016): StreamItem[StreamItemId{notifKey=0|it.niedermann.owncloud.notes|10|null|10307, packageName=it.niedermann.owncloud.notes, id=10, revision=1214, originalRevision=977},StreamItemDataImpl[title=10 chars creatorNode=null, originalPackageName=it.niedermann.owncloud.notes, localPackageName=it.niedermann.owncloud.notes, appName=Notizen, postTime=1492057770227, lastInterruptTime=0, user=UserHandle{0}, onlyAlertOnce=false, vibration pattern=null, interruptive=false, summary=false, hasCustomContentView=false, dismissalId=null, bridgeTag=null]] ranked at index 0
04-13 06:29:30.291 D/DatabaseEventLogger(6016):     StreamItemId{notifKey=0|it.niedermann.owncloud.notes|10|null|10307, packageName=it.niedermann.owncloud.notes, id=10, revision=1214, originalRevision=977}
04-13 06:29:30.291 D/DatabaseEventLogger(6016):         StreamItemId{notifKey=0|it.niedermann.owncloud.notes|10|null|10307, packageName=it.niedermann.owncloud.notes, id=10, revision=1214, originalRevision=977}
04-13 06:29:30.365 D/SyncTask(8310):    Process Local Note: #1/R43194       / 2017-03-26 17:41:05 offizielle Version 0.6.65 läuft auf google Nexus 5X (bullhead), Android 7.1.1 (N (2) (2017-03-26 17:44:06 / null) LOCAL_DELETED
04-13 06:29:30.390 D/NotesClient(8310): DELETE https://cloud.larsmueller.net/index.php/apps/notes/api/v0.2/notes/43194
04-13 06:29:30.449 I/ActivityManager(1955): Displayed it.niedermann.owncloud.notes/.android.activity.NotesListViewActivity: +469ms
04-13 06:29:39.099 D/SyncTask(8310):    Process Local Note: #3/R43095       / 80 25 68 56 28 76 78 78 (2017-03-24 05:22:18 / null) LOCAL_DELETED
04-13 06:29:39.100 D/NotesClient(8310): DELETE https://cloud.larsmueller.net/index.php/apps/notes/api/v0.2/notes/43095
04-13 06:29:42.643 D/SyncTask(8310):    Process Local Note: #9/R43376       / Einkauf (2017-04-10 18:33:49 / null) LOCAL_DELETED
04-13 06:29:42.645 D/NotesClient(8310): DELETE https://cloud.larsmueller.net/index.php/apps/notes/api/v0.2/notes/43376
04-13 06:29:46.497 D/NotesClient(8310): GET https://cloud.larsmueller.net/index.php/apps/notes/api/v0.2/notes
04-13 06:29:47.635 D/SyncTask(8310):    Process Remote Note: R43193       / 2017-03-26 17:41:05 offizielle Version 0.6.65 läuft auf google Nexus 5X (bullhead), Android 7.1.1 (N (2017-03-26 17:41:49 / null)
04-13 06:29:47.669 D/NoteSQLiteOpenHelper(8310): updateNote: R43193       / 2017-03-26 17:41:05 offizielle Version 0.6.65 läuft auf google Nexus 5X (bullhead), Android 7.1.1 (N (2017-03-26 17:41:49 / null) || forceUnchangedDBNoteState: null  => 0 rows updated
04-13 06:29:47.671 D/SyncTask(8310):    Process Remote Note: R43082       / Android ID: 23.3.17 (2017-03-23 10:32:28 / null)
04-13 06:29:47.715 D/NoteSQLiteOpenHelper(8310): updateNote: R43082       / Android ID: 23.3.17 (2017-03-23 10:32:28 / null) || forceUnchangedDBNoteState: null  => 0 rows updated
04-13 06:29:47.717 D/SyncTask(8310):    Process Remote Note: R23927       / Besprechung SM Notiz (2017-01-02 01:02:07 / null)
04-13 06:29:47.766 D/NoteSQLiteOpenHelper(8310): updateNote: R23927       / Besprechung SM Notiz (2017-01-02 01:02:07 / null) || forceUnchangedDBNoteState: null  => 0 rows updated
04-13 06:29:47.769 D/SyncTask(8310):    Process Remote Note: R37513  (*)  / Blitzer A66 (2017-02-15 13:17:01 / null)
04-13 06:29:47.818 D/NoteSQLiteOpenHelper(8310): updateNote: R37513  (*)  / Blitzer A66 (2017-02-15 13:17:01 / null) || forceUnchangedDBNoteState: null  => 0 rows updated
04-13 06:29:47.819 D/SyncTask(8310):    Process Remote Note: R23944  (*)  / Bootloader unlock key Sony Xperia Z3 (2017-01-02 01:02:19 / null)
04-13 06:29:47.867 D/NoteSQLiteOpenHelper(8310): updateNote: R23944  (*)  / Bootloader unlock key Sony Xperia Z3 (2017-01-02 01:02:19 / null) || forceUnchangedDBNoteState: null  => 0 rows updated
04-13 06:29:47.868 D/SyncTask(8310):    Process Remote Note: R39158     
```

**Comment by korelstar** [comment]
At which point the app crashes exactly? When selecting the first note, when selecting further notes or when pressing the delete button?

The log is very interesting, but it seems that it is incomplete. There should be more log data at the time 04-12 21:13. Can you please provide more from that log (or generate a new one)?

**Comment by stefan-niedermann** [comment]
Dear @Happyfeet01
can you please retest with v0.11.0 - i have a feeling it will not be reproducable ;-) 
Regards
