### ISSUE TITLE
"Notes has stopped" on first run

### ISSUE THREAD

**Issue by dan0xii** [stefan-niedermann/nextcloud-notes#472]
I get a fatal exception on a fresh install of the master branch. I say "fresh": this is on my phone and I have been reinstalling various test versions.

It appears that the crash is this line in setupNavigationMenu() called by onCreate() in NoteListViewActivity.java:
`this.account.setText(username + "@" + url.substring(0, url.length() - 1));`

"url" is set to "" as per:
 `String url = preferences.getString(SettingsActivity.SETTINGS_URL, SettingsActivity.DEFAULT_SETTINGS).replace("https://", "").replace("http://", "");`

So url.substring() causes the crash, as best as I can see. The strange thing is that I was replaying the crash and around 1 in 10 attempts the first run screen would be displayed waiting for server information as expected.

Phone is running 7.1.2 (Lineage 14.1) and has run the notes app fine up until now. I've tried uninstalling and reinstalling from f-droid with the same result.

Logcat:
09-05 09:36:48.924 20530-20530/? I/art: Late-enabling -Xcheck:jni
09-05 09:36:49.223 20530-20530/? W/System: ClassLoader referenced unknown path: /data/app/it.niedermann.owncloud.notes-1/lib/arm64
09-05 09:36:49.238 20530-20530/? I/InstantRun: starting instant run server: is main process
09-05 09:36:49.297 20530-20530/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
09-05 09:36:49.434 20530-20530/? D/NoteListViewActivity: onCreate: isConfigured: false
09-05 09:36:49.626 20530-20530/? D/NoteServerSyncHelper: Network connection established.
09-05 09:36:49.632 20530-20598/? D/NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
09-05 09:36:49.654 20530-20530/? D/AndroidRuntime: Shutting down VM
09-05 09:36:49.655 20530-20530/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: it.niedermann.owncloud.notes, PID: 20530
    java.lang.RuntimeException: Unable to start activity ComponentInfo{it.niedermann.owncloud.notes/it.niedermann.owncloud.notes.android.activity.NotesListViewActivity}: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.StringIndexOutOfBoundsException: length=0; regionStart=0; regionLength=-1
        at java.lang.String.substring(String.java:1931)
        at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.setupNavigationMenu(NotesListViewActivity.java:378)
        at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.onCreate(NotesListViewActivity.java:138)
        at android.app.Activity.performCreate(Activity.java:6684)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by korelstar** [comment]
This was introduced in #458.
However, @stefan-niedermann wrote there, that he plans to revert this. This bug makes this more urgent ...

**Comment by stefan-niedermann** [comment]
Well, i planned to revert the layout but still display the account name.

**Comment by stefan-niedermann** [comment]
Will have a look asap
