### ISSUE TITLE
Crash upon cutting the last item of a bullet list

### ISSUE THREAD

**Issue by vchryssos** [stefan-niedermann/nextcloud-notes#604]
Notes version: 1.0.0
Android version: 9.0

Reproduceability:
- make a list of items, using "*" notation for each list item
- select last item
- cut
- *Notes* crashes with following log

Log:
Version: 1.0.0

```
java.lang.IndexOutOfBoundsException: charAt: 469 >= length 469
	at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:123)
	at android.text.CharSequenceCharacterIterator.current(CharSequenceCharacterIterator.java:58)
	at android.text.CharSequenceCharacterIterator.setIndex(CharSequenceCharacterIterator.java:83)
	at android.icu.text.RuleBasedBreakIterator.CISetIndex32(RuleBasedBreakIterator.java:1126)
	at android.icu.text.RuleBasedBreakIterator.isBoundary(RuleBasedBreakIterator.java:503)
	at android.text.method.WordIterator.isBoundary(WordIterator.java:95)
	at android.widget.Editor$SelectionHandleView.positionAtCursorOffset(Editor.java:5467)
	at android.widget.Editor$HandleView.invalidate(Editor.java:4577)
	at android.widget.Editor$SelectionModifierCursorController.invalidateHandles(Editor.java:6145)
	at android.widget.Editor.invalidateHandlesAndActionMode(Editor.java:1985)
	at android.widget.TextView.spanChange(TextView.java:9926)
	at android.widget.TextView$ChangeWatcher.onSpanRemoved(TextView.java:12548)
	at android.text.SpannableStringBuilder.sendSpanRemoved(SpannableStringBuilder.java:1292)
	at android.text.SpannableStringBuilder.removeSpan(SpannableStringBuilder.java:500)
	at android.text.SpannableStringBuilder.removeSpan(SpannableStringBuilder.java:799)
	at android.text.SpannableStringBuilder.removeSpan(SpannableStringBuilder.java:787)
	at com.yydcdut.markdown.live.ListLive.updateListSpanBeginning(ListLive.java:641)
	at com.yydcdut.markdown.live.ListLive.onTextChanged(ListLive.java:149)
	at com.yydcdut.markdown.live.LivePrepare.onTextChanged(LivePrepare.java:81)
	at com.yydcdut.markdown.MarkdownEditText.onTextChanged4Controller(MarkdownEditText.java:252)
	at com.yydcdut.markdown.MarkdownEditText.access$700(MarkdownEditText.java:44)
	at com.yydcdut.markdown.MarkdownEditText$EditTextWatcher.onTextChanged(MarkdownEditText.java:176)
	at android.widget.TextView.sendOnTextChanged(TextView.java:9754)
	at android.widget.TextView.handleTextChanged(TextView.java:9851)
	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:12509)
	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1263)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:575)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:229)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:36)
	at android.widget.TextView.deleteText_internal(TextView.java:12018)
	at android.widget.TextView.onTextContextMenuItem(TextView.java:11284)
	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4181)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2392)
	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:98)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:776)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:148)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:923)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:913)
	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0(FloatingActionMode.java:123)
	at com.android.internal.view.-$$Lambda$FloatingActionMode$LU5MpPuKYDtwlFAuYhXYfzgLNLE.onMenuItemClick(Unknown Source:2)
	at com.android.internal.widget.FloatingToolbar$FloatingToolbarPopup$2.onClick(FloatingToolbar.java:443)
	at android.view.View.performClick(View.java:6605)
	at android.view.View.performClickInternal(View.java:6582)
	at android.view.View.access$3100(View.java:778)
	at android.view.View$PerformClick.run(View.java:25897)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by stefan-niedermann** [comment]
Please have a look at https://github.com/stefan-niedermann/nextcloud-notes/pull/622.

TL;DR: I think i might have found a workaround which prevents the actual crash, but a complete fix is not possible for us until we have found and implemented another markdown rendering library.
