### ISSUE TITLE
Crash on start. shortLabel cannot be empty

### ISSUE THREAD

**Issue by klitztuch** [stefan-niedermann/nextcloud-notes#613]
**Android version:**  10

**Device**: Google Pixel 2 XL

**System language**: German

**App version:** v1.0.1

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. Wait

**Crashlog:**
`Version: 1.0.1

```java.lang.IllegalArgumentException: shortLabel cannot be empty
	at com.android.internal.util.Preconditions.checkStringNotEmpty(Preconditions.java:99)
	at android.content.pm.ShortcutInfo$Builder.setShortLabel(ShortcutInfo.java:1099)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity$1.lambda$onFinish$0$NotesListViewActivity$1(NotesListViewActivity.java:139)
	at it.niedermann.owncloud.notes.android.activity.-$$Lambda$NotesListViewActivity$1$ocIFrs73Sz51yGOPF2fQeWfnL50.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity$1.onFinish(NotesListViewActivity.java:149)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.onPostExecute(NoteServerSyncHelper.java:436)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.onPostExecute(NoteServerSyncHelper.java:264)
	at android.os.AsyncTask.finish(AsyncTask.java:755)
	at android.os.AsyncTask.access$900(AsyncTask.java:192)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by stefan-niedermann** [comment]
Thank you for report, i will have a look.

**Comment by stefan-niedermann** [comment]
This should not happen again starting with the next released version. Though i am wondering how this happened initially :confused: :question:

Did you have a note which was completely empty, even without a title?
