### ISSUE TITLE
App crashes when clicking on checkbox

### ISSUE THREAD

**Issue by silas229** [stefan-niedermann/nextcloud-notes#642]
I clicked on a checkbox in a checklist in the expectation that it would no longer be checked.

## Error log
```
Version: 2.1.2

java.lang.IllegalArgumentException: Center point is not inside any of the rectangles!
	at android.widget.SmartSelectSprite.startAnimation(SmartSelectSprite.java:392)
	at android.widget.SelectionActionModeHelper.startSelectionActionModeWithSmartSelectAnimation(SelectionActionModeHelper.java:319)
	at android.widget.SelectionActionModeHelper.lambda$l1f1_V5lw6noQxI_3u11qF753Iw(Unknown Source:0)
	at android.widget.-$$Lambda$SelectionActionModeHelper$l1f1_V5lw6noQxI_3u11qF753Iw.accept(Unknown Source:4)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:910)
	at android.widget.SelectionActionModeHelper$TextClassificationAsyncTask.onPostExecute(SelectionActionModeHelper.java:864)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6923)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
```

**Comment by stefan-niedermann** [comment]
Can you please test the linked `.apk`-file in this PR: https://github.com/stefan-niedermann/nextcloud-notes/pull/651 ?

**Comment by silas229** [comment]
Unfortunately, I couldn't install the apk ![App was not installed](https://i.silas229.de/images/Screenshot_20200101-213308.png)

**Comment by stefan-niedermann** [comment]
You have to uninstall notes and then install the app, because this debug version has a different signing key from release-versions :)

**Comment by stefan-niedermann** [comment]
Any news on this @silas229 ?

**Comment by stefan-niedermann** [comment]
Closing die to missing feedback. This bug should be fixed in the meantime.

Please reopen if it happens again.

**Comment by silas229** [comment]
Hi, sorry for the absence - now everything works the way it should 👍

**Comment by stefan-niedermann** [comment]
Glad to hear that :)

**Comment by NStreet8579** [comment]
@silas229 Hi, i have been facing this issue. could you guide me how did you fix it?
