### ISSUE TITLE
Display better hint when files app version is not supported

### ISSUE THREAD

**Issue by mMuck** [stefan-niedermann/nextcloud-notes#659]
Hi there,
perhaps this is a duplicate of #652 - could be the same situation when the app is syncing notes. BTW where is that error report from? On two of our Galaxy S5 the new notes app crashes without any information. A Galaxy Tablet with Android 4.4.2 works fine with the new version (multiple accounts and SSO).
After reopening the app it crashes every time until I delete the app data storage. It's not related to the specific account. On all three accounts it crashes at the same moment.

I need a hint how I can help with more information for troubleshooting. :smiley:.

Thanks, Markus

Android: 6.0.1 System language: German
nextcloud-notes: 2.3.0 (F-Droid, latest NC app F-Droid too)
I have the latest Deck (alpha) version installed with a test account connected. This (SSO related thing :wink:) works fine there.

**Comment by stefan-niedermann** [comment]
Okay, can you grab a logcat from the crash?

How many notes do you have? Maybe there is some limitation for the very first sync... Can you try to move everything out of your "Notes"-folder in your nextcloud and the putting the notes part by part back (each time syncing)?

**Comment by mMuck** [comment]
> Okay, can you grab a logcat from the crash?

```
System.err
remove failed: ENOENT (No such file or directory) : /data/user/0/it.niedermann.owncloud.notes/shared_prefs/single-sign-on.xml.bak

System.err
at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:194)

System.err
at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:124)

System.err
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:350)

System.err
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:277)

System.err
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:248)
```
:arrow_up: I don't know if this errors at 'warning' level are important, but this happend in the 300 ms before...
Here the fatal error:

```
AndroidRuntime
FATAL EXCEPTION: AsyncTask #1
Process: it.niedermann.owncloud.notes, PID: 19060
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
at org.json.JSONTokener.nextCleanInternal(JSONTokener.java:116)
at org.json.JSONTokener.nextValue(JSONTokener.java:94)
at org.json.JSONArray.<init>(JSONArray.java:92)
at org.json.JSONArray.<init>(JSONArray.java:108)
at it.niedermann.owncloud.notes.util.ServerResponse$NotesResponse.getNotes(ServerResponse.java:37)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:351)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:277)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:248)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```
 
> How many notes do you have? Maybe there is some limitation for the very first sync... Can you try to move everything out of your "Notes"-folder in your nextcloud and the putting the notes part by part back (each time syncing)?

Good idea. But I tried with different accounts. Even that one with only one dummy note don't work.
Are you doubting the notes app can handle some hundreds of notes? Should be possible. :wink:

**Comment by stefan-niedermann** [comment]
> Are you doubting the notes app can handle some hundreds of notes?

😆 Nooo, in Notes i trust! But see where "works on my machine!" has brought us! 😆 

Serioulsy, it shouldn't be a problem, but i currently have no idea what the exact problem is. I will work on it.

It's especially strange that Deck works and Notes doesn't.

**Comment by stefan-niedermann** [comment]
Can you provide me a test account on your instance so i can debug the problem?

**Comment by stefan-niedermann** [comment]
One more question: We heard that the (server) app "RansomwareDetection" causes issues wit SSO.

Is this app enabled abd does the problem persist if the app is disabled?

**Comment by mMuck** [comment]
Sorry for replying late... 

> One more question: We heard that the (server) app "RansomwareDetection" causes issues wit SSO.
> 
> Is this app enabled abd does the problem persist if the app is disabled?

Isn't installed at the used server instances.

> Can you provide me a test account on your instance so i can debug the problem?

Separate Mail... Can I use a niedermann dot it contact?

**Comment by stefan-niedermann** [comment]
Yes

**Comment by mMuck** [comment]
Tested the newer v2.4.0 on F-Droid.
Still not working, but not crashing. I get a toast with part of the message above

> ...Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference...

Installed v2.4.6 manually. With the new debug message instead of crashing it displayed this:
```
App Version: 2.4.6
App Version Code: 69
Files App Version Code: 30080190
OS Version: 3.4.0-9493471(G900FXXS1CQC1)
OS API Level: 23
Device: klte
Model (and Product): SM-G900F (kltexx)
java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileDescriptor android.os.ParcelFileDescriptor.getFileDescriptor()' on a null object reference
at android.os.ParcelFileDescriptor$AutoCloseInputStream.<init>(ParcelFileDescriptor.java:842)
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:149)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:191)
at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:123)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:362)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:290)
at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:261)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```
And doesn't sync.
I have a positive result with other devices beside the SM-G900F (kltexx) - there Notes is syncing and working. Don't know where the difference is.

**Comment by stefan-niedermann** [comment]
> Files App Version Code: 30080190

Are you using Files app in version 3.8.x?

Notes requires at least Files app in  version >= 3.9.0

**Comment by stefan-niedermann** [comment]
I was able to reproduce the exactly same stack trace like you posted with files app version `3.8.x`. I built in a check and a better hint to the user (something like "Is your files app up to date").
