### ISSUE TITLE
ACCOUNT_ID was not created on upgrade

### ISSUE THREAD

**Issue by lukasdietz** [stefan-niedermann/nextcloud-notes#662]
A while ago the Notes App crashes at every startup. Therefore it is quite useless as it is.

I am using a OnePlus 3 with Havoc OS on Android 10.

The Error is following:
```
Version: 2.3.0

java.lang.RuntimeException: Unable to start activity ComponentInfo{it.niedermann.owncloud.notes/it.niedermann.owncloud.notes.android.activity.NotesListViewActivity}: android.database.sqlite.SQLiteException: no such column: ACCOUNT_ID (code 1 SQLITE_ERROR): , while compiling: CREATE INDEX IF NOT EXISTS NOTES_ACCOUNT_ID_idx ON NOTES(ACCOUNT_ID)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by: android.database.sqlite.SQLiteException: no such column: ACCOUNT_ID (code 1 SQLITE_ERROR): , while compiling: CREATE INDEX IF NOT EXISTS NOTES_ACCOUNT_ID_idx ON NOTES(ACCOUNT_ID)
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:986)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:593)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:61)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1814)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1742)
	at it.niedermann.owncloud.notes.util.DatabaseIndexUtil.createIndex(DatabaseIndexUtil.java:26)
	at it.niedermann.owncloud.notes.util.DatabaseIndexUtil.createIndex(DatabaseIndexUtil.java:19)
	at it.niedermann.owncloud.notes.persistence.NoteSQLiteOpenHelper.createNotesIndexes(NoteSQLiteOpenHelper.java:285)
	at it.niedermann.owncloud.notes.persistence.NoteSQLiteOpenHelper.createNotesTable(NoteSQLiteOpenHelper.java:127)
	at it.niedermann.owncloud.notes.persistence.NoteSQLiteOpenHelper.onUpgrade(NoteSQLiteOpenHelper.java:166)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:417)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:341)
	at it.niedermann.owncloud.notes.persistence.NoteSQLiteOpenHelper.getAccounts(NoteSQLiteOpenHelper.java:788)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.setupHeader(NotesListViewActivity.java:295)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.onCreate(NotesListViewActivity.java:216)
	at android.app.Activity.performCreate(Activity.java:7824)
	at android.app.Activity.performCreate(Activity.java:7813)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	... 11 more
```
I hope somebody can help me. 
With best regards
Lukas

**Comment by stefan-niedermann** [comment]
From which version exactly did you update?

**Comment by stefan-niedermann** [comment]
This is important, since we created the new `ACCOUNT_ID` column a while ago and it did not seem to be created at your device.

(The simplest solution is, to un- and reinstall the app (or to delete the app storage) - this will create a clear database, **but** it will reset all your local changes which didn't sync yet and it will reset your widget configurations)

**Comment by lukasdietz** [comment]
> This is important, since we created the new `ACCOUNT_ID` column a while ago and it did not seem to be created at your device.
> 
> (The simplest solution is, to un- and reinstall the app (or to delete the app storage) - this will create a clear database, **but** it will reset all your local changes which didn't sync yet and it will reset your widget configurations)

Thanks for the quick answer! This solved the Problem instantly.

**Comment by stefan-niedermann** [comment]
Can you please still name the exact version from where you upgraded? This might be helpful for other users.

**Comment by lukasdietz** [comment]
I am not quite sure but it should have been Version 2.1.3
