### ISSUE TITLE
Not sync 

### ISSUE THREAD

**Issue by oktay454** [stefan-niedermann/nextcloud-notes#685]
```
App Version: 2.4.6
App Version Code: 69
Files App Version Code: 30090290

---

OS Version: 3.18.120-perf-gb1e950088d73(3010)
OS API Level: 28
Device: daisy_sprout
Model (and Product): MI A2 Lite (daisy_sprout)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP isteği şu HTTP durum koduyla karşılanamadı: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:155)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:191)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:123)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:362)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:290)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:261)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: <!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="tr" data-locale="tr_TR" >
	<head
 data-requesttoken="">
		<meta charset="utf-8">
		<title>
		Disroot Cloud		</title>
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
				<meta name="apple-itunes-app" content="app-id=1125420102">
				<meta name="theme-color" content="#50162D">
		<link rel="icon" href="/apps/theming/favicon?v=65">
		<link rel="apple-touch-icon" href="/apps/theming/icon?v=65">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#50162D">
		<link rel="manifest" href="/apps/theming/manifest?v=65">
		<link rel="stylesheet" href="/apps/apporder/css/apporder.css?v=778cf622-65">
<link rel="stylesheet" href="/apps/deck/css/activity.css?v=1f9fea20-65">
<link rel="stylesheet" href="/apps/files_ebookreader/css/style.css?v=25e64aa7-65">
<link rel="stylesheet" href="/apps/files_pdfviewer/css/style.css?v=ca9f0d77-65">
<link rel="stylesheet" href="/core/css/guest.css?v=37c9174a-65">
		<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/core/js/dist/main.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/js/core/merged-template-prepend.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/core/search/js/search.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/core/l10n/tr.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/apporder/l10n/tr.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/apporder/js/apporder.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/encryption/l10n/tr.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/encryption/js/encryption.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/core/js/dist/share_backend.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/files_ebookreader/js/previewplugin.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/files_pdfviewer/js/previewplugin.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/files_videoplayer/js/main.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/gallery/l10n/tr.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/notifications/l10n/tr.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/notifications/js/notifications.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/apps/rainloop/js/rainloop.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/core/search/js/searchprovider.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/core/js/files/fileinfo.js?v=37c9174a-65"></script>
<script nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0=" defer src="/core/js/files/client.js?v=37c9174a-65"></script>
		<link rel="stylesheet" href="/apps/accessibility/css/user-5da9e28bb7fc7a69884bd6c04419273e"/><script defer src="/apps/accessibility/js/accessibility?v=0" nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0="></script><link rel="stylesheet" href="/apps/theming/styles?v=65"/><script defer src="/apps/theming/js/theming?v=65" nonce="T0c0UE8vZUhaQXlYRGtGQ2llb21JWlBSOWltYVAxMDVnYTlyU25rUWtpcz06U2d0M2ZaTzJVV1REVkNJS3Y5NUpWL3FId1VDcENpVjN5c3dKUFVGS28xMD0="></script>	</head>
	<body id="body-login">
		<noscript>
	<div id="nojavascript">
		<div>
			Bu uygulamanın düzgün çalışabilmesi için JavaScript gereklidir. Lütfen <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">JavaScript uygulamasını etkinleştirip</a> sayfayı yeniden yükleyin.		</div>
	</div>
</noscript>
				<div class="wrapper">
			<div class="v-align">
									<header role="banner">
						<div id="header">
							<div class="logo">
								<h1 class="hidden-visually">
									Disroot Cloud								</h1>
																	<img src="/apps/theming/image/logo?useSvg=1&amp;v=65"/>
															</div>
						</div>
					</header>
								<main>
					<div class="error error-wide">
	<h2>Sunucu İçinde Sorun</h2>
	<p>Sunucu isteğinizi yerine getiremedi.</p>
	<p>Bu sorun sürerse lütfen aşağıdaki teknik ayrıntıları sunucu yöneticisine iletin.</p>
	<p>Sunucu günlüğünden ayrıntılı bilgi alabilirsiniz.</p>

	<h3>Teknik ayrıntılar</h3>
	<ul>
		<li>Uzak Adres: 178.247.139.81</li>
		<li>İstek Kodu: XjsNJmB6g0H0bLHAQ2RG</li>
			</ul>

	</div>
				</main>
			</div>
		</div>
		<footer role="contentinfo">
			<p class="info">
				<a href="https://cloud.disroot.org" target="_blank" rel="noreferrer noopener" class="entity-name">Disroot Cloud</a> – Powered by Nextcloud<br/><a href="https://disroot.org/en/privacy_policy" class="legal" target="_blank" rel="noreferrer noopener">Kişisel gizliliğin korunması ilkesi</a> · <a href="https://state.disroot.org" class="legal" target="_blank" rel="noreferrer noopener">Service state</a>			</p>
		</footer>
	</body>
</html>

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:433)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:134)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:117)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:134)
	at android.os.Binder.execTransact(Binder.java:731)

```

**Comment by stefan-niedermann** [comment]
Please use the bug template and fill out all information.

![grafik](https://user-images.githubusercontent.com/4741199/72544901-6f2ab900-3888-11ea-8156-67f632bd23e4.png)

**Comment by oktay454** [comment]
Sorry. I don't know much because I don't use GitHub effectively.

**Comment by stefan-niedermann** [comment]
Your server returns `HTTP Status 500` which basically means "Something went wrong at the server side".

Please tell us at least:

**Server**
 - Nextcloud-Version: 
 - Nextcloud Notes-Version (server app): 
 - PHP-Version:

**Smartphone (please complete the following information):**
 - Device: [e.g. Samsung Galaxy S10]
 - Android-Version: [e.g. 8]

**Are you able to create / read notes with the web interface?**

Did you do any update (Nextcloud, Server app, Android app) or a fresh install of everything?

**Comment by oktay454** [comment]
Problem solved.
It's all a mistake from me.
I didn't update the security key after I changed my password.
Sorry again. = (

**Comment by stefan-niedermann** [comment]
Asolutely no problem :) Have fun with the app.
