### ISSUE TITLE
App crash on resume

### ISSUE THREAD

**Issue by ChrisB85** [stefan-niedermann/nextcloud-notes#690]
**Describe the bug**
Im using fresh install of this app.

**To Reproduce**
1. Open app
2. Close app using back button
3. Open app again
4. App crashes

**Expected behavior**
App should not crash

**Server**
 - Nextcloud Notes-Version (android app): 2.4.6
 - Nextcloud-Version: 18.0.0 (using Docker)
 - Nextcloud Notes-Version (server app): 3.1.1
 - PHP-Version: 7.3.13

**Smartphone (please complete the following information):**
 - Device: Pocophone F1
 - Android-Version: 9

**Stacktrace**

```
App Version: 2.4.6
App Version Code: 69
Files App Version Code: 30100090

---

OS Version: 4.9.112-perf-g526fc33(V11.0.5.0.PEJMIXM)
OS API Level: 28
Device: beryllium
Model (and Product): POCOPHONE F1 (beryllium)

---

java.lang.RuntimeException: Unable to resume activity {it.niedermann.owncloud.notes/it.niedermann.owncloud.notes.android.activity.NotesListViewActivity}: java.lang.IllegalArgumentException: Service not registered: com.nextcloud.android.sso.api.AidlNetworkRequest$1@219747e
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3824)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3856)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6806)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: java.lang.IllegalArgumentException: Service not registered: com.nextcloud.android.sso.api.AidlNetworkRequest$1@219747e
	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1570)
	at android.app.ContextImpl.unbindService(ContextImpl.java:1702)
	at android.content.ContextWrapper.unbindService(ContextWrapper.java:727)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.stop(AidlNetworkRequest.java:109)
	at com.nextcloud.android.sso.api.NextcloudAPI.stop(NextcloudAPI.java:80)
	at it.niedermann.owncloud.notes.persistence.NotesClient.updateAccount(NotesClient.java:99)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper.updateAccount(NoteServerSyncHelper.java:141)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.selectAccount(NotesListViewActivity.java:274)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.onResume(NotesListViewActivity.java:228)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1413)
	at android.app.Activity.performResume(Activity.java:7400)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3816)
	... 11 more

```

**Comment by stefan-niedermann** [comment]
Thank you for reporting. This issue has been fixed with version `2.4.8`. Please reopen, if the issue still occurs after upgrading :)

**Comment by ChrisB85** [comment]
OK, thanks. I'm using latest version from F-Droid repo. When update will be available?

**Comment by stefan-niedermann** [comment]
F-Droid already has successfully built the version `2.4.8`, it will come with their next Rrepository update (i guess in 1-2 days).

You can watch the state here: https://f-droid.org/wiki/index.php?title=Special:RecentChanges&hidebots=0&days=30&limit=500

The next time when an entry starting with `deploy` appears, the update should available on your phone.

**Comment by stefan-niedermann** [comment]
Btw `2.4.8` is available on F-Droid since yesterday 🚀
