### ISSUE TITLE
NextcloudApiNotResponding

### ISSUE THREAD

**Issue by amichuda** [stefan-niedermann/nextcloud-notes#710]
**Describe the bug**
Notes app synchronizes, but stops syncing after some amount of time. Only after deleting and re-adding account does sync work, but all new notes created locally are deleted (as expected).

**To Reproduce**
1. Connect nextcloud account
2. Sync notes, old and new
3. Wait a week
4. Sync no longer works

**Expected behavior**
It would always be about to sync

**Server**
 - Nextcloud-Version: 18
 - Nextcloud Notes-Version (server app): latest
 - PHP-Version: 4.7

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.9.0
 - F-Droid or Play Store: play store
 - Device: OnePlus 5t
 - Android-Version: 9

Stacktrace:

```
App Version: 2.9.0
App Version Code: 77
Files App Version Code: 30100090

---

OS Version: 4.4.153-perf+(1912311102)
OS API Level: 28
Device: OnePlus5T
Model (and Product): ONEPLUS A5010 (OnePlus5T)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:128)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:267)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:148)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:194)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:125)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:363)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:291)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:262)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by stefan-niedermann** [comment]
Thank you for reporting this bug.

- Did you see any error message? Which one?
- Is your Nextcloud files app using any password-protection like PIN or device credentials?
- Are you able to grab a LogCat when this happens? (e. g. using [LogCat-Reader](https://play.google.com/store/apps/details?id=com.dp.logcatapp)

Regards

**Comment by amichuda** [comment]
In terms of pin/device credentials, what do you mean? Do you mean SSO or encryption?

**Comment by stefan-niedermann** [comment]
No, i meant if your files app is protected (go to settings in your files app and check "App-PIN" (First entry in "Details" section). What is selected there?

**Comment by amichuda** [comment]
Thank you for the clarification! No I don't have either of those checked.

**Comment by stefan-niedermann** [comment]
Regarding "Step 3": "Wait a week":

- Did Notes or the Files app receive an upfate within this week?
- Didn't you open both apps for a week or did you normally use the apps? Please be as detailled as possible here: How often did you use the Notes and the files app within this week?
- Are you using the News or Deck app on your smartphone too?

I guess this bug is from Single-Sign-On (see https://github.com/nextcloud/Android-SingleSignOn/issues/162).

Thank you for your information

**Comment by amichuda** [comment]
Hi,

Notes or Files did not receive an update. This has been a recurring problem for a few weeks now.

I did not open the apps for a while in between sessions. I think I open them every 3 or four days.

I am using the news app and I recently had the same problem there as well, although not recently (after also doing the same procedure where I re-add my account).

So should I disable SSO and see if that changes anything?

**Comment by amichuda** [comment]
After having this happen again, I've found that sync works after opening the files app, force closing Notes and then re-opening. Is this intended behavior?

**Comment by stefan-niedermann** [comment]
> So should I disable SSO and see if that changes anything?

SSO can't be disabled in the Notes app.

> Is this intended behavior?

No, of course not. This is a known issue of the SSO which is tracked here: https://github.com/nextcloud/Android-SingleSignOn/issues/162

There are some ideas to retry the connection a few times, but nothing concrete yet unfortunately.

**Comment by stefan-niedermann** [comment]
Please reopen if this issue still occurs with `v2.10.3`.

**Comment by zingmars** [comment]
How long will it take for it to appear on f-droid?

**Comment by stefan-niedermann** [comment]
Don't know, depends on F-Droid's build servers.

I guess a few days or max. a week 🤷🏻‍♂️

**Comment by FredMa01** [comment]
Hello
I have still a problem with the new version  :
App Version: 2.10.3
App Version Code: 81
Files App Version Code: 30100190

---

OS Version: 4.9.148(9.1.0.155C432)
OS API Level: 28
Device: HWLLD-H
Model (and Product): LLD-L31 (LLD-L31)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: L'application Nexcloud Files ne répond pas. Veuillez signaler ce problème.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:163)
	at it.niedermann.owncloud.notes.persistence.NotesClient.putNote(NotesClient.java:107)
	at it.niedermann.owncloud.notes.persistence.NotesClient.editNote(NotesClient.java:122)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:318)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:284)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)
com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: L'application Nexcloud Files ne répond pas. Veuillez signaler ce problème.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:163)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:98)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:413)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:320)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:284)
	at android.os.AsyncTask$2.call(AsyncTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
	at java.util.concurrent.ThreadPoolExecutor.processTask(ThreadPoolExecutor.java:1187)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:784)

```

**Comment by stefan-niedermann** [comment]
Yes, noticed it, unfortunately. 😓

We are taking care about it in https://github.com/stefan-niedermann/nextcloud-notes/issues/752

**Comment by smilearric** [comment]
@stefan-niedermann might be fixed since 2.10.3. Thanx!

**Comment by HiperFall** [comment]
I have the same issue, how can I fix it? I've tried reinstalling both apps.

```
App Version: 2.16.3
App Version Code: 2016003
App Flavor: fdroid

Files App Version Code: 30120090

---

OS Version: 3.10.72+(1521441980)
OS API Level: 22
Device: NX541J
Manufacturer: nubia
Model (and Product): NX541J (NX541J)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Nextcloud files app api is not responding. Please report this issue.
 at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
 at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
 at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
 at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
 at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
 at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
 at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$20$MainActivity(MainActivity.java:791)
 at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$4HeEjJCK6xYZ8GdVmxdXI3hCjBw.run(lambda)
 at java.lang.Thread.run(Thread.java:818)
```

**Comment by stefan-niedermann** [comment]
Unfortunately i can't do anything but redirecting you to https://github.com/nextcloud/Android-SingleSignOn/issues/162

Have you disabled all battery optimizations for both apps?

**Comment by HiperFall** [comment]
> Have you disabled all battery optimizations for both apps?
Yes, I tried it and it worked. Thanks!

**Comment by stefan-niedermann** [comment]
@HiperFall we are trying to hunt down this nasty bug. Since battery optimization solved this issue:

Have you disabled it for

- both apps or¹
- only for Notes
- only for the main app?

Thank you in advance :slightly_smiling_face: 

¹ In this case: Would you mind to try disabling it only for one of the two apps and report us if the issue appears again? (Though it might take some time for the optimization system to react again and drop the connection)

**Comment by HiperFall** [comment]
@stefan-niedermann 

It can work if I disable optimizations for the main NextCloud and not for Notes. It's important if the battery optimizatons are disabled for the main app.
