### ISSUE TITLE
API Level 15 cannot use ?android: attributes

### ISSUE THREAD

**Issue by ilippert** [stefan-niedermann/nextcloud-notes#730]
When starting Notes, having logged in with the nextcloud app's log in details, I am shown

the details below (rather than the notes)

```
App Version: 2.10.1
App Version Code: 79
Files App Version Code: 30090290

---

OS Version: 3.0.8(C167B003)
OS API Level: 15
Device: hws7300u
Model (and Product): HUAWEI MediaPad (MediaPad)

---

android.view.InflateException: Binary XML file line #109: Error inflating class TextView
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:697)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:739)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:742)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:396)
	at it.niedermann.owncloud.notes.model.ItemAdapter.onCreateViewHolder(ItemAdapter.java:79)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
	at android.view.View.measure(View.java:12758)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4718)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at android.view.View.measure(View.java:12758)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:641)
	at android.view.View.measure(View.java:12758)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4718)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
	at android.view.View.measure(View.java:12758)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4718)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:833)
	at android.view.View.measure(View.java:12758)
	at androidx.drawerlayout.widget.DrawerLayout.onMeasure(DrawerLayout.java:1119)
	at android.view.View.measure(View.java:12758)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4718)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:143)
	at android.view.View.measure(View.java:12758)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4718)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at android.view.View.measure(View.java:12758)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4718)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at android.view.View.measure(View.java:12758)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4718)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1369)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:660)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:553)
	at android.view.View.measure(View.java:12758)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4718)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:293)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2094)
	at android.view.View.measure(View.java:12758)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1064)
	at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2445)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4424)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: android.content.res.Resources$NotFoundException: File res/drawable-xhdpi-v4/border.xml from drawable resource ID #0x7f080060
	at android.content.res.Resources.loadDrawable(Resources.java:1925)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:601)
	at android.view.View.<init>(View.java:2793)
	at android.widget.TextView.<init>(TextView.java:459)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:99)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:95)
	at androidx.appcompat.app.AppCompatViewInflater.createTextView(AppCompatViewInflater.java:182)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:103)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:668)
	... 63 more
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
	at android.content.res.TypedArray.getColor(TypedArray.java:326)
	at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:783)
	at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:867)
	at android.graphics.drawable.Drawable.createFromXml(Drawable.java:804)
	at android.content.res.Resources.loadDrawable(Resources.java:1922)
	... 73 more

```

**Comment by stefan-niedermann** [comment]
Can you specify since which version this happens? what was the oldest known version that worked?

**Comment by ilippert** [comment]
Sorry, cannot specify because: I received an old tablet, reset to factory settings and installed this today the first time.

**Comment by ilippert** [comment]
of course, i would understand if this is not high priority - given that the android version is very outdated...

**Comment by stefan-niedermann** [comment]
Will be fixed in the next released version.
