### ISSUE TITLE
Synchronisations Fehler 

### ISSUE THREAD

**Issue by weinic** [stefan-niedermann/nextcloud-notes#763]
Die APP bring mir dauernd einen Syncronisarions Fehler.
Ich weiß aber nicht warum...

```
App Version: 2.10.3
App Version Code: 81
Files App Version Code: 30110052

---

OS Version: 3.4.113-lineageos-g1bb760f(a9639c51c9)
OS API Level: 25
Device: hlte
Model (and Product): SM-N9005 (lineage_hlte)

---

com.nextcloud.android.sso.exceptions.TokenMismatchException: Der Authentifizierungs-Token stimmt nicht überein oder dem Paketnamen fehlt die Berechtigung für diese Aktion
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:163)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:98)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:413)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:320)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:284)
	at android.os.AsyncTask$2.call(AsyncTask.java:305)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

```

**Comment by stefan-niedermann** [comment]
Hallo,

könnten Sie bitte versuchen, unter den Abdroid-Einstellungen sowohl bei der Nextcloud-App als auch bei der Notes-App unter "Speicher" den Punkt "Speicher löschen" auswählen und Ihren Account im Anschluss erneut hinzufügen?

Achtung: Nicht-synchronisierte Notizen werden dabei verloren gehen, diese am Besten vorher per E-Mail oder anderweitig sichern.

Verwenden Sie die App aus dem Play Store oder von F-Droid?

Grüße

**Comment by weinic** [comment]
Also das neu einrichten der Notes APP hat funktioniert,
 (Speicher löschen in der Android APP Verwaltung)
Die Nextcloud APP habe ich jetzt nicht zurück gesetzt. Als login Methode habe ich den Automatischen login mit den Anmeldedaten der Nextcloud APP verwendet.

**Comment by stefan-niedermann** [comment]
Alles klar, danke für die Info. Gut, dass es bei Ihnen jetzt soweit wieder funktioniert.

Wissen Sie noch, was genau Sie gemacht haben, bevor das Problem auftrat? Haben Sie eine der beiden Apps geupdated oder so etwas in der Art?

**Comment by weinic** [comment]
Ich habe auch noch die Nextcloud Dev. APP istalliert, diese habe ich heute geupdatet.
Die Anmeldedaten sind aber nicht von der Dev. APP und diese ist auch mit einem anderen Benutzerkonto verbunden.
Die Nextcloud APP und die Notes APP wurden schon vor längerer Zeit geupdatet.
Was ich noch vergessen hatte, die Notes APP ist aus dem F-droid store

**Comment by stefan-niedermann** [comment]
Hmm. Ich werde das Verhalten mit der Dev-App auch nochmal prüfen, danke für den Hinweis.

**Comment by moedn** [comment]
Hi, ich hatte 'nen ähnlichen Fehler; ich schreib's aber aus Doku-Gründen mal auf Englisch :)

---

Same issue here, see copied log below. Unfortunately I don't have much details to share, hope the following helps:

- I'm using the official version deployed on F-Droid (no dev app variant or so)
- I perform ~weekly updates; issue occurred first around mid-January; occurred spontaneously to me (_maybe_ after an update, but can't remember) 
- no changes on the server side when the issue occurred (confirmed)
- other nextcloud-related apps and services showed no error (Nextloud App, synced calendars/tasks etc.), so with high probability the issue was caused inside the notes app
- I'm running Lineage 18.1 on a Pixel 4 with OpenGapps installed (nano package)

I didn't (as suggested above) clear all data in the nextcloud app and the notes app; just reconnecting the account solved the issue for me (so deleting the synchronisation in the settings and re-adding it afterwards; this step will delete all unsynced changes of course)

---

log (when the error was still there):

```
java.lang.Exception: com.nextcloud.android.sso.exceptions.TokenMismatchException: Provided authentication token does not match or package name is not permitted to perform this action
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pushLocalChanges(NotesServerSyncTask.java:158)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:94)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)


java.lang.RuntimeException: com.nextcloud.android.sso.exceptions.TokenMismatchException: Provided authentication token does not match or package name is not permitted to perform this action
 at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
 at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
 at io.reactivex.Maybe.blockingGet(Maybe.java:2321)
 at io.reactivex.Observable.blockingSingle(Observable.java:5381)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.pullRemoteChanges(NotesServerSyncTask.java:219)
 at it.niedermann.owncloud.notes.persistence.NotesServerSyncTask.run(NotesServerSyncTask.java:96)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
 at java.util.concurrent.FutureTask.run(FutureTask.java:266)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
 at java.lang.Thread.run(Thread.java:923)
Caused by: com.nextcloud.android.sso.exceptions.TokenMismatchException: Provided authentication token does not match or package name is not permitted to perform this action
 at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:188)
 at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:199)
 at com.nextcloud.android.sso.api.NextcloudAPI.lambda$performRequestObservableV2$1$com-nextcloud-android-sso-api-NextcloudAPI(NextcloudAPI.java:129)
 at com.nextcloud.android.sso.api.NextcloudAPI$$ExternalSyntheticLambda2.subscribe(Unknown Source:6)
 at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
 at io.reactivex.Observable.subscribe(Observable.java:12284)
 at io.reactivex.internal.operators.observable.ObservableSingleMaybe.subscribeActual(ObservableSingleMaybe.java:31)
 at io.reactivex.Maybe.subscribe(Maybe.java:4290)
 at io.reactivex.Maybe.blockingGet(Maybe.java:2320)
 ... 8 more
```

**Comment by mogasuisse** [comment]
same issue, also with a pixel 4...

**Comment by stefan-niedermann** [comment]
@mogasuisse there are at least three different stacktraces indicating three different errors in this thread. Please read [our FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error) and open a new issue filling the complete template and add details about your environment in case you didn't find an answer there.

**Comment by mogasuisse** [comment]
sure, I was just pointing out the pixel 4. Two other users of the instance have their note app syncing.

**Comment by mogasuisse** [comment]
> 


sure, I was just pointing out the pixel 4. Two other users of the instance have their note app syncing.

**Comment by sphenotux** [comment]
Same here. V3.7.1 fdroid. No sync. "Backup" of local notes via email. Deleted cache and files via Android settings. Restarted Notes App. Sync works again (easy to check via NC app).
