### ISSUE TITLE
App crash when selected

### ISSUE THREAD

**Issue by Valdnet** [stefan-niedermann/nextcloud-notes#776]
**Describe the bug**
```
App Version: 2.11.3
App Version Code: 2011003
Files App Version Code: 30110090

---

java.lang.StringIndexOutOfBoundsException
	at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:62)
	at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:1205)
	at it.niedermann.owncloud.notes.util.format.ContextBasedFormattingCallback.onPrepareActionMode(ContextBasedFormattingCallback.java:48)
	at android.widget.Editor$TextActionModeCallback.onPrepareActionMode(Editor.java:4121)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onPrepareActionMode(DecorView.java:2932)
	at com.android.internal.view.FloatingActionMode.invalidate(FloatingActionMode.java:145)
	at com.android.internal.policy.DecorView.setHandledFloatingActionMode(DecorView.java:2191)
	at com.android.internal.policy.DecorView.setHandledActionMode(DecorView.java:2025)
	at com.android.internal.policy.DecorView.startActionMode(DecorView.java:1072)
	at com.android.internal.policy.DecorView.startActionModeForChild(DecorView.java:1027)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1015)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1015)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1015)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1015)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1015)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1015)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1015)
	at android.view.ViewGroup.startActionModeForChild(ViewGroup.java:1015)
	at android.view.View.startActionMode(View.java:7393)
	at android.widget.Editor.startInsertionActionMode(Editor.java:2178)
	at android.widget.Editor$InsertionHandleView.onTouchEvent(Editor.java:5382)
	at android.view.View.dispatchTouchEvent(View.java:13500)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3073)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2766)
	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2621)
	at android.view.View.dispatchPointerEvent(View.java:13763)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5819)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5614)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5058)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5111)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5077)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5234)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5085)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5291)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5058)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5111)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5077)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5085)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5058)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7949)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7900)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7854)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8139)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:233)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:363)
	at android.os.Looper.loop(Looper.java:173)
	at android.app.ActivityThread.main(ActivityThread.java:8147)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

```

**To Reproduce**

1. Open a note with text.
2. In the word, mark the letters to correct, for example: Te | st.
3. Tap again on the check mark.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app):  2.11.3
 - Android-Version: [e.g. 8] 10

**Comment by stefan-niedermann** [comment]
@Valdnet i have a few questions:

- Are you using the Play Store or F-Droid version?
- Are you able to reproduce this issue with a minimal note you can share here?
- Can you take a video of what exactly you are doing? (Because i can't reproduce the crash)

In the meantime i added a catch until we know the source of this issue, so the app at least won't crash. The fix will come with `v2.11.7`, unfortunately it will take some time until the update appears because, you know, corona and stuff.

Thank you for reporting.

**Comment by Valdnet** [comment]
I'm using F-Droid.

Video: [crash.zip](https://github.com/stefan-niedermann/nextcloud-notes/files/4419333/crash.zip)

**Comment by stefan-niedermann** [comment]
Thank you, i was able to reproduce this issue now and i think i'm able to fix the root cause (and not only prevent the crash).
