### ISSUE TITLE
Synchronization failed

### ISSUE THREAD

**Issue by dolamroth69** [stefan-niedermann/nextcloud-notes#787]
**Describe the bug**
```
App Version: 2.11.7
App Version Code: 2011007
App Flavor: fdroid

Files App Version Code: 30110090

---

OS Version: 4.9.112-perf+(cd8e0)
OS API Level: 28
Device: channel
Model (and Product): moto g(7) play (channel_reteu)

---

com.nextcloud.android.sso.exceptions.TokenMismatchException: Der Authentifizierungs-Token stimmt nicht überein oder dem Paketnamen fehlt die Berechtigung für diese Aktion
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:162)
	at it.niedermann.owncloud.notes.persistence.NotesClient.putNote(NotesClient.java:107)
	at it.niedermann.owncloud.notes.persistence.NotesClient.editNote(NotesClient.java:121)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:383)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:356)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:320)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
com.nextcloud.android.sso.exceptions.TokenMismatchException: Der Authentifizierungs-Token stimmt nicht überein oder dem Paketnamen fehlt die Berechtigung für diese Aktion
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:162)
	at it.niedermann.owncloud.notes.persistence.NotesClient.putNote(NotesClient.java:107)
	at it.niedermann.owncloud.notes.persistence.NotesClient.createNote(NotesClient.java:117)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:394)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:356)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:320)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
com.nextcloud.android.sso.exceptions.TokenMismatchException: Der Authentifizierungs-Token stimmt nicht überein oder dem Paketnamen fehlt die Berechtigung für diese Aktion
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:162)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:98)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:446)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:358)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:320)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

```

**To Reproduce**
1. Opened Notizen
2. Created New note by selecting + button
3. Above pasted error report

**Expected behavior**
Sync should happen smoothly in the background

**Screenshots**
![Screenshot_20200414-114304](https://user-images.githubusercontent.com/24807347/79210461-2bbef700-7e45-11ea-8d65-a50460129445.png)

**Server**
 - Nextcloud-Version: 
 - Nextcloud Notes-Version (server app): 
 - PHP-Version: 

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Device: [e.g. Samsung Galaxy S10]
 - Android-Version: [e.g. 8]

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Thank you for the hint, we are aware of this issue but weren't able to finde the root cause yet.

You can clear the storage of the Nextcloud Android app **and** the Nextcloud Notes Android app and readd your account. This will solve the issue.

**Comment by stefan-niedermann** [comment]
Do you remember what exactly you did **right before** this error happened? Updated the Nextcloud Android App or the Nextcloud Notes Android App? Fresh install of Nextcloud Notes Android App? Anything else?

**Comment by dolamroth69** [comment]
No updating of the apps, just working inside the app, adding a note.
--
T. +49 171 4115114
LinkedIn <https://www.linkedin.com/in/michaelmiener> | Xing <https://www.xing.com/profile/Michael_Miener>

**Comment by stefan-niedermann** [comment]
Did clearing the storage fix the issue for you?

**Comment by marcatsmci** [comment]
Same for me ;-(
Removing Nextcloud & Notes apps, reinstalling : no way

**Comment by stefan-niedermann** [comment]
@marcatsmci do you also have the app from F-Droid? I will soon publish an update for F-Droid where the problem (hopefully) will be solved. Play Store will take some more time.

**Comment by marcatsmci** [comment]
From Play store. I give a try from F-Droid...

**Comment by stefan-niedermann** [comment]
No.

1. I just released it for F-Droid and Play Store Beta channel today. It will take a few days to build. Play Store will take up to 10 days (they say it's because of corona)
2. `0.24.3` is **VERY** outdated. Please update you F-Droid cache, the current released version on F-Droid is `2.11.8`

The fix (hopefully) will be in `2.11.10`.

**Comment by marcatsmci** [comment]
Thanks, I'll wait a little bit...

**Comment by stefan-niedermann** [comment]
You can try the dev build: https://github.com/stefan-niedermann/nextcloud-notes/suites/602835376/artifacts/4485981 but attention: It will not receive updates and has no optimized code. But for giving feedback it will be sufficient.

If it does not work, please give me more information about:

1. What exactly is the error message? Is it also "TokenMismatchException"? If not please open a separate issue
2. What version of the main Nextcloud app are you using?

**Comment by marcatsmci** [comment]
Hello,
ok with the dev build ;-)

**Comment by marcatsmci** [comment]
The error is __TokenMismatchException__

NC 18.0.3

**Comment by stefan-niedermann** [comment]
> ok with the dev build ;-)

Sounds good! I will close this issue then. Just reopen it (or open a new) if this error appears again with the released version `2.11.10`. :)

**Comment by Isaac-Graham** [comment]
Hey guy, this also happens in my device. The log is shown as follows:

```
App Version: 2.11.8
App Version Code: 2011008
App Flavor: fdroid

Files App Version Code: 30110090

---

OS Version: 4.14.116(10.1.0.121C00)
OS API Level: 29
Device: HWVOG
Manufacturer: HUAWEI
Model (and Product): VOG-AL00 (VOG-AL00)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP 请求失败，HTTP 错误代码：302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:162)
	at it.niedermann.owncloud.notes.persistence.NotesClient.getNotes(NotesClient.java:98)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:446)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:358)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:320)
	at android.os.AsyncTask$3.call(AsyncTask.java:389)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:438)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:135)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:118)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:134)
	at android.os.Binder.execTransactInternal(Binder.java:1028)
	at android.os.Binder.execTransact(Binder.java:1001)

```

Hope this would be helpful.

**Comment by stefan-niedermann** [comment]
Hi @Isaac-Graham this is something different. There is something wrong with the setup of your server. You can contact me via info@niedermann.it so we can try to solve the issue, but there is nothing i can do on the app-side. Please create a test account and share the credentials via E-Mail.
