### ISSUE TITLE
Synchronization failed

### ISSUE THREAD

**Issue by DeerMaximum** [stefan-niedermann/nextcloud-notes#820]
**Describe the bug**
Notes are not synchronized

**To Reproduce**
1. Opened App
2. Created/Edit Note

**Expected behavior**
Sync should happen smoothly in the background

**Server**
 - Nextcloud-Version: 17.0.6
 - Nextcloud Notes-Version (server app):  3.3.0
 - PHP-Version: 7.3.16

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.11.12
 - F-Droid or Play Store: F-Droid
 - Device: SHIFT6m
 - Android-Version: 8.0.0

**Stacktrace**

```
App Version: 2.11.12
App Version Code: 2011012
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 3.18.60-SHIFT-00362-ge78e9d8616fb(1566905523)
OS API Level: 26
Device: SHIFT6m
Manufacturer: SHIFT
Model (and Product): SHIFT6m (SHIFT6m_EEA)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP-Anfrage ist fehlgeschlagen mit HTTP-Statuscode: 500
  at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
  at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
  at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:163)
  at it.niedermann.owncloud.notes.persistence.NotesClient.putNote(NotesClient.java:108)
  at it.niedermann.owncloud.notes.persistence.NotesClient.editNote(NotesClient.java:122)
  at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:369)
  at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:343)
  at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
  at android.os.AsyncTask$2.call(AsyncTask.java:333)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
  at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IllegalStateException: []

  at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:438)
  at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:135)
  at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:118)
  at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:134)
  at android.os.Binder.execTransact(Binder.java:674)

```

**Comment by stefan-niedermann** [comment]
Have a look at your server logs, the HTTP status `500` says, that something went wrong at the server.

**Comment by korelstar** [comment]
According to the logs, the server return the HTTP status code 500, which means "Internal Server Error". Please have look at your server's nextcloud.log. There, you should find related entries about the problem.

**Comment by stefan-niedermann** [comment]
@DeerMaximum maybe you can leave a comment here, what the problem was? This might be helpful for other users stumbling over the same issue :slightly_smiling_face:
