### ISSUE TITLE
App crashes on start

### ISSUE THREAD

**Issue by tikeyknax** [stefan-niedermann/nextcloud-notes#829]
**Android version:** 10

**Device**: Samsung Galaxy S9 SM-G960F

**System language**: German

**App version:** 2.11.13

**App source:** Google Play Store

**Steps to reproduce:**
  1. open the app
 

The app crashes when trying to open it with the following exception:

```
App Version: 2.11.13
App Version Code: 2011013
App Flavor: play

Files App Version Code: 30110190

---

OS Version: 4.9.118-18339707(G960FXXU8DTC5)
OS API Level: 29
Device: starlte
Manufacturer: samsung
Model (and Product): SM-G960F (starltexx)

---

java.lang.RuntimeException: Unable to start activity ComponentInfo{it.niedermann.owncloud.notes/it.niedermann.owncloud.notes.android.activity.NotesListViewActivity}: android.database.sqlite.SQLiteException: duplicate column name: API_VERSION (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE ACCOUNTS ADD COLUMN API_VERSION TEXT
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3488)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3635)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2175)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7857)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
Caused by: android.database.sqlite.SQLiteException: duplicate column name: API_VERSION (code 1 SQLITE_ERROR[1]): , while compiling: ALTER TABLE ACCOUNTS ADD COLUMN API_VERSION TEXT
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1372)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:811)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:33)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2321)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2249)
	at it.niedermann.owncloud.notes.persistence.AbstractNotesDatabase.onUpgrade(AbstractNotesDatabase.java:272)
	at it.niedermann.owncloud.notes.persistence.NotesDatabase.onUpgrade(NotesDatabase.java:52)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:493)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:415)
	at it.niedermann.owncloud.notes.persistence.NotesDatabase.getAccounts(NotesDatabase.java:674)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.setupHeader(NotesListViewActivity.java:238)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.onCreate(NotesListViewActivity.java:153)
	at android.app.Activity.performCreate(Activity.java:7955)
	at android.app.Activity.performCreate(Activity.java:7944)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3463)
	... 11 more

**Comment by stefan-niedermann** [comment]
Hello, it seems like you upgraded from a version < 2.0.0 to the current version.

Unfortunately there was a bug in `2.11.x` which breaks the local database after the upgrade. The bug is known and fixed in the meantime (starting with version `2.12.0`).

You can fix it by deleting the storage of the app (Android settings -> Apps -> Nextcloud Notes -> Storage -> Clear storage) and then reimport your account - sorry, that's the only way to get rid of the error message.

Could you please tell me whether or not this worked for you?

Regards

**Comment by tikeyknax** [comment]
Hey, thanks for the quick response. It worked and re-adding the account was super easy as well.
Cheers

**Comment by stefan-niedermann** [comment]
You're welcome, have fun with the app 🙂
