### ISSUE TITLE
Sometimes error appears when editing note via note widget

### ISSUE THREAD

**Issue by jancborchardt** [stefan-niedermann/nextcloud-notes#834]
Not entirely sure how to reproduce this, but it seems to often appear when I edit the note I have permanently shown via the widget.

Getting this error – I will try and see when and how it happens again:
```
App Version: 2.12.0
App Version Code: 2012000
App Flavor: fdroid

Files App Version Code: com.nextcloud.client

---

OS Version: 3.4.0-perf-g284400a(de8920e892)
OS API Level: 27
Device: FP2
Manufacturer: Fairphone
Model (and Product): FP2 (FP2)

---

java.lang.NullPointerException: Attempt to read from field 'com.yydcdut.markdown.MarkdownEditText it.niedermann.owncloud.notes.databinding.FragmentNoteEditBinding.editContent' on a null object reference
	at it.niedermann.owncloud.notes.android.fragment.NoteEditFragment.getContent(NoteEditFragment.java:203)
	at it.niedermann.owncloud.notes.android.fragment.BaseNoteFragment.saveNote(BaseNoteFragment.java:265)
	at it.niedermann.owncloud.notes.android.fragment.NoteEditFragment.saveNote(NoteEditFragment.java:208)
	at it.niedermann.owncloud.notes.android.fragment.BaseNoteFragment.onSaveInstanceState(BaseNoteFragment.java:140)
	at it.niedermann.owncloud.notes.android.fragment.SearchableBaseNoteFragment.onSaveInstanceState(SearchableBaseNoteFragment.java:178)
	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:2863)
	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:434)
	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:400)
	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:143)
	at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2386)
	at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
	at androidx.fragment.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:512)
	at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:533)
	at android.app.Activity.performSaveInstanceState(Activity.java:1496)
	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1386)
	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4721)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4025)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4084)
	at android.app.ActivityThread.-wrap24(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1622)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by stefan-niedermann** [comment]
- Does it happen when opening the note from the app or from the widget?
- Does it happen directly after opening the note, after typing something (and wait for the autosave) or does it happen when you close the note?

**Comment by jancborchardt** [comment]
Ever since you asked for these clarification points, I didn’t encounter the issue again. ;) Am looking out for it and will try and analyze.

As far as I can remember from the occurences, my usual workflow when this happened was the following:
1. Open a note from the widget
2. Type down something I don’t want to forget
3. Lock the phone again (press power button)
4. Some time later, unlock it again → see the error

**Comment by stefan-niedermann** [comment]
> Ever since you asked for these clarification points, I didn’t encounter the issue again. ;) 

Any news here? Have you encountered this issue in the last 7 months again? If not, i propose to close this issue until we see it again and can get more information about it.
