### ISSUE TITLE
Cannot connect anymore

### ISSUE THREAD

**Issue by getwet** [stefan-niedermann/nextcloud-notes#839]
Hi,

I cannot connect since the update on fdroid a view days ago.
The logs shows:

```
App Version: 2.12.1
App Version Code: 2012001
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 3.10.108-g187d27c(b0d22b9dab)
OS API Level: 28
Device: gts210vewifi
Manufacturer: samsung
Model (and Product): SM-T813 (gts210vewifixx)

---

java.lang.RuntimeException: Parcelable encountered IOException writing serializable object (name = com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException)
	at android.os.Parcel.writeSerializable(Parcel.java:1714)
	at android.os.Parcel.writeValue(Parcel.java:1662)
	at android.os.Parcel.writeList(Parcel.java:963)
	at android.os.Parcel.writeValue(Parcel.java:1611)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
	at android.os.Bundle.writeToParcel(Bundle.java:1233)
	at android.os.Parcel.writeBundle(Parcel.java:915)
	at androidx.fragment.app.FragmentState.writeToParcel(FragmentState.java:125)
	at android.os.Parcel.writeTypedObject(Parcel.java:1516)
	at android.os.Parcel.writeTypedList(Parcel.java:1395)
	at android.os.Parcel.writeTypedList(Parcel.java:1380)
	at androidx.fragment.app.FragmentManagerState.writeToParcel(FragmentManagerState.java:51)
	at android.os.Parcel.writeParcelable(Parcel.java:1683)
	at android.os.Parcel.writeValue(Parcel.java:1589)
	at android.os.Parcel.writeArrayMapInternal(Parcel.java:875)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1579)
	at android.os.Bundle.writeToParcel(Bundle.java:1233)
	at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4010)
	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.io.NotSerializableException: com.nextcloud.android.sso.model.ExceptionMessage
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
	at android.os.Parcel.writeSerializable(Parcel.java:1709)
	... 26 more

```

This was from my tablet, but I've got the same error on my smartphone.
I did allready the mentioned solutions like wipe the data and reconnect, without success.

**Comment by stefan-niedermann** [comment]
Have you tried to wipe the data from both, thr Notes app **and** the Nextcloud app?

**Comment by getwet** [comment]
No, only the notes app. But I'll try to wipe also nextcloud app.

**Comment by getwet** [comment]
Ok, has been worked!
Top, many thanks for your fast solution.

**Comment by stefan-niedermann** [comment]
Sorry for the circumstates and thank you for the bug report :)
