### ISSUE TITLE
In-Note search crashes on Android 4.4

### ISSUE THREAD

**Issue by stefan-niedermann** [stefan-niedermann/nextcloud-notes#847]
```
App Version: 2.12.0 - 2.12.2 (and maybe others)
App Version Code: 2012000
App Flavor: dev

Files App Version Code: 30110090

---

OS Version: 3.10.0+(4174703)
OS API Level: 19
Device: generic_x86
Manufacturer: unknown
Model (and Product): Android SDK built for x86 (sdk_x86)

---

java.lang.IllegalArgumentException: radius must be > 0
	at android.graphics.RadialGradient.<init>(RadialGradient.java:53)
	at com.google.android.material.shadow.ShadowRenderer.drawCornerShadow(ShadowRenderer.java:160)
	at com.google.android.material.shape.ShapePath$ArcShadowOperation.draw(ShapePath.java:385)
	at com.google.android.material.shape.ShapePath$1.draw(ShapePath.java:226)
	at com.google.android.material.shape.ShapePath$ShadowCompatOperation.draw(ShapePath.java:323)
	at com.google.android.material.shape.MaterialShapeDrawable.drawCompatShadow(MaterialShapeDrawable.java:1055)
	at com.google.android.material.shape.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:958)
	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java:349)
	at android.graphics.drawable.InsetDrawable.draw(InsetDrawable.java:158)
	at android.view.View.draw(View.java:14450)
	at android.view.View.draw(View.java:14350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1277)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
	at android.view.View.draw(View.java:14348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
	at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.java:235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
	at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.java:223)
	at android.view.View.draw(View.java:14348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
	at android.view.View.draw(View.java:14348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
	at android.view.View.draw(View.java:14468)
	at android.widget.FrameLayout.draw(FrameLayout.java:472)
	at android.view.View.draw(View.java:14350)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
	at android.view.View.draw(View.java:14348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
	at android.view.View.draw(View.java:14348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
	at android.view.View.draw(View.java:14348)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
	at android.view.View.draw(View.java:14468)
	at android.widget.FrameLayout.draw(FrameLayout.java:472)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2326)
	at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2496)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2409)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1883)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:544)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
	at dalvik.system.NativeStart.main(Native Method)

```

**Comment by JenniferJohnson89** [comment]
I noticed that there is a similar problem at https://github.com/material-components/material-components-android. Perhaps we can refer to https://github.com/material-components/material-components-android/issues/937 to find more context about the bug (e.g. the cause of the bug, or related library version, or their steps to reproduce). 
Or maybe this can help us find the faulty lines and we can also refer to the https://github.com/material-components/material-components-android/commit/26fc10cfc99c9ac3b7a4747f2c80e6a48a6bec5f for the bug?

**Comment by JenniferJohnson89** [comment]
I tried https://github.com/material-components/material-components-android/commit/26fc10cfc99c9ac3b7a4747f2c80e6a48a6bec5f and upgrade com.google.android.material to 1.3.0-alpha02, it works!

**Comment by stefan-niedermann** [comment]
Nice research! Thank you! So let's hope that the final version of `com.google.android.material:1.3.0` will be released soon :slightly_smiling_face:

**Comment by stefan-niedermann** [comment]
[1.3.0-beta01](https://github.com/material-components/material-components-android/releases) was released a few weeks ago. @JenniferJohnson89 when the final version `1.3.0` appears, will you be there to test the behavior? :slightly_smiling_face:

**Comment by stefan-niedermann** [comment]
`v3.1.3` includes the final release of material `1.3.0` library.

Since the Nextcloud app dropped support for Android < `5.0`, we will also drop the support for it in future versions since we depend on the Nextcloud app for the Single Sign On mechanism. I hope the bump to material `1.3.0` solves this issue for you, this would be a great timing :slightly_smiling_face:
