### ISSUE TITLE
cannot add an account

### ISSUE THREAD

**Issue by Davidbrcz** [stefan-niedermann/nextcloud-notes#850]
**Describe the bug**
Impossible to add an existing Nextcloud account and synchronize the notes. 

_Clearing Notes cache doesn't help. Clearing Nextcloud main app as well leads to an exception (writing to a RO SQLDatabase) after first new use, but then it work again._  

**To Reproduce**
1 open the app
2 select an account
3 Allow access
4. Error

**Expected behavior**
The account is added and the notes are synchronized 

**Screenshots**
NA

**Server**
 - Nextcloud-Version: 18.0.5
 - Nextcloud Notes-Version (server app): 3.4.0
 - PHP-Version: 7.3

**Smartphone (please complete the following information):**
  - App Version: 2.12.2
 - App Version Code: 2012002
 - F-Droid or Play Store: F-droid
 - Device: one plus 6
 - Android-Version: oxygen Os 10.3.3 (Android 10)
 - OS Version: 4.9.179-perf+(2004142132)
 - OS API Level: 29

**Stacktrace**
```
com.nextcloud.android.sso.exceptions.TokenMismatchException: Le jeton d'authentification fourni ne correspond pas ou le nom du paquet n'est pas autorisé à effectuer cette action
at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.lambda$null$13$NotesListViewActivity(NotesListViewActivity.java:717)
at it.niedermann.owncloud.notes.android.activity.-$$Lambda$NotesListViewActivity$ApX5jZPpliFMx5irsu2MU1K_PSk.run(Unknown Source:4)
at java.lang.Thread.run(Thread.java:919)
```

Edit: when it works, it's awesome !

**Comment by stefan-niedermann** [comment]
Yeah, just wanted to answer you to clear the cache of both apps. We are aware of this issue but haven't found a final solution yet. Thank you for reporting though, glad to hear that everything works fine for you. 👍
