### ISSUE TITLE
NullPointer during login attempt

### ISSUE THREAD

**Issue by thenickname** [stefan-niedermann/nextcloud-notes#854]
**Describe the bug**
Cannot login anymore. When chosing account, exception occurs (see stacktrace). Web browser and files app work fine.

Removing data, cache, app, account does not change the situation

**To Reproduce**
tbh I don't know how it came to this situation. At some point the app stopped syncing. So I decided to log out and back in. Then the error occured.

**Expected behavior**
Login through notes app works.

**Screenshots**

**Server**
 - Nextcloud-Version: 18.0.4snap3
 - Nextcloud Notes-Version (server app): 
 - PHP-Version: 

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: F-Droid
 - Device: [e.g. Samsung Galaxy S10] Mi Note 10
 - Android-Version: [e.g. 8] 9

**Stacktrace**

```
App Version: 2.12.2
App Version Code: 2012002
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 4.14.83-perf-g613dee7(V11.0.17.0.PFDEUXM)
OS API Level: 28
Device: tucana
Manufacturer: Xiaomi
Model (and Product): Mi Note 10 (tucana_eea)

---

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.substring(int)' on a null object reference
	at it.niedermann.owncloud.notes.persistence.NotesDatabase.addAccount(NotesDatabase.java:689)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.lambda$null$13$NotesListViewActivity(NotesListViewActivity.java:718)
	at it.niedermann.owncloud.notes.android.activity.-$$Lambda$NotesListViewActivity$ApX5jZPpliFMx5irsu2MU1K_PSk.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by thenickname** [comment]
After clearing cache and app data in the Files app and attempting another login from within Notes app, I got this:

```
App Version: 2.12.2
App Version Code: 2012002
App Flavor: fdroid

Files App Version Code: 30110190

---

OS Version: 4.14.83-perf-g613dee7(V11.0.17.0.PFDEUXM)
OS API Level: 28
Device: tucana
Manufacturer: Xiaomi
Model (and Product): Mi Note 10 (tucana_eea)

---

java.lang.ClassNotFoundException: com.owncloud.android.lib.common.network.CertificateCombinedException
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1615)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1520)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1776)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2002)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:503)
	at java.lang.Throwable.readObject(Throwable.java:907)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1067)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1902)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1803)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2002)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:503)
	at java.lang.Throwable.readObject(Throwable.java:907)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1067)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1902)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1803)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.deserializeObjectV2(AidlNetworkRequest.java:329)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:167)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.lambda$null$13$NotesListViewActivity(NotesListViewActivity.java:717)
	at it.niedermann.owncloud.notes.android.activity.-$$Lambda$NotesListViewActivity$ApX5jZPpliFMx5irsu2MU1K_PSk.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.owncloud.android.lib.common.network.CertificateCombinedException" on path: DexPathList[[zip file "/data/app/it.niedermann.owncloud.notes-8bvBNj05Tj3KYvWWeO9U0A==/base.apk"],nativeLibraryDirectories=[/data/app/it.niedermann.owncloud.notes-8bvBNj05Tj3KYvWWeO9U0A==/lib/arm64, /system/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 32 more

```

**Comment by stefan-niedermann** [comment]
@thenickname are you able to do a `curl` request from a linux machine? I need the output of

`curl "https://username:password@example.com/ocs/v2.php/cloud/capabilities?format=json" -H 'OCS-APIRequest: true'`

Either strip sensitive information like the domain yourself or send it via E-Mail to info@niedermann.it please.

**Comment by stefan-niedermann** [comment]
I might have found a fix for this issue. Could you please download and install this debug-version?

https://niedermann.it/notes-redesign/fix-nullpointer-exception.apk

You can safely install it in parallel to your existing version. (Don't be surprised, it will look a bit different to what you are used to)

**Comment by thenickname** [comment]
Thanks for the response... I'm afraid the version of the app has other issues, at least on my device:
```
App Version: 2.12.2
App Version Code: 2012002
App Flavor: dev

Files App Version Code: 30110190

---

OS Version: 4.14.83-perf-g613dee7(V11.0.17.0.PFDEUXM)
OS API Level: 28
Device: tucana
Manufacturer: Xiaomi
Model (and Product): Mi Note 10 (tucana_eea)

---

java.lang.IllegalArgumentException: Unknown color
	at android.graphics.Color.parseColor(Color.java:1391)
	at it.niedermann.owncloud.notes.persistence.NotesDatabase.getLocalAccountByAccountName(NotesDatabase.java:777)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.selectAccount(NotesListViewActivity.java:222)
	at it.niedermann.owncloud.notes.android.activity.NotesListViewActivity.lambda$null$11$NotesListViewActivity(NotesListViewActivity.java:708)
	at it.niedermann.owncloud.notes.android.activity.-$$Lambda$NotesListViewActivity$AzssXwwIhl2f-nJ6kKqh7unrVws.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

```

**Comment by stefan-niedermann** [comment]
No that's fine, i think we are getting closer.

Try this one:

https://niedermann.it/notes-redesign/fix-nullpointer-exception-2.apk

The output of [the command[(https://github.com/stefan-niedermann/nextcloud-notes/issues/854#issuecomment-640085763) would be really useful...

**Comment by thenickname** [comment]
Regarding the curl output: 

```
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":18,"minor":0,"micro":4,"string":"18.0.4","edition":"","extendedSupport":false},"capabilities":{"bruteforce":{"delay":200},"spreed":{"features":["audio","video","chat-v2","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","mention-flag","in-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms","chat-read-marker","webinary-lobby","start-call-flag","chat-replies","circles-support"],"config":{"chat":{"max-length":32000}}}}}}}
```

**Comment by thenickname** [comment]
The second apk worked!

**Comment by stefan-niedermann** [comment]
Glad to hear, i will merge the changes and push them out with the next release - but - seriosuly: There are missing so many important entries in this curl output!

Which Notes server app are you using?
Have you disabled the theming app manually or so? There is supposed to be a node `theming`...

**Comment by thenickname** [comment]
Thanks a lot. I will check if there are more Infos available...but this is what curl gave me. Does it make a difference wether I fire the request as admin or as a nonadmin user? Output above is nonadmin.

I use the snap server package with the current notes app. I have to check the versions.

**Comment by stefan-niedermann** [comment]
> Does it make a difference wether I fire the request as admin or as a nonadmin user?

This *might* be possible, yes. Just let me know if you have any further issues (this could prevent bugs in the future).

**Comment by thenickname** [comment]
Curl output, now as admin:
```
{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":18,"minor":0,"micro":4,"string":"18.0.4","edition":"","extendedSupport":false},"capabilities":{"core":{"pollinterval":60,"webdav-root":"remote.php\/webdav"},"bruteforce":{"delay":200},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"directEditing":{"url":"https:\/\/nextcloud-nick\/ocs\/v2.php\/apps\/files\/api\/v1\/directEditing","etag":"6226ba873373f5e73a3ef504107523f7"},"versioning":true,"undelete":true},"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"ocm":{"enabled":true,"apiVersion":"1.0-proposal1","endPoint":"https:\/\/nextcloud-nick\/index.php\/ocm","resourceTypes":[{"name":"file","shareTypes":["user","group"],"protocols":{"webdav":"\/public.php\/webdav\/"}}]},"deck":{"version":"1.0.2"},"dav":{"chunking":"1.0"},"files_sharing":{"api_enabled":true,"public":{"enabled":true,"password":{"enforced":false,"askForOptionalPassword":false},"expire_date":{"enabled":false},"multiple_links":true,"expire_date_internal":{"enabled":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"user":{"send_mail":false,"expire_date":{"enabled":true}},"group_sharing":true,"group":{"enabled":true,"expire_date":{"enabled":true}},"default_permissions":31,"federation":{"outgoing":true,"incoming":true,"expire_date":{"enabled":true}},"sharee":{"query_lookup_default":false},"sharebymail":{"enabled":true,"upload_files_drop":{"enabled":true},"password":{"enabled":true},"expire_date":{"enabled":true}}},"notes":{"api_version":["0.2","1.1"]},"notifications":{"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings","action-web"],"push":["devices","object-data","delete"],"admin-notifications":["ocs","cli"]},"password_policy":{"minLength":8,"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"api":{"generate":"https:\/\/nextcloud-nick\/ocs\/v2.php\/apps\/password_policy\/api\/v1\/generate","validate":"https:\/\/nextcloud-nick\/ocs\/v2.php\/apps\/password_policy\/api\/v1\/validate"}},"spreed":{"features":["audio","video","chat-v2","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","mention-flag","in-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms","chat-read-marker","webinary-lobby","start-call-flag","chat-replies","circles-support"],"config":{"chat":{"max-length":32000}}}}}}}
```

And thanks again

**Comment by thenickname** [comment]
Curl output, now as admin:

{"ocs":{"meta":{"status":"ok","statuscode":200,"message":"OK"},"data":{"version":{"major":18,"minor":0,"micro":4,"string":"18.0.4","edition":"","extendedSupport":false},"capabilities":{"core":{"pollinterval":60,"webdav-root":"remote.php\/webdav"},"bruteforce":{"delay":200},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"directEditing":{"url":"https:\/\/domain\/ocs\/v2.php\/apps\/files\/api\/v1\/directEditing","etag":"6226ba873373f5e73a3ef504107523f7"},"versioning":true,"undelete":true},"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"ocm":{"enabled":true,"apiVersion":"1.0-proposal1","endPoint":"https:\/\/domain\/index.php\/ocm","resourceTypes":[{"name":"file","shareTypes":["user","group"],"protocols":{"webdav":"\/public.php\/webdav\/"}}]},"deck":{"version":"1.0.2"},"dav":{"chunking":"1.0"},"files_sharing":{"api_enabled":true,"public":{"enabled":true,"password":{"enforced":false,"askForOptionalPassword":false},"expire_date":{"enabled":false},"multiple_links":true,"expire_date_internal":{"enabled":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"user":{"send_mail":false,"expire_date":{"enabled":true}},"group_sharing":true,"group":{"enabled":true,"expire_date":{"enabled":true}},"default_permissions":31,"federation":{"outgoing":true,"incoming":true,"expire_date":{"enabled":true}},"sharee":{"query_lookup_default":false},"sharebymail":{"enabled":true,"upload_files_drop":{"enabled":true},"password":{"enabled":true},"expire_date":{"enabled":true}}},"notes":{"api_version":["0.2","1.1"]},"notifications":{"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings","action-web"],"push":["devices","object-data","delete"],"admin-notifications":["ocs","cli"]},"password_policy":{"minLength":8,"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"api":{"generate":"https:\/\/domain\/ocs\/v2.php\/apps\/password_policy\/api\/v1\/generate","validate":"https:\/\/domain\/ocs\/v2.php\/apps\/password_policy\/api\/v1\/validate"}},"spreed":{"features":["audio","video","chat-v2","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","mention-flag","in-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms","chat-read-marker","webinary-lobby","start-call-flag","chat-replies","circles-support"],"config":{"chat":{"max-length":32000}}}}}}}

And thanks again
