### ISSUE TITLE
App crashes when creating a new category for a note 

### ISSUE THREAD

**Issue by sqwish** [stefan-niedermann/nextcloud-notes#871]
**Android version:** 9

**Device**: Xiaomi Mi A1 

**System language**: English (Ireland)

**App version:** 2.13.3

**App source:** F-Droid

**Steps to reproduce:**
  1. open the app
  2. click on a note
  3. click on the three dots menu at the top right 
  4. click on Category 
  5. start typing a new Category name 
  6. after typing a few characters, app crashes with crash log below 

```
App Version: 2.13.3
App Version Code: 2013003
App Flavor: fdroid

Files App Version Code: 30120090

---

OS Version: 3.18.120-perf-g51b110d(V10.0.21.0.PDHMIXM)
OS API Level: 28
Device: tissot_sprout
Manufacturer: Xiaomi
Model (and Product): Mi A1 (tissot)

---

java.lang.IllegalArgumentException: fromIndex(1) > toIndex(0)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1018)
	at java.util.ArrayList.subList(ArrayList.java:1008)
	at it.niedermann.owncloud.notes.android.fragment.CategoryAdapter.setCategoryList(CategoryAdapter.java:112)
	at it.niedermann.owncloud.notes.android.fragment.CategoryDialogFragment$LoadCategoriesTask.onPostExecute(CategoryDialogFragment.java:181)
	at it.niedermann.owncloud.notes.android.fragment.CategoryDialogFragment$LoadCategoriesTask.onPostExecute(CategoryDialogFragment.java:170)
	at android.os.AsyncTask.finish(AsyncTask.java:695)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:712)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by stefan-niedermann** [comment]
Thanks for the report. This has already been fixed and released. Just waiting for F-Droid to build the app :man_shrugging: 

Workaround: Use Nextcloud app to move the .md file into the new category folder or add the category via Web UI. As soon as the category exists, you can choose it even with this defect version.

**Comment by stefan-niedermann** [comment]
Updated just arrived F-Droid, @sqwish you can now download the new version and everything should be fine again.

**Comment by sqwish** [comment]
Wow, very nice. Completely fixed. Thank you!

**Comment by IngoBelka** [comment]
Sorry for reopen the bug, but I can't find a new version on F-Droid then 2.13.3, and the bug is still present on my Huawei Media Tab. 

```
App Version: 2.13.3
App Version Code: 2013003
App Flavor: fdroid

Files App Version Code: 30120090

---

OS Version: 4.9.148(9.1.0.335C432)
OS API Level: 28
Device: HWSHT
Manufacturer: HUAWEI
Model (and Product): SHT-W09 (SHT-W09)

---

java.lang.IllegalArgumentException: fromIndex(1) > toIndex(0)
	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1018)
	at java.util.ArrayList.subList(ArrayList.java:1008)
	at it.niedermann.owncloud.notes.android.fragment.CategoryAdapter.setCategoryList(CategoryAdapter.java:112)
	at it.niedermann.owncloud.notes.android.fragment.CategoryDialogFragment$LoadCategoriesTask.onPostExecute(CategoryDialogFragment.java:181)
	at it.niedermann.owncloud.notes.android.fragment.CategoryDialogFragment$LoadCategoriesTask.onPostExecute(CategoryDialogFragment.java:170)
	at android.os.AsyncTask.finish(AsyncTask.java:696)
	at android.os.AsyncTask.access$600(AsyncTask.java:180)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:713)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

```

**Comment by stefan-niedermann** [comment]
The new version is definitely available on F-Droid as you can also see [on their website](https://f-droid.org/de/packages/it.niedermann.owncloud.notes/):

[![grafik](https://user-images.githubusercontent.com/4741199/85544404-479c0180-b61b-11ea-827e-884ff558b8b8.png)](https://f-droid.org/de/packages/it.niedermann.owncloud.notes/)


You should refresh your F-Droid refresh or clear the storage of the F-Droid app if nothing helps.

**Comment by IngoBelka** [comment]
I'm in the swedish forest currently, may be the net was to slow. Thank you, now I have the new version, works perfectly.

**Comment by stefan-niedermann** [comment]
Glad to hear that everything works fine for you now :slightly_smiling_face:
