### ISSUE TITLE
Crash because of ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by rugk** [stefan-niedermann/nextcloud-notes#912]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

The app reported a crash to me.

**To Reproduce**
 Not sure what caused this. Was just pasting something or so in a new note/maybe already saved it… :upside_down_face: 

**Expected behavior**

Not crash.

**Screenshots**

N/A

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: FD-Droid
 - Android-Version: 9
 - Device: FP3

**Stacktrace**
```
App Version: 2.16.3
App Version Code: 2016003
App Flavor: fdroid

Files App Version Code: 30120090

---

OS Version: 4.9.112-perf+(04211500)
OS API Level: 28
Device: FP3
Manufacturer: Fairphone
Model (and Product): FP3 (FP3)

---

java.lang.ArrayIndexOutOfBoundsException: length=15; index=-1
	at java.util.ArrayList.get(ArrayList.java:439)
	at it.niedermann.owncloud.notes.main.items.ItemAdapter.getItem(ItemAdapter.java:202)
	at it.niedermann.owncloud.notes.main.items.ItemAdapter.getItemViewType(ItemAdapter.java:222)
	at it.niedermann.owncloud.notes.main.items.section.SectionItemDecoration.getItemOffsets(SectionItemDecoration.java:33)
	at androidx.recyclerview.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:5119)
	at androidx.recyclerview.widget.RecyclerView$LayoutManager.calculateItemDecorationsForChild(RecyclerView.java:9711)
	at androidx.recyclerview.widget.ItemTouchHelper.scrollIfNecessary(ItemTouchHelper.java:750)
	at androidx.recyclerview.widget.ItemTouchHelper$1.run(ItemTouchHelper.java:260)
	at androidx.recyclerview.widget.ItemTouchHelper$2.onTouchEvent(ItemTouchHelper.java:389)
	at androidx.recyclerview.widget.RecyclerView.dispatchToOnItemTouchListeners(RecyclerView.java:3124)
	at androidx.recyclerview.widget.RecyclerView.onTouchEvent(RecyclerView.java:3283)
	at android.view.View.dispatchTouchEvent(View.java:12514)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3024)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2705)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3401)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
	at android.view.View.dispatchPointerEvent(View.java:12753)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5121)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4924)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4441)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4494)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4460)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4600)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4468)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4657)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4441)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4494)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4460)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4468)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4441)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7116)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7085)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7046)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7219)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7190)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7242)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1012)
	at android.view.Choreographer.doCallbacks(Choreographer.java:823)
	at android.view.Choreographer.doFrame(Choreographer.java:752)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:998)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6746)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```

**Comment by stefan-niedermann** [comment]
Thank you for the report, will be fixed in `v2.16.7`.
