### ISSUE TITLE
Nextcloud notes bug

### ISSUE THREAD

**Issue by Oceania2301** [stefan-niedermann/nextcloud-notes#918]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

```
App Version: 2.16.4
App Version Code: 2016004
App Flavor: play

Files App Version Code: 30120190

---

OS Version: 4.14.98-perf+(V11.0.9.0.PCOMIXM)
OS API Level: 28
Device: ginkgo
Manufacturer: Xiaomi
Model (and Product): Redmi Note 8 (ginkgo)

---

com.nextcloud.android.sso.exceptions.TokenMismatchException: Il token di autenticazione fornito non corrisponde o il nome del pacchetto non è permesso per eseguire questa azione
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$20$MainActivity(MainActivity.java:791)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$4HeEjJCK6xYZ8GdVmxdXI3hCjBw.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:764)

```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 
 - F-Droid or Play Store: 
 - Android-Version: 
 - Device: 

**Server**
 - Nextcloud version: 
 - Nextcloud Notes version (server app): 

**Stacktrace**

**Comment by stefan-niedermann** [comment]
Hi @Oceania2301,

have you tried to **clear the cache of both apps** [as described here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error)?

**Comment by stefan-niedermann** [comment]
ping @Oceania2301

**Comment by stefan-niedermann** [comment]
[Why this issue has been closed.](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#why-has-my-bug-report-been-closed)
