### ISSUE TITLE
synchronisation abdroid

### ISSUE THREAD

**Issue by jlgenet** [stefan-niedermann/nextcloud-notes#950]
```
App Version: 2.16.7
App Version Code: 2016007
App Flavor: fdroid

Files App Version Code: 30130090

---

OS Version: 3.18.31-perf-g9aaac6e-00050-g798c233-dirty(eng.nubia.20180817.150508)
OS API Level: 25
Device: NX907J
Manufacturer: nubia
Model (and Product): NX907J (NX907J)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: L'application Nexcloud Files ne répond pas. Veuillez signaler ce problème.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$20$MainActivity(MainActivity.java:791)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$4HeEjJCK6xYZ8GdVmxdXI3hCjBw.run(lambda)
	at java.lang.Thread.run(Thread.java:761)

```

**Comment by stefan-niedermann** [comment]
Please read and follow the steps in the [FAQ](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error). If this doesn't help open a new bug report filling the complete issue template.
