### ISSUE TITLE
Http 302 with HSTS domain

### ISSUE THREAD

**Issue by bashirsouid** [stefan-niedermann/nextcloud-notes#960]
**Describe the bug**
Can't sync app with nextcloud instance hosted on .dev domain. Error report does 302. Used to work with local hostname during initial testing. The error dialog says this often happens if notes app is not installed in nextcloud but I think this is not the case here because app is installed and loads properly from browser. I think most likely the app is trying to make a call over http instead of https and failing to follow the 302 redirect to https which is required for all domains ending in .app, .dev, etc. By the root domain provider (Google).

**To Reproduce**
1. Open app
2. Connect to server with domain like .app or .dev which always requires HTTPS from root level domain.
3. It failed to sync due to 302. 

**Expected behavior**
Load notes from server.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): 2.16.7
 - F-Droid or Play Store: F-droid
 - Android-Version: 10
 - Device: Moto g7

**Server**
 - Nextcloud version: 12
 - Nextcloud Notes version (server app): 

**Stacktrace**
```
App Version: 2.16.7
App Version Code: 2016007
App Flavor: fdroid

Files App Version Code: 30130190

---

OS Version: 4.9.206-perf+(6d15b)
OS API Level: 29
Device: channel
Manufacturer: motorola
Model (and Product): moto g(7) play (channel_amz)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 302
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV02.getNotes(NotesClientV02.java:31)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.IllegalStateException: 
	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1036)
	at android.os.Binder.execTransact(Binder.java:1003)

```

**Comment by stefan-niedermann** [comment]
Have you tried to clear the storage of the Notes **and** the files app as [mentioned here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error)?

**Comment by bashirsouid** [comment]
I hadn't before... Just tried it now but it unfortunately didn't help. Then tried uninstalling and reinstalling and still no luck.

**Comment by bashirsouid** [comment]
I didn't yet try creating a new user account in Nextcloud. Think worth trying here?

**Comment by stefan-niedermann** [comment]
No, just try to clear the storage of **both** apps and readd the account

**Comment by stefan-niedermann** [comment]
In this case i can only redirect you to the corresponding issue in the files app repository: https://github.com/nextcloud/android/issues/6465

Since the notes app doesn't make any network requests itself,  the files app should handle this (and any redirects). Maybe there is some exotic server setup? I'd recommend you to join the discussion and share server details in the linked issue.

Sorry that i can't provide better help here...
