### ISSUE TITLE
ClassNotFound Exception

### ISSUE THREAD

**Issue by fschaupp** [stefan-niedermann/nextcloud-notes#961]
Hi!
I got this exception after adding a new nextloud-account to the app.

```
App Version: 2.16.7
App Version Code: 2016007
App Flavor: fdroid

Files App Version Code: 30130190

---

OS Version: 4.9.186-perf-gef389aa(V12.0.1.0.QDGMIXM)
OS API Level: 29
Device: polaris
Manufacturer: Xiaomi
Model (and Product): Mi MIX 2S (polaris)

---

java.lang.ClassNotFoundException: com.owncloud.android.lib.common.network.CertificateCombinedException
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:682)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1703)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1594)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1872)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2114)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:557)
	at java.lang.Throwable.readObject(Throwable.java:951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1066)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2013)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1899)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2114)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:557)
	at java.lang.Throwable.readObject(Throwable.java:951)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1066)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2013)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1899)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1412)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:427)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.deserializeObjectV2(AidlNetworkRequest.java:329)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:167)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.CapabilitiesClient.getCapabilities(CapabilitiesClient.java:64)
	at it.niedermann.owncloud.notes.main.MainActivity.lambda$null$20$MainActivity(MainActivity.java:791)
	at it.niedermann.owncloud.notes.main.-$$Lambda$MainActivity$4HeEjJCK6xYZ8GdVmxdXI3hCjBw.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.lang.ClassNotFoundException: com.owncloud.android.lib.common.network.CertificateCombinedException
	... 32 more

```

**Comment by stefan-niedermann** [comment]
Hi, Are you able to use the main Nextcloud app without any issue?

**Comment by fschaupp** [comment]
> Hi, Are you able to use the main Nextcloud app without any issue?

Yes ^^'

**Comment by stefan-niedermann** [comment]
cc @David-Development and @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
> com.owncloud.android.lib.common.network.CertificateCombinedException

This is in our lib.
No idea why this could not be found…As if all classes in lib could not be resolved, it would lead to more crashes…

**Comment by stefan-niedermann** [comment]
@fschaupp would you mind reopen this issue in this repository: https://github.com/nextcloud/Android-SingleSignOn/issues/new please?

Maybe worth a try to fence this error:
- Try the Nextcloud News app or Nextcloud Deck app and check if you get the same error
- Try on another device and tell us whether it works there

Thank you!

**Comment by fschaupp** [comment]
> @fschaupp would you mind reopen this issue in this repository: https://github.com/nextcloud/Android-SingleSignOn/issues/new please?
> 
> Maybe worth a try to fence this error:
> 
> * Try the Nextcloud News app or Nextcloud Deck app and check if you get the same error
> * Try on another device and tell us whether it works there
> 
> Thank you!

Hi Stefan!
Today I tried it again and everything worked. All of the 3 apps. I think I never got the SSO-Popup for allowing the acess to the nextcloud files before.

**Comment by stefan-niedermann** [comment]
Thank you for the update!

I think we can safely close https://github.com/nextcloud/Android-SingleSignOn/issues/253 too (and reopen in case you ever stumble over this issue again), what do you think?
