### ISSUE TITLE
Accounts Won't Sync

### ISSUE THREAD

**Issue by pebkacs** [stefan-niedermann/nextcloud-notes#977]
# System Info
2 separate Nextcloud servers (v19.0.3)
Android v11 (Pixel 3)
Notes Android (F-Droid) v2.17.1

# Issue
Neither of my accounts will sync notes.  Each time I open the app or switch accounts in the app I get the HTTP-500 "Synchronization failed" error.  I have even tried completely removing each account, uninstalling/reinstalling the app.  Thank you for this great app and your support!

# Error Report

```
App Version: 2.17.1
App Version Code: 2017001
App Flavor: fdroid

Files App Version Code: 30130190

---

OS Version: 4.9.223-g5bded8e40b62-ab6647920(6720564)
OS API Level: 30
Device: blueline
Manufacturer: Google
Model (and Product): Pixel 3 (blueline)

---

com.nextcloud.android.sso.exceptions.NextcloudHttpRequestFailedException: HTTP request failed with HTTP status-code: 500
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:172)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.putNote(NotesClientV1.java:41)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.createNote(NotesClientV1.java:45)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pushLocalChanges(NoteServerSyncHelper.java:384)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:347)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$3.call(AsyncTask.java:394)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.lang.IllegalStateException: {"errorType":"OCP\\Files\\NotPermittedException"}

	at com.nextcloud.android.sso.InputStreamBinder.processRequestV2(InputStreamBinder.java:429)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestAndBodyStreamV2(InputStreamBinder.java:125)
	at com.nextcloud.android.sso.InputStreamBinder.performNextcloudRequestV2(InputStreamBinder.java:108)
	at com.nextcloud.android.sso.aidl.IInputStreamService$Stub.onTransact(IInputStreamService.java:158)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)
```

**Comment by stefan-niedermann** [comment]
What's in the server log? The error message says, it's a `HTTP 500` error, what basically means, that the server has an issue.
Do you have installed and enabled the [correct server app](https://apps.nextcloud.com/apps/notes)?

**Comment by pebkacs** [comment]
I think this is from one of those instances:

```
Error
no app in context
2020-10-16T07:09:47-0700
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "notes.page.index" as such route does not exist.

    /var/www/nextcloud/lib/private/Route/Router.php - line 338:

    Symfony\Component\Routing\Generator\UrlGenerator->generate("notes.page.index", [], 1)

    /var/www/nextcloud/lib/private/Route/CachingRouter.php - line 60:

    OC\Route\Router->generate("notes.page.index", [], false)

    /var/www/nextcloud/lib/private/URLGenerator.php - line 83:

    OC\Route\CachingRouter->generate("notes.page.index", [])

    /var/www/nextcloud/lib/private/NavigationManager.php - line 294:

    OC\URLGenerator->linkToRoute("notes.page.index")

    /var/www/nextcloud/lib/private/NavigationManager.php - line 115:

    OC\NavigationManager->init()

    /var/www/nextcloud/apps/theming/lib/ThemingDefaults.php - line 183:

    OC\NavigationManager->getAll("guest")

    /var/www/nextcloud/lib/private/legacy/OC_Defaults.php - line 263:

    OCA\Theming\ThemingDefaults->getShortFooter()

    /var/www/nextcloud/lib/public/Defaults.php - line 169:

    OC_Defaults->getLongFooter()

    /var/www/nextcloud/core/templates/layout.guest.php - line 55:

    OCP\Defaults->getLongFooter()

    /var/www/nextcloud/lib/private/Template/Base.php - line 178:

    include("/var/www/ne ... p")

    /var/www/nextcloud/lib/private/Template/Base.php - line 150:

    OC\Template\Base->load("/var/www/ne ... p", null)

    /var/www/nextcloud/lib/private/legacy/OC_Template.php - line 182:

    OC\Template\Base->fetchPage(null)

    /var/www/nextcloud/lib/private/legacy/OC_Template.php - line 213:

    OC_Template->fetchPage(null)

    /var/www/nextcloud/lib/private/Template/Base.php - line 132:

    OC_Template->fetchPage()

    /var/www/nextcloud/lib/private/legacy/OC_Template.php - line 334:

    OC\Template\Base->printPage()

    /var/www/nextcloud/index.php - line 63:

    OC_Template::printExceptionErrorPage(Exception {}, 500)
```
I've had this issue for a few months across multiple Android devices, I just finally got some time to report it.  However, after reading issue #537, it ripped me off about toggling the "Sync only on Wi-Fi" setting.  I ran it set to "off" for a while and both accounts synced without throwing the error.  I have since toggled it back to "on", and no issues even after rebooting my phone.

**Comment by stefan-niedermann** [comment]
Phew, this log looks pretty useles for me, but i also don't know much about the server side. Maybe @korelstar can have a look whether he can fiddle out something?

@pebkacs please tell us the version of your Notes server app - the issue template is there for a reason, please use it next time. 🙂

**Comment by stefan-niedermann** [comment]
Does the Notes app work properly in a web browser? Can please make a screenshit of it (remove sensitive content before posting it here)?

**Comment by pebkacs** [comment]
> Phew, this log looks pretty useles for me, but i also don't know much about the server side. Maybe @korelstar can have a look whether he can fiddle out something?
> 
> @pebkacs please tell us the version of your Notes server app - the issue template is there for a reason, please use it next time. 🙂

There's a template?  Sorry, guess I missed it.

Notes App on server is v3.6.4.  It has always worked fine in the web browser.

![Screenshot_20201016-233126](https://user-images.githubusercontent.com/16310537/96330148-d3410000-1007-11eb-8d30-ce60f2f3b86f.png)

**Comment by stefan-niedermann** [comment]
I know it's been a while, but i would like to ask you to open this issue in the [repository of the server app](https://github.com/nextcloud/notes/issues/new?assignees=&labels=bug%2C+need+to+reproduce&template=bug_report.md&title=) (i am watching it and will be aware of it)

The log of the server clearly hints for an error in the server app (or your server environment):

```
Error
no app in context
2020-10-16T07:09:47-0700
Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "notes.page.index" as such route does not exist.
```

Sorry, there is nothing that we could do at the Android apps side unfortunately 🤷‍♂️

**Comment by pebkacs** [comment]
Thanks for following up on this, @stefan-niedermann.  I will see if I can find some time to open a ticket in the other repo, per your suggestion.
