### ISSUE TITLE
App does not synchronize

### ISSUE THREAD

**Issue by dominikprager** [stefan-niedermann/nextcloud-notes#982]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

The App does not synchronize to the Server. When I first login, there is no problem. The notes are synchronized. Next time I start the App, the synchronizing-circle is turning and turning until the error-message comes up.

**Smartphone**
 - Nextcloud Notes-Version (android app): v2.16.7 
 - F-Droid or Play Store: Play Store
 - Android-Version: 8.1
 - Device: Blackberry KeyOne

**Server**
 - Nextcloud version: 18.04
 - Nextcloud Notes version (server app): 3.6.4

**Stacktrace**
```
App Version: 2.16.7
App Version Code: 2016007
App Flavor: play

Files App Version Code: 30130090

---

OS Version: 3.18.71-perf-g0f5ce2e(ABT975)
OS API Level: 27
Device: bbb100
Manufacturer: BlackBerry
Model (and Product): BBB100-2 (bbb100emea)

---

com.nextcloud.android.sso.exceptions.NextcloudApiNotRespondingException: Die Nextcloud-Deitei-App-Api reagiert nicht. Bitte melden Sie diesen Fehler.
	at com.nextcloud.android.sso.api.AidlNetworkRequest.waitForApi(AidlNetworkRequest.java:147)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performAidlNetworkRequestV2(AidlNetworkRequest.java:278)
	at com.nextcloud.android.sso.api.AidlNetworkRequest.performNetworkRequestV2(AidlNetworkRequest.java:165)
	at com.nextcloud.android.sso.api.NextcloudAPI.performNetworkRequestV2(NextcloudAPI.java:148)
	at it.niedermann.owncloud.notes.persistence.SSOClient.requestFilesApp(SSOClient.java:27)
	at it.niedermann.owncloud.notes.persistence.NotesClient.requestServer(NotesClient.java:167)
	at it.niedermann.owncloud.notes.persistence.NotesClientV1.getNotes(NotesClientV1.java:31)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.pullRemoteChanges(NoteServerSyncHelper.java:435)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:349)
	at it.niedermann.owncloud.notes.persistence.NoteServerSyncHelper$SyncTask.doInBackground(NoteServerSyncHelper.java:307)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by stefan-niedermann** [comment]
Have you tried to disable the Android battery optimization for the Nextcloud app?

**Comment by dominikprager** [comment]
> 
> 
> Have you tried to disable the Android battery optimization for the Nextcloud app?

Yes. It is disabled both for the Nextcloud App and the Notes App.

**Comment by stefan-niedermann** [comment]
Have you tried to clear the storage of both apps as [described here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error)

Did it happen all of out sudden or after an update? Did it work at any time before or never at all?

**Comment by dominikprager** [comment]
> 
> 
> Have you tried to clear the storage of both apps as [described here](https://github.com/stefan-niedermann/nextcloud-notes/blob/master/FAQ.md#i-have-experienced-an-error)

Yes I've tried several times. It works for a while (a Minute), but then it's like as described at the beginning.

> Did it happen all of out sudden or after an update? Did it work at any time before or never at all?
The problem happens since February/March 2020. Maybe after an update. Before that it worked well.

**Comment by stefan-niedermann** [comment]
Hmm... another user with a similar problem was able to solve this issue by granting the Nextcloud app the "Auto-Start" permission - see https://github.com/stefan-niedermann/nextcloud-deck/issues/660#issuecomment-682002392
This depends on the manufacturers which unfortunately often manipulate the Android system.

Maybe you could try that, too?

If it also fails, i could offer to refund the money of course (Send me your Play Store order ID to info@niedermann.it) and we can open an issue at the [Nextcloud Single-Sign-On issue tracker](https://github.com/nextcloud/Android-SingleSignOn/issues/new) as the problem is caused there.

You alternatively could install the [F-Droid app store](https://f-droid.org/) and install the Notes app from there (for free), just to verify if this could solve the issue for you?

**Comment by bentolor** [comment]
Had the same issue after upgrading and reauthorizing in the Nextcloud app. 

Needed to uninstall Notes app. On restart it asked for the account to use and sync started to work again. Hat so save unsynchronized changes on the app for that.

**Comment by stefan-niedermann** [comment]
@dominikprager any updates?

**Comment by stefan-niedermann** [comment]
Closing since lack of response. If it occurs again, feel free to add your input to [this issue](https://github.com/nextcloud/Android-SingleSignOn/issues/162) in the Nextcloud Single Sign On repository and try out the solutions that already worked for others (turn off shitty vendor battery "optimizations", grant auto-start permissions, clear storage, ...)
