### ISSUE TITLE
App crashes on tapping empty entry in checklist

### ISSUE THREAD

**Issue by nobodywasishere** [stefan-niedermann/nextcloud-notes#985]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

The app crashes whenever you create an empty entry in a checklist and tap on it from markdown view.

**To Reproduce**
1. Create a new note with:
```
List:
- [ ] thing 1
- [ ] thing 2
- [ ]
```
2. Click on the eye icon to open in markdown view
3. Tap around the bottom of "thing 2"

**Expected behavior**

The app doesn't crash. Fixing this would either mean rendering the empty entry or removing it before rendering to remove the crash. The app doesn't crash when the extra `- [ ]` isn't there.

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app): v2.17.1
 - F-Droid or Play Store: F-Droid
 - Android-Version: 9 (LineageOS 16.0)
 - Device: OnePlus 3

**Server**
 - Nextcloud version: 19.0.3
 - Nextcloud Notes version (server app): 3.6.4

**Stacktrace**

```
App Version: 2.17.1
App Version Code: 2017001
App Flavor: fdroid

Files App Version Code: 30130190

---

OS Version: 3.18.120-lineageos-g682d339(8ed3bd4da7)
OS API Level: 28
Device: OnePlus3
Manufacturer: OnePlus
Model (and Product): ONEPLUS A3000 (lineage_oneplus3)

---

java.lang.StringIndexOutOfBoundsException
 at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:61)
 at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:1194)
 at com.yydcdut.markdown.utils.TextHelper.formatTodoLine(TextHelper.java:208)
 at com.yydcdut.markdown.syntax.text.TodoSyntax.onTodoClicked(TodoSyntax.java:93)
 at com.yydcdut.markdown.utils.SyntaxUtils$1.onClick(SyntaxUtils.java:266)
 at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:231)
 at android.widget.TextView.onTouchEvent(TextView.java:10106)
 at android.view.View.dispatchTouchEvent(View.java:12513)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3030)
 at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2719)
 at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:440)
 at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1830)
 at android.app.Activity.dispatchTouchEvent(Activity.java:3401)
 at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
 at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
 at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:398)
 at android.view.View.dispatchPointerEvent(View.java:12752)
 at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5113)
 at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4916)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
 at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4592)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
 at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4649)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
 at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4486)
 at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4452)
 at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4460)
 at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4433)
 at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7099)
 at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7068)
 at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7029)
 at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7202)
 at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:186)
 at android.os.MessageQueue.nativePollOnce(Native Method)
 at android.os.MessageQueue.next(MessageQueue.java:326)
 at android.os.Looper.loop(Looper.java:160)
 at android.app.ActivityThread.main(ActivityThread.java:6718)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
```

**Comment by nobodywasishere** [comment]
This is a duplicate of #908. Closing
