### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by markushub** [stefan-niedermann/nextcloud-notes#995]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

inside a Markdown dokument I select all and App crashed

**To Reproduce**

- Select all 
- Cut
- Hit Space

**Expected behavior**

No Crash
please Lock at stacktrace

**Screenshots**

**Smartphone (please complete the following information):**
 - Nextcloud Notes-Version (android app):  30140090
 - F-Droid or Play Store: F
 - Android-Version: 10
 - Device: potter

**Server**
 - Nextcloud version: 20.0.2
 - Nextcloud Notes version (server app): 

**Stacktrace**
```
App Version: 2.17.1
App Version Code: 2017001
App Flavor: fdroid

Files App Version Code: 30140090

---

OS Version: 3.18.120-perf-Arrow(2048)
OS API Level: 29
Device: potter
Manufacturer: motorola
Model (and Product): Moto G5 Plus (XT1685) (Moto G5 Plus)

---

java.lang.IndexOutOfBoundsException: charAt: 0 >= length 0
	at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:124)
	at android.text.CharSequenceCharacterIterator.current(CharSequenceCharacterIterator.java:58)
	at android.text.CharSequenceCharacterIterator.first(CharSequenceCharacterIterator.java:44)
	at android.icu.text.RuleBasedBreakIterator.CISetIndex32(RuleBasedBreakIterator.java:1046)
	at android.icu.text.RuleBasedBreakIterator.isBoundary(RuleBasedBreakIterator.java:500)
	at android.text.method.WordIterator.isBoundary(WordIterator.java:101)
	at android.widget.Editor$SelectionHandleView.positionAtCursorOffset(Editor.java:5562)
	at android.widget.Editor$HandleView.invalidate(Editor.java:4610)
	at android.widget.Editor$SelectionModifierCursorController.invalidateHandles(Editor.java:6254)
	at android.widget.Editor.invalidateHandlesAndActionMode(Editor.java:2007)
	at android.widget.TextView.spanChange(TextView.java:10732)
	at android.widget.TextView$ChangeWatcher.onSpanRemoved(TextView.java:13457)
	at android.text.SpannableStringBuilder.sendSpanRemoved(SpannableStringBuilder.java:1296)
	at android.text.SpannableStringBuilder.removeSpan(SpannableStringBuilder.java:501)
	at android.text.SpannableStringBuilder.removeSpan(SpannableStringBuilder.java:801)
	at android.text.SpannableStringBuilder.removeSpan(SpannableStringBuilder.java:789)
	at com.yydcdut.markdown.utils.SyntaxUtils.removeSpans(SyntaxUtils.java:294)
	at com.yydcdut.markdown.live.HeaderLive.format(HeaderLive.java:90)
	at com.yydcdut.markdown.live.HeaderLive.onTextChanged(HeaderLive.java:63)
	at com.yydcdut.markdown.live.LivePrepare.onTextChanged(LivePrepare.java:81)
	at com.yydcdut.markdown.MarkdownEditText.onTextChanged4Controller(MarkdownEditText.java:252)
	at com.yydcdut.markdown.MarkdownEditText.access$700(MarkdownEditText.java:44)
	at com.yydcdut.markdown.MarkdownEditText$EditTextWatcher.onTextChanged(MarkdownEditText.java:176)
	at android.widget.TextView.sendOnTextChanged(TextView.java:10550)
	at android.widget.TextView.handleTextChanged(TextView.java:10657)
	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:13418)
	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1267)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:576)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:230)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:37)
	at android.text.method.BaseKeyListener.deleteSelection(BaseKeyListener.java:433)
	at android.text.method.BaseKeyListener.backspaceOrForwardDelete(BaseKeyListener.java:328)
	at android.text.method.BaseKeyListener.backspace(BaseKeyListener.java:71)
	at android.text.method.BaseKeyListener.onKeyDown(BaseKeyListener.java:479)
	at android.text.method.QwertyKeyListener.onKeyDown(QwertyKeyListener.java:362)
	at android.text.method.TextKeyListener.onKeyDown(TextKeyListener.java:141)
	at android.widget.TextView.doKeyDown(TextView.java:8445)
	at android.widget.TextView.onKeyDown(TextView.java:8202)
	at android.view.KeyEvent.dispatch(KeyEvent.java:2801)
	at android.view.View.dispatchKeyEvent(View.java:13890)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.widget.ScrollView.dispatchKeyEvent(ScrollView.java:491)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at android.view.ViewGroup.dispatchKeyEvent(ViewGroup.java:1922)
	at com.android.internal.policy.DecorView.superDispatchKeyEvent(DecorView.java:453)
	at com.android.internal.policy.PhoneWindow.superDispatchKeyEvent(PhoneWindow.java:1840)
	at android.app.Activity.dispatchKeyEvent(Activity.java:3971)
	at androidx.core.app.ComponentActivity.superDispatchKeyEvent(ComponentActivity.java:122)
	at androidx.core.view.KeyEventDispatcher.dispatchKeyEvent(KeyEventDispatcher.java:84)
	at androidx.core.app.ComponentActivity.dispatchKeyEvent(ComponentActivity.java:140)
	at androidx.appcompat.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:569)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.dispatchKeyEvent(AppCompatDelegateImpl.java:3054)
	at androidx.appcompat.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
	at com.android.internal.policy.DecorView.dispatchKeyEvent(DecorView.java:367)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:5583)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5451)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5117)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5174)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5011)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4977)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4985)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4958)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7683)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7652)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7613)
	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4728)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)

```

**Comment by stefan-niedermann** [comment]
Please [read this](https://github.com/stefan-niedermann/nextcloud-notes/issues/991#issuecomment-732432222) - the answer is the same.
