### ISSUE TITLE
App crashes when dragging a checkbox in preview mode

### ISSUE THREAD

**Issue by monoclecat** [stefan-niedermann/nextcloud-notes#997]
Please use **[GitHub reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/)** 👍 to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!

**Describe the bug**

App crashes if you drag a checkbox to the right in preview mode.

**To Reproduce**
1. In the app, create a note with a checkbox, for example "- [ ] abc"
2. Go into Preview mode by pressing the eye icon
3. Touch the checkbox and drag it to the right
4. App crashes with error "Drag shadow dimensions must be positive"

**Smartphone**
 - Nextcloud Notes-Version (android app): 2.17.1
 - F-Droid or Play Store: F-Droid
 - Android-Version: 10 QKQ1.190828.002
 - Device: Mi 8

**Server**
Can provide, but I don't think server information is relevant here.

**Stacktrace**
```
App Version: 2.17.1
App Version Code: 2017001
App Flavor: fdroid

Files App Version Code: 30140190

---

OS Version: 4.9.186-perf-g61e16d5(V12.0.1.0.QEAMIXM)
OS API Level: 29
Device: dipper
Manufacturer: Xiaomi
Model (and Product): MI 8 (dipper)

---

java.lang.IllegalStateException: Drag shadow dimensions must be positive
	at android.view.View.startDragAndDrop(View.java:25739)
	at android.widget.Editor.startDragAndDrop(Editor.java:1241)
	at android.widget.Editor.performLongClick(Editor.java:1267)
	at android.widget.TextView.performLongClick(TextView.java:12244)
	at android.view.View.performLongClick(View.java:7241)
	at android.view.View$CheckForLongPress.run(View.java:27642)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7562)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

**Comment by stefan-niedermann** [comment]
Please read here: https://github.com/stefan-niedermann/nextcloud-notes/issues/909#issuecomment-663973289

Closing in favor of https://github.com/stefan-niedermann/nextcloud-notes/issues/549 since we made much progress in the last few days.
